import express from 'express';import {ApiError,required,integer} from './errors.js';import {authService,publicUser} from './auth.js';import {repository} from './repository.js';import {escapeHtml} from './security.js';
const now=()=>new Date().toISOString();
const parse=(value,fallback)=>{try{return JSON.parse(value);}catch{return fallback;}};
const contentJson=row=>({...row,tags:parse(row.tags,[]),body:parse(row.body,[])});
const mediaJson=row=>({id:row.id,owner_id:row.owner_id,filename:row.filename,mime_type:row.mime_type,alt_text:row.alt_text,caption:row.caption,version:row.version,created_at:row.created_at,size:row.bytes.length});
const version=(body,row)=>{integer(body.version,1,Number.MAX_SAFE_INTEGER,'version');if(body.version!==row.version)throw new ApiError(409,'stale_version','The resource has changed.');};
const jsonArray=(value,name)=>{if(!Array.isArray(value))throw new ApiError(422,'validation_error',`${name} must be an array.`,{[name]:'invalid'});return value;};
const contentAccess=(user,row)=>{if(user.role==='author'&&row.author_id!==user.id)throw new ApiError(403,'forbidden','Content belongs to another author.');};
const editable=row=>{if(!['draft','rejected'].includes(row.status))throw new ApiError(409,'invalid_state','Content is not editable in its current state.');};
const render=blocks=>jsonArray(blocks,'body').map(block=>{if(!block||!['heading','paragraph','quote'].includes(block.type)||typeof block.text!=='string')throw new ApiError(422,'validation_error','Invalid rich-text block.');const text=escapeHtml(block.text);return block.type==='heading'?`<h2>${text}</h2>`:block.type==='quote'?`<blockquote>${text}</blockquote>`:`<p>${text}</p>`;}).join('');
const pathValue=(value,name)=>{if(typeof value!=='string'||!/^\/[a-z0-9/_-]*$/i.test(value)||value.includes('//'))throw new ApiError(422,'validation_error',`Invalid ${name}.`,{[name]:'invalid'});return value;};
export function createApp({db,env=process.env}){const app=express(),auth=authService(db,env),repo=repository(db);app.disable('x-powered-by');app.use(express.json({limit:'2mb'}));app.use(express.static('public'));

 app.post('/api/auth/register',(req,res)=>res.status(201).json({user:auth.register(req,res)}));
 app.post('/api/auth/login',(req,res)=>res.json({user:auth.login(req,res)}));
 app.post('/api/auth/logout',(req,res)=>{auth.current(req);auth.logout(req,res);res.json({logged_out:true});});
 app.post('/api/auth/password-reset-requests',(req,res)=>res.json(auth.requestReset(req)));
 app.post('/api/auth/password-resets',(req,res)=>res.json(auth.reset(req)));

 app.post('/api/content',(req,res)=>{const user=auth.current(req,['author','editor']);required(req.body,['type','title','slug']);if(!['post','page'].includes(req.body.type)||!/^[-a-z0-9]{3,80}$/.test(req.body.slug))throw new ApiError(422,'validation_error','Invalid content type or slug.');const tags=jsonArray(req.body.tags??[],'tags');try{const t=now(),r=db.prepare("INSERT INTO content(author_id,type,title,slug,excerpt,category,tags,body,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,'draft',?,?)").run(user.id,req.body.type,String(req.body.title).trim(),req.body.slug,String(req.body.excerpt??''),String(req.body.category??''),JSON.stringify(tags),'[]',t,t);res.status(201).json(contentJson(repo.content(r.lastInsertRowid)));}catch(e){if(e.code==='SQLITE_CONSTRAINT_UNIQUE')throw new ApiError(409,'slug_exists','Slug is already in use.');throw e;}});
 app.get('/api/content/:id',(req,res)=>{const user=auth.current(req,['author','editor']);const row=repo.content(Number(req.params.id));contentAccess(user,row);res.json(contentJson(row));});
 app.patch('/api/content/:id',(req,res)=>{const user=auth.current(req,['author','editor']),row=repo.content(Number(req.params.id));contentAccess(user,row);editable(row);version(req.body,row);const tags=req.body.tags===undefined?parse(row.tags,[]):jsonArray(req.body.tags,'tags');if(req.body.slug!==undefined&&!/^[-a-z0-9]{3,80}$/.test(req.body.slug))throw new ApiError(422,'validation_error','Invalid slug.');try{db.prepare('UPDATE content SET title=?,slug=?,excerpt=?,category=?,tags=?,version=version+1,updated_at=? WHERE id=?').run(req.body.title??row.title,req.body.slug??row.slug,req.body.excerpt??row.excerpt,req.body.category??row.category,JSON.stringify(tags),now(),row.id);res.json(contentJson(repo.content(row.id)));}catch(e){if(e.code==='SQLITE_CONSTRAINT_UNIQUE')throw new ApiError(409,'slug_exists','Slug is already in use.');throw e;}});
 app.delete('/api/content/:id',(req,res)=>{const user=auth.current(req,['author','editor']),row=repo.content(Number(req.params.id));contentAccess(user,row);editable(row);version(req.body,row);db.prepare('DELETE FROM content WHERE id=?').run(row.id);res.status(204).end();});

 app.put('/api/content/:id/body',(req,res)=>{const user=auth.current(req,['author','editor']),row=repo.content(Number(req.params.id));contentAccess(user,row);editable(row);version(req.body,row);render(req.body.body);const snapshot=JSON.stringify(contentJson(row));db.transaction(()=>{db.prepare('INSERT INTO content_revisions(content_id,editor_id,snapshot,created_at) VALUES(?,?,?,?)').run(row.id,user.id,snapshot,now());db.prepare('UPDATE content SET body=?,version=version+1,updated_at=? WHERE id=?').run(JSON.stringify(req.body.body),now(),row.id);})();res.json(contentJson(repo.content(row.id)));});
 app.post('/api/content/:id/preview',(req,res)=>{const user=auth.current(req,['author','editor']),row=repo.content(Number(req.params.id));contentAccess(user,row);const blocks=req.body.body??parse(row.body,[]);res.json({content_id:row.id,html:render(blocks)});});

 app.get('/api/media',(req,res)=>{const user=auth.current(req,['author','editor']);let page=Number(req.query.page||1);integer(page,1,10000,'page');const rows=user.role==='author'?db.prepare('SELECT * FROM media_assets WHERE owner_id=? ORDER BY id DESC LIMIT 20 OFFSET ?').all(user.id,(page-1)*20):db.prepare('SELECT * FROM media_assets ORDER BY id DESC LIMIT 20 OFFSET ?').all((page-1)*20);res.json({items:rows.map(mediaJson),page});});
 app.post('/api/media',(req,res)=>{const user=auth.current(req,['author','editor']);required(req.body,['filename','mime_type','content_base64']);const allowed=['image/png','image/jpeg','image/webp','text/plain'];if(!allowed.includes(req.body.mime_type)||!/^[\w.-]{1,100}$/.test(req.body.filename))throw new ApiError(422,'validation_error','Invalid media metadata.');const bytes=Buffer.from(req.body.content_base64,'base64');if(!bytes.length||bytes.length>Number(env.MAX_MEDIA_BYTES||1048576))throw new ApiError(422,'validation_error','Media content size is invalid.');const r=db.prepare('INSERT INTO media_assets(owner_id,filename,mime_type,alt_text,caption,bytes,created_at) VALUES(?,?,?,?,?,?,?)').run(user.id,req.body.filename,req.body.mime_type,String(req.body.alt_text??''),String(req.body.caption??''),bytes,now());res.status(201).json(mediaJson(repo.media(r.lastInsertRowid)));});
 app.patch('/api/media/:id',(req,res)=>{const user=auth.current(req,['author','editor']),row=repo.media(Number(req.params.id));if(user.role==='author'&&row.owner_id!==user.id)throw new ApiError(403,'forbidden','Media belongs to another author.');version(req.body,row);db.prepare('UPDATE media_assets SET alt_text=?,caption=?,version=version+1 WHERE id=?').run(req.body.alt_text??row.alt_text,req.body.caption??row.caption,row.id);res.json(mediaJson(repo.media(row.id)));});
 app.get('/api/media/:id/content',(req,res)=>{const user=auth.current(req,['author','editor']),row=repo.media(Number(req.params.id));if(user.role==='author'&&row.owner_id!==user.id)throw new ApiError(403,'forbidden','Media belongs to another author.');res.type(row.mime_type).send(row.bytes);});
 app.delete('/api/media/:id',(req,res)=>{const user=auth.current(req,['author','editor']),row=repo.media(Number(req.params.id));if(user.role==='author'&&row.owner_id!==user.id)throw new ApiError(403,'forbidden','Media belongs to another author.');version(req.body,row);db.prepare('DELETE FROM media_assets WHERE id=?').run(row.id);res.status(204).end();});

 const transition=(row,user,to,note='')=>{db.transaction(()=>{db.prepare('UPDATE content SET status=?,version=version+1,updated_at=? WHERE id=?').run(to,now(),row.id);db.prepare('INSERT INTO workflow_transitions(content_id,actor_id,from_status,to_status,note,created_at) VALUES(?,?,?,?,?,?)').run(row.id,user.id,row.status,to,note,now());db.prepare('INSERT INTO audit_events(actor_id,action,subject,created_at) VALUES(?,?,?,?)').run(user.id,`content.${to}`,String(row.id),now());})();return contentJson(repo.content(row.id));};
 app.post('/api/content/:id/submit',(req,res)=>{const user=auth.current(req,['author','editor']),row=repo.content(Number(req.params.id));contentAccess(user,row);if(!['draft','rejected'].includes(row.status))throw new ApiError(409,'invalid_state','Only editable content can be submitted.');version(req.body,row);res.json(transition(row,user,'submitted',String(req.body.note??'')));});
 app.post('/api/content/:id/approve',(req,res)=>{const user=auth.current(req,['editor']),row=repo.content(Number(req.params.id));if(row.status!=='submitted')throw new ApiError(409,'invalid_state','Only submitted content can be approved.');version(req.body,row);res.json(transition(row,user,'approved',String(req.body.note??'')));});
 app.post('/api/content/:id/reject',(req,res)=>{const user=auth.current(req,['editor']),row=repo.content(Number(req.params.id));if(row.status!=='submitted')throw new ApiError(409,'invalid_state','Only submitted content can be rejected.');required(req.body,['reason']);version(req.body,row);res.json(transition(row,user,'rejected',String(req.body.reason)));});
 app.post('/api/content/:id/schedule',(req,res)=>{const user=auth.current(req,['editor']),row=repo.content(Number(req.params.id));if(row.status!=='approved')throw new ApiError(409,'invalid_state','Only approved content can be scheduled.');version(req.body,row);const date=new Date(req.body.publish_at);if(Number.isNaN(date.valueOf())||date<=new Date())throw new ApiError(422,'validation_error','Publication time must be in the future.');db.prepare("UPDATE content SET status='scheduled',scheduled_at=?,version=version+1,updated_at=? WHERE id=?").run(date.toISOString(),now(),row.id);res.json(contentJson(repo.content(row.id)));});
 app.post('/api/content/:id/unpublish',(req,res)=>{const user=auth.current(req,['editor']),row=repo.content(Number(req.params.id));if(row.status!=='published')throw new ApiError(409,'invalid_state','Only published content can be unpublished.');version(req.body,row);res.json(transition(row,user,'draft',String(req.body.note??'')));});

 app.get('/api/public/content',(req,res)=>{const page=Number(req.query.page||1);integer(page,1,10000,'page');let rows=db.prepare("SELECT * FROM content WHERE status='published' ORDER BY published_at DESC,id DESC").all();if(req.query.type)rows=rows.filter(x=>x.type===req.query.type);if(req.query.category)rows=rows.filter(x=>x.category===req.query.category);if(req.query.tag)rows=rows.filter(x=>parse(x.tags,[]).includes(req.query.tag));res.json({items:rows.slice((page-1)*20,page*20).map(contentJson),page});});
 app.get('/api/public/content/:slug',(req,res)=>{const row=db.prepare("SELECT * FROM content WHERE slug=? AND status='published'").get(req.params.slug);if(!row)throw new ApiError(404,'not_found','Published content was not found.');res.json(contentJson(row));});

 app.get('/api/public/content/:id/comments',(req,res)=>{const row=repo.content(Number(req.params.id));if(row.status!=='published')throw new ApiError(404,'not_found','Published content was not found.');res.json({items:db.prepare("SELECT id,content_id,author_name,body,created_at FROM comments WHERE content_id=? AND status='published' ORDER BY id").all(row.id)});});
 app.post('/api/public/content/:id/comments',(req,res)=>{const row=repo.content(Number(req.params.id));if(row.status!=='published')throw new ApiError(409,'invalid_state','Comments require published content.');required(req.body,['author_name','email','body']);if(!/^\S+@\S+\.\S+$/.test(req.body.email)||String(req.body.body).length>2000)throw new ApiError(422,'validation_error','Invalid comment.');const r=db.prepare('INSERT INTO comments(content_id,author_name,email,body,created_at) VALUES(?,?,?,?,?)').run(row.id,String(req.body.author_name),String(req.body.email).toLowerCase(),String(req.body.body),now());res.status(201).json(repo.comment(r.lastInsertRowid));});
 app.post('/api/admin/comments/:id/moderate',(req,res)=>{const user=auth.current(req,['moderator','admin']),row=repo.comment(Number(req.params.id));required(req.body,['status']);if(!['published','hidden'].includes(req.body.status))throw new ApiError(422,'validation_error','Invalid moderation status.');db.prepare('UPDATE comments SET status=?,moderation_reason=? WHERE id=?').run(req.body.status,String(req.body.reason??''),row.id);db.prepare('INSERT INTO audit_events(actor_id,action,subject,created_at) VALUES(?,?,?,?)').run(user.id,'comment.moderated',String(row.id),now());res.json(repo.comment(row.id));});

 app.get('/api/templates',(req,res)=>{auth.current(req,['editor','admin']);res.json({items:db.prepare('SELECT * FROM templates ORDER BY id').all()});});
 app.post('/api/templates',(req,res)=>{auth.current(req,['editor','admin']);required(req.body,['name','content_type','markup']);if(!['post','page'].includes(req.body.content_type)||!String(req.body.markup).includes('{{body}}'))throw new ApiError(422,'validation_error','Invalid template.');try{const r=db.prepare('INSERT INTO templates(name,content_type,markup) VALUES(?,?,?)').run(req.body.name,req.body.content_type,req.body.markup);res.status(201).json(repo.template(r.lastInsertRowid));}catch(e){if(e.code==='SQLITE_CONSTRAINT_UNIQUE')throw new ApiError(409,'template_exists','Template name already exists.');throw e;}});
 app.patch('/api/templates/:id',(req,res)=>{auth.current(req,['editor','admin']);const row=repo.template(Number(req.params.id));version(req.body,row);const markup=req.body.markup??row.markup;if(!String(markup).includes('{{body}}'))throw new ApiError(422,'validation_error','Template must contain a body placeholder.');db.prepare('UPDATE templates SET name=?,markup=?,version=version+1 WHERE id=?').run(req.body.name??row.name,markup,row.id);res.json(repo.template(row.id));});
 app.put('/api/content/:id/template',(req,res)=>{auth.current(req,['editor','admin']);const row=repo.content(Number(req.params.id)),template=repo.template(req.body.template_id);version(req.body,row);if(template.content_type!==row.type)throw new ApiError(409,'incompatible_template','Template is incompatible with this content type.');db.prepare('UPDATE content SET template_id=?,version=version+1,updated_at=? WHERE id=?').run(template.id,now(),row.id);res.json(contentJson(repo.content(row.id)));});

 app.get('/api/admin/users',(req,res)=>{auth.current(req,['admin']);const page=Number(req.query.page||1);integer(page,1,10000,'page');res.json({items:db.prepare('SELECT * FROM users ORDER BY id LIMIT 20 OFFSET ?').all((page-1)*20).map(publicUser),page});});
 app.patch('/api/admin/users/:id/roles',(req,res)=>{const actor=auth.current(req,['admin']),row=repo.user(Number(req.params.id));required(req.body,['role']);version(req.body,row);const allowed=['author','editor','admin','moderator'];if(!allowed.includes(req.body.role))throw new ApiError(422,'validation_error','Unknown assignable role.');if(row.id===actor.id&&req.body.role!=='admin')throw new ApiError(409,'last_admin_guard','An administrator cannot remove their own admin role.');db.prepare('UPDATE users SET role=?,version=version+1 WHERE id=?').run(req.body.role,row.id);res.json(publicUser(repo.user(row.id)));});
 app.get('/api/admin/roles',(req,res)=>{auth.current(req,['admin']);res.json({items:db.prepare('SELECT * FROM roles ORDER BY id').all().map(x=>({...x,capabilities:parse(x.capabilities,[])}))});});
 app.patch('/api/admin/roles/:id',(req,res)=>{auth.current(req,['admin']);const row=repo.role(Number(req.params.id));version(req.body,row);const capabilities=jsonArray(req.body.capabilities,'capabilities');const allowed=['content:create','content:own','content:edit','content:publish','media:manage','comments:moderate','site:admin'];if(!capabilities.every(x=>allowed.includes(x)))throw new ApiError(422,'validation_error','Unknown capability.');db.prepare('UPDATE roles SET capabilities=?,version=version+1 WHERE id=?').run(JSON.stringify([...new Set(capabilities)]),row.id);const updated=repo.role(row.id);res.json({...updated,capabilities:parse(updated.capabilities,[])});});

 app.get('/api/admin/settings',(req,res)=>{auth.current(req,['admin']);res.json({items:db.prepare('SELECT * FROM settings ORDER BY key').all().map(x=>({...x,value:parse(x.value,x.value)}))});});
 app.patch('/api/admin/settings',(req,res)=>{auth.current(req,['admin']);required(req.body,['settings']);const allowed=['site_name','tagline','comments_enabled'];const entries=Object.entries(req.body.settings);if(!entries.length||entries.some(([k])=>!allowed.includes(k)))throw new ApiError(422,'validation_error','Only allow-listed settings can be changed.');db.transaction(()=>{for(const [key,value] of entries)db.prepare('UPDATE settings SET value=?,version=version+1 WHERE key=?').run(JSON.stringify(value),key);})();res.json({items:db.prepare('SELECT * FROM settings ORDER BY key').all().map(x=>({...x,value:parse(x.value,x.value)}))});});
 app.get('/api/admin/integrations',(req,res)=>{auth.current(req,['admin']);res.json({items:db.prepare('SELECT * FROM integrations ORDER BY id').all().map(x=>({...x,enabled:Boolean(x.enabled),config:parse(x.config,{})}))});});
 app.patch('/api/admin/integrations/:id',(req,res)=>{auth.current(req,['admin']);const row=repo.integration(Number(req.params.id));version(req.body,row);if(req.body.config!==undefined&&(typeof req.body.config!=='object'||Array.isArray(req.body.config)))throw new ApiError(422,'validation_error','Integration config must be an object.');db.prepare('UPDATE integrations SET enabled=?,config=?,version=version+1 WHERE id=?').run(req.body.enabled===undefined?row.enabled:Number(Boolean(req.body.enabled)),JSON.stringify(req.body.config??parse(row.config,{})),row.id);const updated=repo.integration(row.id);res.json({...updated,enabled:Boolean(updated.enabled),config:parse(updated.config,{})});});

 app.post('/api/content-imports',(req,res)=>{const user=auth.current(req,['editor','admin']);required(req.body,['items','idempotency_key']);const items=jsonArray(req.body.items,'items');if(!items.length||items.length>50)throw new ApiError(422,'validation_error','Import must contain 1 to 50 items.');for(const item of items)if(!item||!['post','page'].includes(item.type)||!item.title||!/^[-a-z0-9]{3,80}$/.test(item.slug))throw new ApiError(422,'validation_error','Import item is invalid.');try{const result=db.transaction(()=>{const job=db.prepare("INSERT INTO import_jobs(actor_id,item_count,status,created_at,idempotency_key) VALUES(?,?,'completed',?,?)").run(user.id,items.length,now(),req.body.idempotency_key);const stmt=db.prepare("INSERT INTO content(author_id,type,title,slug,excerpt,category,tags,body,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,'draft',?,?)");for(const item of items){const t=now();stmt.run(user.id,item.type,item.title,item.slug,String(item.excerpt??''),String(item.category??''),JSON.stringify(item.tags??[]),JSON.stringify(item.body??[]),t,t);}return repo.content(db.prepare('SELECT max(id) id FROM content').get().id)&&db.prepare('SELECT * FROM import_jobs WHERE id=?').get(job.lastInsertRowid);})();res.status(201).json(result);}catch(e){if(e.code==='SQLITE_CONSTRAINT_UNIQUE')throw new ApiError(409,'duplicate_import','Import key or slug already exists.');throw e;}});
 app.get('/api/content-exports',(req,res)=>{auth.current(req,['editor','admin']);if(req.query.format!=='json')throw new ApiError(422,'validation_error','Only JSON export is supported.');let rows=db.prepare('SELECT * FROM content ORDER BY id').all();if(req.query.type){if(!['post','page'].includes(req.query.type))throw new ApiError(422,'validation_error','Invalid content type.');rows=rows.filter(x=>x.type===req.query.type);}res.json({format:'json',items:rows.map(contentJson)});});

 app.get('/api/navigation',(req,res)=>{auth.current(req,['editor','admin']);const row=db.prepare('SELECT * FROM navigation WHERE id=1').get();res.json({...row,items:parse(row.items,[])});});
 app.put('/api/navigation',(req,res)=>{auth.current(req,['editor','admin']);const row=db.prepare('SELECT * FROM navigation WHERE id=1').get();version(req.body,row);const items=jsonArray(req.body.items,'items');if(items.length>20||items.some(x=>!x||typeof x.label!=='string'||!pathValue(x.path,'navigation path')))throw new ApiError(422,'validation_error','Invalid navigation items.');db.prepare('UPDATE navigation SET items=?,version=version+1 WHERE id=1').run(JSON.stringify(items));const updated=db.prepare('SELECT * FROM navigation WHERE id=1').get();res.json({...updated,items:parse(updated.items,[])});});
 app.get('/api/admin/redirects',(req,res)=>{auth.current(req,['editor','admin']);res.json({items:db.prepare('SELECT * FROM redirects ORDER BY id').all()});});
 app.post('/api/admin/redirects',(req,res)=>{auth.current(req,['editor','admin']);required(req.body,['source_path','target_path','status_code']);const source=pathValue(req.body.source_path,'source path'),target=pathValue(req.body.target_path,'target path');if(source===target||![301,302].includes(req.body.status_code))throw new ApiError(422,'validation_error','Invalid redirect.');try{const r=db.prepare('INSERT INTO redirects(source_path,target_path,status_code,created_at) VALUES(?,?,?,?)').run(source,target,req.body.status_code,now());res.status(201).json(repo.redirect(r.lastInsertRowid));}catch(e){if(e.code==='SQLITE_CONSTRAINT_UNIQUE')throw new ApiError(409,'redirect_exists','Redirect source already exists.');throw e;}});
 app.delete('/api/admin/redirects/:id',(req,res)=>{auth.current(req,['editor','admin']);const row=repo.redirect(Number(req.params.id));db.prepare('DELETE FROM redirects WHERE id=?').run(row.id);res.status(204).end();});

 app.use('/api',(req,res,next)=>next(new ApiError(404,'not_found','API route was not found.')));
 app.use((err,req,res,next)=>{if(res.headersSent)return next(err);if(err instanceof SyntaxError&&err.status===400)return res.status(422).json({error:{code:'invalid_json',message:'Request JSON is invalid.',fields:{}}});const status=err.status||500;if(status===500)console.error('Unexpected server error');res.status(status).json({error:{code:err.code||'internal_error',message:status===500?'An unexpected error occurred.':err.message,fields:err.fields||{}}});});return app;}
