<?php
declare(strict_types=1);namespace App;use PDO;use Slim\App;final class Routes{public static function register(App$app,PDO$db,Auth$auth,MailRepository$repo,array$c):void{$ok=fn($r,$d,$s=200)=>Http::json($r,$d,$s);$fetch=function(string$sql,array$args)use($db):array{$s=$db->prepare($sql);$s->execute($args);$r=$s->fetch();if(!$r)throw new ApiException(404,'not_found','Resource not found.');return$r;};$duplicate=function(callable$f):void{try{$f();}catch(\PDOException$e){if($e->getCode()==='23000')throw new ApiException(409,'conflict','Resource already exists.');throw$e;}};$version=function(array$d,array$r):void{if(isset($d['version'])&&(int)$d['version']!==(int)$r['version'])throw new ApiException(409,'stale_version','Resource version is stale.');};$email=function(string$v,string$field='email'):string{$v=strtolower(trim($v));if(!filter_var($v,FILTER_VALIDATE_EMAIL))throw new ApiException(422,'validation_error','Invalid email address.',[$field=>'valid email required']);return$v;};$folder=function(int$mid,string$name)use($fetch):array{return$fetch('SELECT * FROM folders WHERE mailbox_id=? AND name=?',[$mid,$name]);};
// MAIL-01
$app->post('/api/auth/login',function($q,$r)use($auth,$ok){$d=Http::body($q);Http::required($d,['email','password']);[$u,$t]=$auth->login($d['email'],$d['password']);return$ok($r,['user'=>$u])->withHeader('Set-Cookie',$auth->cookie.'='.rawurlencode($t).'; Path=/; HttpOnly; SameSite=Lax');});
$app->post('/api/auth/logout',function($q,$r)use($auth,$ok){$auth->user($q);$auth->logout($q);return$ok($r,['logged_out'=>true])->withHeader('Set-Cookie',$auth->cookie.'=; Path=/; HttpOnly; Max-Age=0; SameSite=Lax');});
$app->post('/api/auth/password-reset-requests',function($q,$r)use($db,$c,$ok){$d=Http::body($q);Http::required($d,['email']);$s=$db->prepare('SELECT id FROM users WHERE email=? AND status="active"');$s->execute([strtolower($d['email'])]);$u=$s->fetch();$token=null;if($u){$token='reset-'.bin2hex(random_bytes(5));$db->prepare('INSERT INTO reset_tokens(user_id,token_hash,expires_at) VALUES(?,?,?)')->execute([$u['id'],hash('sha256',$token),gmdate(DATE_ATOM,time()+$c['resetTtl'])]);}return$ok($r,['accepted'=>true,'reset_token'=>$c['appEnv']==='test'?$token:null],201);});
$app->post('/api/auth/password-resets',function($q,$r)use($db,$ok){$d=Http::body($q);Http::required($d,['token','password']);if(strlen($d['password'])<10)throw new ApiException(422,'validation_error','Invalid password.',['password'=>'minimum 10 characters']);$s=$db->prepare('SELECT * FROM reset_tokens WHERE token_hash=?');$s->execute([hash('sha256',$d['token'])]);$t=$s->fetch();if(!$t||$t['used_at']!==null||$t['expires_at']<=gmdate(DATE_ATOM))throw new ApiException(409,'invalid_reset_token','Reset token is invalid or expired.');$db->beginTransaction();$db->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($d['password'],PASSWORD_DEFAULT),$t['user_id']]);$db->prepare('UPDATE reset_tokens SET used_at=? WHERE id=?')->execute([gmdate(DATE_ATOM),$t['id']]);$db->prepare('DELETE FROM sessions WHERE user_id=?')->execute([$t['user_id']]);$db->commit();return$ok($r,['password_reset'=>true]);});
// MAIL-02
$app->get('/api/mail/folders',function($q,$r)use($auth,$repo,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->mailbox($u);return$ok($r,['items'=>$repo->rows('SELECT f.id,f.name,COUNT(m.id) message_count,SUM(CASE WHEN m.is_read=0 THEN 1 ELSE 0 END) unread_count FROM folders f LEFT JOIN messages m ON m.folder_id=f.id WHERE f.mailbox_id=? GROUP BY f.id ORDER BY f.id',[$m['id']])]);});
$app->get('/api/mail/messages',function($q,$r)use($auth,$repo,$folder,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->mailbox($u);$p=$q->getQueryParams();[$l,$o]=Http::page($q);$f=$folder((int)$m['id'],(string)($p['folder']??'inbox'));$term='%'.trim((string)($p['q']??'')).'%';return$ok($r,['items'=>$repo->rows('SELECT id,sender,recipients,subject,status,is_read,is_flagged,version,created_at FROM messages WHERE mailbox_id=? AND folder_id=? AND (subject LIKE ? OR sender LIKE ?) ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?',[$m['id'],$f['id'],$term,$term,$l,$o]),'page'=>(int)($p['page']??1)]);});
// MAIL-03
$app->post('/api/mail/drafts',function($q,$r)use($auth,$repo,$db,$folder,$duplicate,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->mailbox($u);$d=Http::body($q);$rec=$d['recipients']??[];if(!is_array($rec))throw new ApiException(422,'validation_error','Invalid recipients.',['recipients'=>'array required']);$f=$folder((int)$m['id'],'drafts');$key=isset($d['idempotency_key'])?(string)$d['idempotency_key']:null;$duplicate(fn()=>$db->prepare('INSERT INTO messages(mailbox_id,folder_id,sender,recipients,subject,body,status,is_read,is_flagged,created_at,idempotency_key) VALUES(?,?,?,?,?, ?,"draft",0,0,?,?)')->execute([$m['id'],$f['id'],$m['address'],json_encode($rec,JSON_THROW_ON_ERROR),(string)($d['subject']??''),(string)($d['body']??''),gmdate(DATE_ATOM),$key]));return$ok($r,$repo->message((int)$db->lastInsertId(),$u),201);});
$app->patch('/api/mail/drafts/{id}',function($q,$r,$a)use($auth,$repo,$db,$version,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->message((int)$a['id'],$u);if($m['status']!=='draft')throw new ApiException(409,'invalid_state','Only drafts can be changed.');$d=Http::body($q);$version($d,$m);$rec=$d['recipients']??json_decode($m['recipients'],true);if(!is_array($rec))throw new ApiException(422,'validation_error','Invalid recipients.',['recipients'=>'array required']);$db->prepare('UPDATE messages SET recipients=?,subject=?,body=?,version=version+1 WHERE id=?')->execute([json_encode($rec,JSON_THROW_ON_ERROR),(string)($d['subject']??$m['subject']),(string)($d['body']??$m['body']),$m['id']]);return$ok($r,$repo->message((int)$m['id'],$u));});
$app->post('/api/mail/drafts/{id}/send',function($q,$r,$a)use($auth,$repo,$db,$folder,$email,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->message((int)$a['id'],$u);if($m['status']!=='draft')throw new ApiException(409,'invalid_state','Message is not a draft.');$rec=json_decode($m['recipients'],true);if(!$rec)throw new ApiException(422,'validation_error','At least one recipient is required.',['recipients'=>'required']);foreach($rec as$x)$email((string)$x,'recipients');$box=$repo->mailbox($u);$sent=$folder((int)$box['id'],'sent');$db->beginTransaction();$db->prepare('UPDATE messages SET folder_id=?,status="sent",version=version+1 WHERE id=?')->execute([$sent['id'],$m['id']]);$db->prepare('INSERT INTO deliveries(message_id,status,created_at) VALUES(?,"delivered",?)')->execute([$m['id'],gmdate(DATE_ATOM)]);$db->commit();return$ok($r,$fetch=self::one($db,'SELECT * FROM deliveries WHERE message_id=?',[$m['id']]));});
$app->delete('/api/mail/drafts/{id}',function($q,$r,$a)use($auth,$repo,$db){$u=$auth->user($q,['mailbox_user']);$m=$repo->message((int)$a['id'],$u);if($m['status']!=='draft')throw new ApiException(409,'invalid_state','Message is not a draft.');$db->prepare('DELETE FROM messages WHERE id=?')->execute([$m['id']]);return$r->withStatus(204);});
// MAIL-04
$app->get('/api/mail/messages/{id}',function($q,$r,$a)use($auth,$repo,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->message((int)$a['id'],$u);return$ok($r,['message'=>$m,'attachments'=>$repo->rows('SELECT id,filename,mime,size FROM attachments WHERE message_id=? ORDER BY id',[$m['id']])]);});
$app->patch('/api/mail/messages/{id}',function($q,$r,$a)use($auth,$repo,$db,$version,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->message((int)$a['id'],$u);$d=Http::body($q);$version($d,$m);if(!array_key_exists('is_read',$d)&&!array_key_exists('is_flagged',$d))throw new ApiException(422,'validation_error','No supported change.',['is_read'=>'or is_flagged required']);$db->prepare('UPDATE messages SET is_read=?,is_flagged=?,version=version+1 WHERE id=?')->execute([(int)(bool)($d['is_read']??$m['is_read']),(int)(bool)($d['is_flagged']??$m['is_flagged']),$m['id']]);return$ok($r,$repo->message((int)$m['id'],$u));});
$app->post('/api/mail/messages/{id}/move',function($q,$r,$a)use($auth,$repo,$db,$folder,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->message((int)$a['id'],$u);$d=Http::body($q);Http::required($d,['folder']);$box=$repo->mailbox($u);$f=$folder((int)$box['id'],$d['folder']);if((int)$f['id']===(int)$m['folder_id'])throw new ApiException(409,'invalid_state','Message is already in that folder.');$db->prepare('UPDATE messages SET folder_id=?,version=version+1 WHERE id=?')->execute([$f['id'],$m['id']]);return$ok($r,$repo->message((int)$m['id'],$u));});
$app->delete('/api/mail/messages/{id}',function($q,$r,$a)use($auth,$repo,$db,$folder){$u=$auth->user($q,['mailbox_user']);$m=$repo->message((int)$a['id'],$u);$box=$repo->mailbox($u);$trash=$folder((int)$box['id'],'trash');if((int)$m['folder_id']===(int)$trash['id']){$db->prepare('DELETE FROM messages WHERE id=?')->execute([$m['id']]);}else{$db->prepare('UPDATE messages SET folder_id=?,status="trashed",version=version+1 WHERE id=?')->execute([$trash['id'],$m['id']]);}return$r->withStatus(204);});
// MAIL-05
$app->post('/api/mail/drafts/{id}/attachments',function($q,$r,$a)use($auth,$repo,$db,$duplicate,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->message((int)$a['id'],$u);if($m['status']!=='draft')throw new ApiException(409,'invalid_state','Attachments require a draft.');$d=Http::body($q);Http::required($d,['filename','mime','content_base64']);$bytes=base64_decode($d['content_base64'],true);if($bytes===false||strlen($bytes)>1048576)throw new ApiException(422,'validation_error','Invalid attachment.',['content_base64'=>'valid Base64, maximum 1 MiB']);$duplicate(fn()=>$db->prepare('INSERT INTO attachments(message_id,filename,mime,content,size) VALUES(?,?,?,?,?)')->execute([$m['id'],basename($d['filename']),$d['mime'],$d['content_base64'],strlen($bytes)]));return$ok($r,self::one($db,'SELECT id,message_id,filename,mime,size FROM attachments WHERE id=?',[(int)$db->lastInsertId()]),201);});
$app->get('/api/mail/attachments/{id}/content',function($q,$r,$a)use($auth,$repo,$db,$ok){$u=$auth->user($q,['mailbox_user']);$box=$repo->mailbox($u);$x=self::one($db,'SELECT a.* FROM attachments a JOIN messages m ON m.id=a.message_id WHERE a.id=? AND m.mailbox_id=?',[(int)$a['id'],$box['id']]);return$ok($r,['filename'=>$x['filename'],'mime'=>$x['mime'],'content_base64'=>$x['content']]);});
$app->delete('/api/mail/drafts/{id}/attachments/{aid}',function($q,$r,$a)use($auth,$repo,$db){$u=$auth->user($q,['mailbox_user']);$m=$repo->message((int)$a['id'],$u);if($m['status']!=='draft')throw new ApiException(409,'invalid_state','Attachments require a draft.');$s=$db->prepare('DELETE FROM attachments WHERE id=? AND message_id=?');$s->execute([(int)$a['aid'],$m['id']]);if($s->rowCount()===0)throw new ApiException(404,'not_found','Resource not found.');return$r->withStatus(204);});
// MAIL-06
$app->get('/api/contacts',function($q,$r)use($auth,$repo,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->mailbox($u);$term='%'.trim((string)($q->getQueryParams()['q']??'')).'%';return$ok($r,['items'=>$repo->rows('SELECT * FROM contacts WHERE mailbox_id=? AND (name LIKE ? OR email LIKE ?) ORDER BY name,id',[$m['id'],$term,$term])]);});
$app->post('/api/contacts',function($q,$r)use($auth,$repo,$db,$duplicate,$email,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->mailbox($u);$d=Http::body($q);Http::required($d,['name','email']);$e=$email($d['email']);$duplicate(fn()=>$db->prepare('INSERT INTO contacts(mailbox_id,name,email) VALUES(?,?,?)')->execute([$m['id'],$d['name'],$e]));return$ok($r,self::one($db,'SELECT * FROM contacts WHERE id=?',[(int)$db->lastInsertId()]),201);});
$app->patch('/api/contacts/{id}',function($q,$r,$a)use($auth,$repo,$db,$version,$email,$ok){$u=$auth->user($q,['mailbox_user']);$x=$repo->owned('contacts',(int)$a['id'],$u);$d=Http::body($q);$version($d,$x);$e=$email((string)($d['email']??$x['email']));try{$db->prepare('UPDATE contacts SET name=?,email=?,version=version+1 WHERE id=?')->execute([(string)($d['name']??$x['name']),$e,$x['id']]);}catch(\PDOException){throw new ApiException(409,'conflict','Contact already exists.');}return$ok($r,$repo->owned('contacts',(int)$x['id'],$u));});
$app->delete('/api/contacts/{id}',function($q,$r,$a)use($auth,$repo,$db){$u=$auth->user($q,['mailbox_user']);$x=$repo->owned('contacts',(int)$a['id'],$u);$db->prepare('DELETE FROM contacts WHERE id=?')->execute([$x['id']]);return$r->withStatus(204);});
// MAIL-07
$app->get('/api/mail/rules',function($q,$r)use($auth,$repo,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->mailbox($u);return$ok($r,['items'=>$repo->rows('SELECT * FROM rules WHERE mailbox_id=? ORDER BY position',[$m['id']])]);});
$app->post('/api/mail/rules',function($q,$r)use($auth,$repo,$db,$duplicate,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->mailbox($u);$d=Http::body($q);Http::required($d,['name','condition_field','condition_value','action_type','action_value']);if(!in_array($d['condition_field'],['sender','recipient','subject'],true)||!in_array($d['action_type'],['move','flag','discard'],true))throw new ApiException(422,'validation_error','Unsupported rule schema.',['condition_field'=>'sender, recipient, or subject','action_type'=>'move, flag, or discard']);$pos=(int)self::scalar($db,'SELECT COALESCE(MAX(position),0)+1 FROM rules WHERE mailbox_id=?',[$m['id']]);$duplicate(fn()=>$db->prepare('INSERT INTO rules(mailbox_id,name,condition_field,condition_value,action_type,action_value,position,enabled) VALUES(?,?,?,?,?,?,?,1)')->execute([$m['id'],$d['name'],$d['condition_field'],$d['condition_value'],$d['action_type'],$d['action_value'],$pos]));return$ok($r,self::one($db,'SELECT * FROM rules WHERE id=?',[(int)$db->lastInsertId()]),201);});
$app->patch('/api/mail/rules/{id}',function($q,$r,$a)use($auth,$repo,$db,$version,$ok){$u=$auth->user($q,['mailbox_user']);$x=$repo->owned('rules',(int)$a['id'],$u);$d=Http::body($q);$version($d,$x);if(!array_key_exists('enabled',$d))throw new ApiException(422,'validation_error','No supported change.',['enabled'=>'required']);$db->prepare('UPDATE rules SET enabled=?,version=version+1 WHERE id=?')->execute([(int)(bool)$d['enabled'],$x['id']]);return$ok($r,$repo->owned('rules',(int)$x['id'],$u));});
$app->delete('/api/mail/rules/{id}',function($q,$r,$a)use($auth,$repo,$db){$u=$auth->user($q,['mailbox_user']);$x=$repo->owned('rules',(int)$a['id'],$u);$db->prepare('DELETE FROM rules WHERE id=?')->execute([$x['id']]);return$r->withStatus(204);});
$app->post('/api/mail/rules/reorder',function($q,$r)use($auth,$repo,$db,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->mailbox($u);$d=Http::body($q);$ids=$d['rule_ids']??null;if(!is_array($ids)||count($ids)!==(int)self::scalar($db,'SELECT COUNT(*) FROM rules WHERE mailbox_id=?',[$m['id']]))throw new ApiException(422,'validation_error','Complete rule order required.',['rule_ids'=>'must contain every rule']);$owned=$repo->rows('SELECT id FROM rules WHERE mailbox_id=? ORDER BY id',[$m['id']]);$expected=array_map(fn($x)=>(int)$x['id'],$owned);$actual=array_map('intval',$ids);sort($expected);$check=$actual;sort($check);if($expected!==$check)throw new ApiException(404,'not_found','One or more rules were not found.');$db->beginTransaction();$db->prepare('UPDATE rules SET position=position+1000 WHERE mailbox_id=?')->execute([$m['id']]);$s=$db->prepare('UPDATE rules SET position=? WHERE id=? AND mailbox_id=?');foreach($actual as$i=>$id)$s->execute([$i+1,$id,$m['id']]);$db->commit();return$ok($r,['rule_ids'=>$actual]);});
// MAIL-08
$app->get('/api/admin/domains',function($q,$r)use($auth,$repo,$ok){$u=$auth->user($q,['domain_admin']);return$ok($r,['items'=>$repo->adminDomains($u)]);});
$app->post('/api/admin/domains',function($q,$r)use($auth,$repo,$db,$duplicate,$ok){$u=$auth->user($q,['domain_admin']);$d=Http::body($q);Http::required($d,['name']);$name=strtolower($d['name']);if(!filter_var($name,FILTER_VALIDATE_DOMAIN,FILTER_FLAG_HOSTNAME))throw new ApiException(422,'validation_error','Invalid domain.',['name'=>'hostname required']);$db->beginTransaction();try{$duplicate(fn()=>$db->prepare('INSERT INTO domains(name,status) VALUES(?,"active")')->execute([$name]));$id=(int)$db->lastInsertId();$db->prepare('INSERT INTO domain_admins VALUES(?,?)')->execute([$u['id'],$id]);$repo->audit((int)$u['id'],$id,'domain.created',$name);$db->commit();}catch(\Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}return$ok($r,$repo->adminDomain($id,$u),201);});
$app->post('/api/admin/domains/{id}/aliases',function($q,$r,$a)use($auth,$repo,$db,$duplicate,$email,$ok){$u=$auth->user($q,['domain_admin']);$dmain=$repo->adminDomain((int)$a['id'],$u);$d=Http::body($q);Http::required($d,['source','destination']);$source=$email($d['source'],'source');$dest=$email($d['destination'],'destination');if(!str_ends_with($source,'@'.$dmain['name']))throw new ApiException(422,'validation_error','Alias must belong to domain.',['source'=>'wrong domain']);$duplicate(fn()=>$db->prepare('INSERT INTO aliases(domain_id,source,destination) VALUES(?,?,?)')->execute([$dmain['id'],$source,$dest]));return$ok($r,self::one($db,'SELECT * FROM aliases WHERE id=?',[(int)$db->lastInsertId()]),201);});
$app->patch('/api/admin/mailboxes/{id}/quota',function($q,$r,$a)use($auth,$repo,$db,$version,$ok){$u=$auth->user($q,['domain_admin']);$x=self::one($db,'SELECT * FROM mailboxes WHERE id=?',[(int)$a['id']]);$repo->adminDomain((int)$x['domain_id'],$u);$d=Http::body($q);$version($d,$x);$quota=(int)($d['quota_mb']??0);if($quota<(int)$x['used_mb']||$quota>102400)throw new ApiException(422,'validation_error','Invalid quota.',['quota_mb'=>'must cover usage and be <=102400']);$db->prepare('UPDATE mailboxes SET quota_mb=?,version=version+1 WHERE id=?')->execute([$quota,$x['id']]);return$ok($r,self::one($db,'SELECT * FROM mailboxes WHERE id=?',[$x['id']]));});
// MAIL-09
$app->get('/api/admin/quarantine',function($q,$r)use($auth,$repo,$ok){$u=$auth->user($q,['domain_admin','platform_admin']);$p=$q->getQueryParams();[$l,$o]=Http::page($q);$domains=$repo->adminDomains($u);$ids=array_map(fn($x)=>(int)$x['id'],$domains);if(isset($p['domainId'])){$repo->adminDomain((int)$p['domainId'],$u);$ids=[(int)$p['domainId']];}$reason=(string)($p['reason']??'');if($reason!==''&&!in_array($reason,['spam','malware','policy'],true))throw new ApiException(422,'validation_error','Invalid reason.',['reason'=>'spam, malware, or policy']);$marks=implode(',',array_fill(0,count($ids),'?'));$args=$ids;if($reason!=='')$args[]=$reason;$args[]=$l;$args[]=$o;return$ok($r,['items'=>$repo->rows('SELECT * FROM quarantine_items WHERE domain_id IN('.$marks.') AND status="quarantined"'.($reason!==''?' AND reason=?':'').' ORDER BY id DESC LIMIT ? OFFSET ?',$args)]);});
$app->post('/api/admin/quarantine/{id}/release',function($q,$r,$a)use($auth,$repo,$db,$ok){$u=$auth->user($q,['domain_admin','platform_admin']);$x=self::one($db,'SELECT * FROM quarantine_items WHERE id=?',[(int)$a['id']]);$repo->adminDomain((int)$x['domain_id'],$u);if($x['status']!=='quarantined')throw new ApiException(409,'invalid_state','Item is not quarantined.');$db->prepare('UPDATE quarantine_items SET status="released" WHERE id=?')->execute([$x['id']]);$repo->audit((int)$u['id'],(int)$x['domain_id'],'quarantine.released','Item '.$x['id']);return$ok($r,self::one($db,'SELECT * FROM quarantine_items WHERE id=?',[$x['id']]));});
$app->delete('/api/admin/quarantine/{id}',function($q,$r,$a)use($auth,$repo,$db){$u=$auth->user($q,['domain_admin','platform_admin']);$x=self::one($db,'SELECT * FROM quarantine_items WHERE id=?',[(int)$a['id']]);$repo->adminDomain((int)$x['domain_id'],$u);if($x['status']!=='quarantined')throw new ApiException(409,'invalid_state','Item is not quarantined.');$db->prepare('DELETE FROM quarantine_items WHERE id=?')->execute([$x['id']]);return$r->withStatus(204);});
// MAIL-10
$app->get('/api/admin/audit-events',function($q,$r)use($auth,$repo,$ok){$u=$auth->user($q,['domain_admin','platform_admin']);$p=$q->getQueryParams();$ids=array_map(fn($x)=>(int)$x['id'],$repo->adminDomains($u));if(isset($p['domainId'])){$repo->adminDomain((int)$p['domainId'],$u);$ids=[(int)$p['domainId']];}$from=(string)($p['from']??'0000-01-01T00:00:00Z');$to=(string)($p['to']??'9999-12-31T23:59:59Z');if(strtotime($from)===false||strtotime($to)===false||$from>$to)throw new ApiException(422,'validation_error','Invalid date range.',['from'=>'must precede to']);$marks=implode(',',array_fill(0,count($ids),'?'));$args=$ids;$sql='SELECT * FROM audit_events WHERE (domain_id IN('.$marks.')'.($u['role']==='platform_admin'?' OR domain_id IS NULL':'').') AND created_at>=? AND created_at<=?';$args[]=$from;$args[]=$to;if(isset($p['actorId'])){$sql.=' AND actor_id=?';$args[]=(int)$p['actorId'];}$sql.=' ORDER BY id DESC';return$ok($r,['items'=>$repo->rows($sql,$args)]);});
// MAIL-11
$app->post('/api/contacts/imports',function($q,$r)use($auth,$repo,$db,$email,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->mailbox($u);$d=Http::body($q);Http::required($d,['csv']);$lines=preg_split('/\r?\n/',trim($d['csv']))?:[];$count=0;$db->beginTransaction();try{foreach($lines as$i=>$line){if($i===0&&strtolower(trim($line))==='name,email')continue;$cols=str_getcsv($line);if(count($cols)!==2||trim($cols[0])==='')throw new ApiException(422,'validation_error','Invalid CSV row.',['csv'=>'row '.($i+1)]);$e=$email($cols[1],'csv');try{$db->prepare('INSERT INTO contacts(mailbox_id,name,email) VALUES(?,?,?)')->execute([$m['id'],trim($cols[0]),$e]);$count++;}catch(\PDOException){throw new ApiException(409,'conflict','Imported contact already exists.');}}$db->prepare('INSERT INTO import_jobs(mailbox_id,imported,status,created_at) VALUES(?,?,"completed",?)')->execute([$m['id'],$count,gmdate(DATE_ATOM)]);$id=(int)$db->lastInsertId();$db->commit();}catch(\Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}return$ok($r,self::one($db,'SELECT * FROM import_jobs WHERE id=?',[$id]),201);});
$app->get('/api/contacts.csv',function($q,$r)use($auth,$repo){$u=$auth->user($q,['mailbox_user']);$m=$repo->mailbox($u);$out="name,email\n";foreach($repo->rows('SELECT name,email FROM contacts WHERE mailbox_id=? ORDER BY name',[$m['id']])as$x)$out.=self::csvRow([$x['name'],$x['email']]);return Http::csv($r,$out,'contacts.csv');});
$app->get('/api/admin/domains/{id}/mailboxes.csv',function($q,$r,$a)use($auth,$repo){$u=$auth->user($q,['domain_admin']);$d=$repo->adminDomain((int)$a['id'],$u);$out="address,quota_mb,used_mb,status\n";foreach($repo->rows('SELECT address,quota_mb,used_mb,status FROM mailboxes WHERE domain_id=? ORDER BY address',[$d['id']])as$x)$out.=self::csvRow([$x['address'],$x['quota_mb'],$x['used_mb'],$x['status']]);return Http::csv($r,$out,'mailboxes-'.$d['name'].'.csv');});
// MAIL-12
$app->get('/api/mail/settings',function($q,$r)use($auth,$repo,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->mailbox($u);return$ok($r,self::one($repo->db,'SELECT * FROM settings WHERE mailbox_id=?',[$m['id']]));});
$app->patch('/api/mail/settings',function($q,$r)use($auth,$repo,$db,$version,$email,$ok){$u=$auth->user($q,['mailbox_user']);$m=$repo->mailbox($u);$x=self::one($db,'SELECT * FROM settings WHERE mailbox_id=?',[$m['id']]);$d=Http::body($q);$version($d,$x);$density=(string)($d['display_density']??$x['display_density']);if(!in_array($density,['compact','comfortable'],true))throw new ApiException(422,'validation_error','Invalid display density.',['display_density'=>'compact or comfortable']);$fwd=(bool)($d['forwarding_enabled']??$x['forwarding_enabled']);$address=(string)($d['forwarding_address']??$x['forwarding_address']);if($fwd)$address=$email($address,'forwarding_address');$vac=(bool)($d['vacation_enabled']??$x['vacation_enabled']);$msg=(string)($d['vacation_message']??$x['vacation_message']);if($vac&&trim($msg)==='')throw new ApiException(422,'validation_error','Vacation message required.',['vacation_message'=>'required when enabled']);$db->prepare('UPDATE settings SET signature=?,vacation_enabled=?,vacation_message=?,forwarding_enabled=?,forwarding_address=?,display_density=?,version=version+1 WHERE mailbox_id=?')->execute([(string)($d['signature']??$x['signature']),(int)$vac,$msg,(int)$fwd,$address,$density,$m['id']]);return$ok($r,self::one($db,'SELECT * FROM settings WHERE mailbox_id=?',[$m['id']]));});
}private static function one(PDO$db,string$sql,array$args):array{$s=$db->prepare($sql);$s->execute($args);$r=$s->fetch();if(!$r)throw new ApiException(404,'not_found','Resource not found.');return$r;}private static function scalar(PDO$db,string$sql,array$args):mixed{$s=$db->prepare($sql);$s->execute($args);return$s->fetchColumn();}private static function csvRow(array$v):string{$h=fopen('php://temp','r+');fputcsv($h,$v,',','"','\\');rewind($h);$line=(string)stream_get_contents($h);fclose($h);return$line;}}
