import express from 'express';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';import {ApiError,requireFields} from './errors.js';import {Auth} from './auth.js';import {Repository} from './repository.js';import {hashPassword,randomToken,tokenHash} from './security.js';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const now=()=>new Date().toISOString();
function parseCookies(req,_res,next){req.cookies=Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return[decodeURIComponent(x.slice(0,i).trim()),decodeURIComponent(x.slice(i+1))]}));next();}
function stay(checkIn,checkOut,{future=true}={}){if(!/^\d{4}-\d{2}-\d{2}$/.test(checkIn||'')||!/^\d{4}-\d{2}-\d{2}$/.test(checkOut||''))throw new ApiError(422,'validation_error','Dates must use YYYY-MM-DD.');const start=Date.parse(checkIn+'T00:00:00Z'),end=Date.parse(checkOut+'T00:00:00Z'),nights=(end-start)/86400000;if(!Number.isInteger(nights)||nights<1||nights>30||(future&&start<Date.now()-86400000))throw new ApiError(422,'validation_error','Stay must be 1 to 30 future nights.');return nights;}
function occupancy(data,type){const adults=Number(data.adults),children=Number(data.children||0);if(!Number.isInteger(adults)||!Number.isInteger(children)||adults<1||children<0||adults>type.capacity_adults||children>type.capacity_children)throw new ApiError(422,'validation_error','Occupancy exceeds room capacity.');return[adults,children];}
function version(data,item){if(data.version!==undefined&&Number(data.version)!==item.version)throw new ApiError(409,'stale_version','Resource version is stale.');}
function duplicate(work){try{return work();}catch(error){if(error.code?.startsWith('SQLITE_CONSTRAINT'))throw new ApiError(409,'conflict','Resource already exists.');throw error;}}
function range(query){const from=query.from,to=query.to;if(!/^\d{4}-\d{2}-\d{2}$/.test(from||'')||!/^\d{4}-\d{2}-\d{2}$/.test(to||''))throw new ApiError(422,'validation_error','Dates must use YYYY-MM-DD.');const days=(Date.parse(to+'T00:00:00Z')-Date.parse(from+'T00:00:00Z'))/86400000;if(!Number.isInteger(days)||days<1||days>366)throw new ApiError(422,'validation_error','Report range must be 1 to 366 days.');return[from,to];}
function reviewFields(data){if(!Number.isInteger(data.rating)||data.rating<1||data.rating>5||typeof data.title!=='string'||data.title.length<2||data.title.length>80||typeof data.body!=='string'||data.body.length<3||data.body.length>1000)throw new ApiError(422,'validation_error','Invalid review fields.');}
export function createApp(db,config={}){
 const app=express(),auth=new Auth(db,{cookie:config.cookie||'hotel_session',ttl:config.sessionTtl||86400}),repo=new Repository(db);app.locals.services={db,auth,repo};app.use(express.json({limit:'64kb'}));app.use(parseCookies);app.use(express.static(path.join(__dirname,'../public')));
 // HOTEL-01
 app.post('/api/auth/register',(req,res)=>{requireFields(req.body,['email','password','name']);const email=String(req.body.email).toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||typeof req.body.password!=='string'||req.body.password.length<10||typeof req.body.name!=='string'||req.body.name.length<2)throw new ApiError(422,'validation_error','Invalid account fields.');const id=duplicate(()=>db.prepare("INSERT INTO users(email,password_hash,name,role,status) VALUES(?,?,?,'guest','active')").run(email,hashPassword(req.body.password),req.body.name).lastInsertRowid);res.status(201).json(auth.public(repo.need('users',id)));});
 app.post('/api/auth/login',(req,res)=>{requireFields(req.body,['email','password']);const[user,token]=auth.login(req.body.email,req.body.password);res.setHeader('Set-Cookie',`${auth.cookie}=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax`);res.json({user});});
 app.post('/api/auth/logout',(req,res)=>{auth.current(req);auth.logout(req);res.setHeader('Set-Cookie',`${auth.cookie}=; Path=/; HttpOnly; Max-Age=0; SameSite=Lax`);res.json({logged_out:true});});
 app.post('/api/auth/password-reset-requests',(req,res)=>{requireFields(req.body,['email']);const user=db.prepare("SELECT id FROM users WHERE email=? AND status='active'").get(String(req.body.email).toLowerCase());let token=null;if(user){token='reset-'+randomToken();db.prepare('INSERT INTO reset_tokens(user_id,token_hash,expires_at) VALUES(?,?,?)').run(user.id,tokenHash(token),new Date(Date.now()+(config.resetTtl||1800)*1000).toISOString());}res.status(201).json({accepted:true,reset_token:config.appEnv==='test'?token:null});});
 app.post('/api/auth/password-resets',(req,res)=>{requireFields(req.body,['token','password']);if(typeof req.body.password!=='string'||req.body.password.length<10)throw new ApiError(422,'validation_error','Password must have at least 10 characters.');const item=db.prepare('SELECT * FROM reset_tokens WHERE token_hash=?').get(tokenHash(String(req.body.token)));if(!item||item.used_at||item.expires_at<=now())throw new ApiError(409,'invalid_reset_token','Reset token is invalid or expired.');db.transaction(()=>{db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(hashPassword(req.body.password),item.user_id);db.prepare('UPDATE reset_tokens SET used_at=? WHERE id=?').run(now(),item.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(item.user_id);})();res.json({password_reset:true});});
 // HOTEL-02/03
 app.get('/api/room-types/availability',(req,res)=>{const nights=stay(req.query.checkIn,req.query.checkOut),amenities=String(req.query.amenities||'').split(',').filter(Boolean),adults=Number(req.query.adults),children=Number(req.query.children||0);if(!Number.isInteger(adults)||!Number.isInteger(children)||adults<1||children<0)throw new ApiError(422,'validation_error','Invalid occupancy.');const items=db.prepare("SELECT * FROM room_types WHERE status='active' AND capacity_adults>=? AND capacity_children>=? ORDER BY id").all(adults,children).filter(type=>amenities.every(a=>JSON.parse(type.amenities).includes(a))).map(type=>{const rate=repo.rate(type.id,req.query.checkIn,req.query.checkOut);return{...type,available_rooms:repo.availableCount(type.id,req.query.checkIn,req.query.checkOut),nights,total_cents:nights*rate.nightly_rate_cents};}).filter(x=>x.available_rooms>0);res.json({items});});
 app.get('/api/room-types/:id',(req,res)=>{const item=repo.roomType(Number(req.params.id));res.json({...item,amenities:JSON.parse(item.amenities)});});
 app.get('/api/room-types/:id/rates',(req,res)=>{const type=repo.roomType(Number(req.params.id)),nights=stay(req.query.checkIn,req.query.checkOut),rate=repo.rate(type.id,req.query.checkIn,req.query.checkOut);res.json({room_type_id:type.id,nights,rate_plan:rate,total_cents:nights*rate.nightly_rate_cents});});
 // HOTEL-04
 app.post('/api/booking-quotes',(req,res)=>{const user=auth.current(req,['guest','staff']);requireFields(req.body,['room_type_id','check_in','check_out','adults']);const type=repo.roomType(Number(req.body.room_type_id)),nights=stay(req.body.check_in,req.body.check_out),[adults,children]=occupancy(req.body,type);if(repo.availableCount(type.id,req.body.check_in,req.body.check_out)<1)throw new ApiError(409,'sold_out','No room is available.');const rate=repo.rate(type.id,req.body.check_in,req.body.check_out),total=nights*rate.nightly_rate_cents,expires=new Date(Date.now()+(config.quoteTtl||900)*1000).toISOString();const id=db.prepare('INSERT INTO booking_quotes(user_id,room_type_id,rate_plan_id,policy_id,check_in,check_out,adults,children,nightly_rate_cents,total_cents,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(user.id,type.id,rate.id,rate.policy_id,req.body.check_in,req.body.check_out,adults,children,rate.nightly_rate_cents,total,expires,now()).lastInsertRowid;res.status(201).json(repo.need('booking_quotes',id));});
 app.post('/api/bookings',(req,res)=>{const actor=auth.current(req,['guest','staff']);requireFields(req.body,['quote_id','guest_name','payment_method_id','idempotency_key']);const quote=repo.need('booking_quotes',Number(req.body.quote_id));if(quote.status!=='active'||quote.expires_at<=now())throw new ApiError(409,'invalid_state','Quote is no longer active.');if(quote.user_id!==actor.id)throw new ApiError(403,'forbidden','Quote belongs to another actor.');if(req.body.payment_method_id!=='pm_success')throw new ApiError(422,'payment_declined','Deterministic payment fixture declined.');if(repo.availableCount(quote.room_type_id,quote.check_in,quote.check_out)<1)throw new ApiError(409,'sold_out','No room is available.');const guestId=actor.role==='staff'?Number(req.body.guest_id):actor.id;if(actor.role==='staff'&&!db.prepare("SELECT id FROM users WHERE id=? AND role='guest' AND status='active'").get(guestId))throw new ApiError(422,'validation_error','Valid guest_id required for staff booking.');const policy=repo.need('cancellation_policies',quote.policy_id);let bookingId;duplicate(()=>db.transaction(()=>{const code='HTL-'+crypto.randomBytes(4).toString('hex').toUpperCase();bookingId=db.prepare("INSERT INTO bookings(confirmation_code,guest_id,created_by,room_type_id,check_in,check_out,adults,children,total_cents,policy_name,free_hours,fee_percent,status,created_at,idempotency_key) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'confirmed',?,?)").run(code,guestId,actor.id,quote.room_type_id,quote.check_in,quote.check_out,quote.adults,quote.children,quote.total_cents,policy.name,policy.free_hours,policy.fee_percent,now(),req.body.idempotency_key).lastInsertRowid;db.prepare("INSERT INTO payments(booking_id,amount_cents,kind,status,method_ref,idempotency_key,created_at) VALUES(?,?,'charge','succeeded',?,?,?)").run(bookingId,quote.total_cents,req.body.payment_method_id,'pay-'+req.body.idempotency_key,now());db.prepare("INSERT INTO invoices(booking_id,room_cents,total_cents,status) VALUES(?,?,?,'open')").run(bookingId,quote.total_cents,quote.total_cents);db.prepare("UPDATE booking_quotes SET status='consumed' WHERE id=?").run(quote.id);})());res.status(201).json(repo.publicBooking(repo.need('bookings',bookingId)));});
 // HOTEL-05
 app.get('/api/bookings',(req,res)=>{const user=auth.current(req,['guest','staff']);const page=Math.max(1,Number(req.query.page||1));if(!Number.isInteger(page))throw new ApiError(422,'validation_error','Invalid page.');const rows=user.role==='staff'?db.prepare('SELECT * FROM bookings ORDER BY id DESC LIMIT 20 OFFSET ?').all((page-1)*20):db.prepare('SELECT * FROM bookings WHERE guest_id=? ORDER BY id DESC LIMIT 20 OFFSET ?').all(user.id,(page-1)*20);res.json({items:rows.map(x=>repo.publicBooking(x)),page});});
 app.get('/api/bookings/:id',(req,res)=>{const user=auth.current(req,['guest','staff']);res.json(repo.publicBooking(repo.booking(Number(req.params.id),user)));});
 app.patch('/api/bookings/:id',(req,res)=>{const user=auth.current(req,['guest','staff']),item=repo.booking(Number(req.params.id),user);version(req.body,item);if(item.status!=='confirmed')throw new ApiError(409,'invalid_state','Only confirmed bookings may be modified.');const type=repo.roomType(item.room_type_id),checkIn=req.body.check_in||item.check_in,checkOut=req.body.check_out||item.check_out,nights=stay(checkIn,checkOut),[adults,children]=occupancy({adults:req.body.adults??item.adults,children:req.body.children??item.children},type);if(repo.availableCount(type.id,checkIn,checkOut,item.id)<1)throw new ApiError(409,'sold_out','No room is available.');const rate=repo.rate(type.id,checkIn,checkOut),total=nights*rate.nightly_rate_cents;db.prepare('UPDATE bookings SET check_in=?,check_out=?,adults=?,children=?,total_cents=?,version=version+1 WHERE id=?').run(checkIn,checkOut,adults,children,total,item.id);db.prepare('UPDATE invoices SET room_cents=?,total_cents=?+incidentals_cents-refund_cents WHERE booking_id=?').run(total,total,item.id);res.json(repo.publicBooking(repo.need('bookings',item.id)));});
 app.post('/api/bookings/:id/cancel',(req,res)=>{const user=auth.current(req,['guest','staff']),item=repo.booking(Number(req.params.id),user);requireFields(req.body,['reason','idempotency_key']);if(item.status!=='confirmed')throw new ApiError(409,'invalid_state','Only confirmed bookings may be cancelled.');const hours=(Date.parse(item.check_in+'T15:00:00Z')-Date.now())/3600000,fee=hours<item.free_hours?Math.round(item.total_cents*item.fee_percent/100):0,refund=item.total_cents-fee;duplicate(()=>db.transaction(()=>{db.prepare("UPDATE bookings SET status='cancelled',version=version+1 WHERE id=?").run(item.id);db.prepare('INSERT INTO cancellations(booking_id,reason,fee_cents,refund_cents,created_at) VALUES(?,?,?,?,?)').run(item.id,req.body.reason,fee,refund,now());db.prepare("INSERT INTO payments(booking_id,amount_cents,kind,status,method_ref,idempotency_key,created_at) VALUES(?,?,'refund','succeeded','local-refund',?,?)").run(item.id,refund,req.body.idempotency_key,now());db.prepare("UPDATE invoices SET refund_cents=?,total_cents=room_cents+incidentals_cents-?,status='finalized',finalized_at=? WHERE booking_id=?").run(refund,refund,now(),item.id);})());res.json({booking:repo.publicBooking(repo.need('bookings',item.id)),fee_cents:fee,refund_cents:refund});});
 // HOTEL-06
 app.post('/api/staff/bookings/:id/check-in',(req,res)=>{const user=auth.current(req,['staff']),booking=repo.booking(Number(req.params.id),user);requireFields(req.body,['room_id']);if(booking.status!=='confirmed')throw new ApiError(409,'invalid_state','Booking cannot be checked in.');const room=repo.need('rooms',Number(req.body.room_id));if(room.room_type_id!==booking.room_type_id||room.status!=='available')throw new ApiError(409,'room_unavailable','Room is unavailable or the wrong type.');db.transaction(()=>{db.prepare("UPDATE bookings SET room_id=?,status='checked_in',version=version+1 WHERE id=?").run(room.id,booking.id);db.prepare("UPDATE rooms SET status='occupied',version=version+1 WHERE id=?").run(room.id);db.prepare('INSERT INTO stays(booking_id,room_id,checked_in_at) VALUES(?,?,?)').run(booking.id,room.id,now());})();repo.audit(user.id,'booking.checked_in',booking.confirmation_code);res.json(repo.publicBooking(repo.need('bookings',booking.id)));});
 app.post('/api/staff/bookings/:id/check-out',(req,res)=>{const user=auth.current(req,['staff']),booking=repo.booking(Number(req.params.id),user);requireFields(req.body,['incidentals_cents','payment_method_id','idempotency_key']);if(booking.status!=='checked_in')throw new ApiError(409,'invalid_state','Booking is not checked in.');if(!Number.isInteger(req.body.incidentals_cents)||req.body.incidentals_cents<0||req.body.payment_method_id!=='pm_success')throw new ApiError(422,'validation_error','Invalid incidentals or payment fixture.');const invoice=repo.need('invoices',db.prepare('SELECT id FROM invoices WHERE booking_id=?').get(booking.id).id),total=invoice.room_cents+req.body.incidentals_cents;duplicate(()=>db.transaction(()=>{db.prepare("UPDATE bookings SET status='checked_out',version=version+1 WHERE id=?").run(booking.id);db.prepare('UPDATE stays SET checked_out_at=?,incidentals_cents=? WHERE booking_id=?').run(now(),req.body.incidentals_cents,booking.id);db.prepare("UPDATE rooms SET status='available',version=version+1 WHERE id=?").run(booking.room_id);db.prepare("UPDATE invoices SET incidentals_cents=?,total_cents=?,status='finalized',finalized_at=? WHERE booking_id=?").run(req.body.incidentals_cents,total,now(),booking.id);if(req.body.incidentals_cents>0)db.prepare("INSERT INTO payments(booking_id,amount_cents,kind,status,method_ref,idempotency_key,created_at) VALUES(?,?,'charge','succeeded',?,?,?)").run(booking.id,req.body.incidentals_cents,req.body.payment_method_id,req.body.idempotency_key,now());})());repo.audit(user.id,'booking.checked_out',booking.confirmation_code);res.json({booking:repo.publicBooking(repo.need('bookings',booking.id)),invoice:db.prepare('SELECT * FROM invoices WHERE booking_id=?').get(booking.id)});});
 // HOTEL-07
 app.get('/api/staff/rooms',(req,res)=>{auth.current(req,['staff','admin']);res.json({items:db.prepare('SELECT * FROM rooms ORDER BY number').all()});});
 app.post('/api/admin/rooms',(req,res)=>{auth.current(req,['admin']);requireFields(req.body,['number','room_type_id']);repo.roomType(Number(req.body.room_type_id));if(!/^\d{3,5}$/.test(String(req.body.number)))throw new ApiError(422,'validation_error','Invalid room number.');const id=duplicate(()=>db.prepare("INSERT INTO rooms(number,room_type_id,status) VALUES(?,?,'available')").run(String(req.body.number),Number(req.body.room_type_id)).lastInsertRowid);res.status(201).json(repo.need('rooms',id));});
 app.patch('/api/staff/rooms/:id',(req,res)=>{auth.current(req,['staff','admin']);const room=repo.need('rooms',Number(req.params.id));version(req.body,room);const status=req.body.status??room.status;if(!['available','maintenance','occupied'].includes(status))throw new ApiError(422,'validation_error','Invalid room status.');if(room.status==='occupied'&&status==='available')throw new ApiError(409,'invalid_state','Occupied room must be checked out.');if(status==='maintenance'&&typeof req.body.maintenance_reason!=='string')throw new ApiError(422,'validation_error','Maintenance reason required.');db.prepare('UPDATE rooms SET status=?,maintenance_reason=?,version=version+1 WHERE id=?').run(status,status==='maintenance'?req.body.maintenance_reason:null,room.id);res.json(repo.need('rooms',room.id));});
 app.patch('/api/admin/room-types/:id',(req,res)=>{auth.current(req,['admin']);const type=repo.roomType(Number(req.params.id));version(req.body,type);const adults=req.body.capacity_adults??type.capacity_adults,children=req.body.capacity_children??type.capacity_children;if(!Number.isInteger(adults)||!Number.isInteger(children)||adults<1||children<0)throw new ApiError(422,'validation_error','Invalid room capacity.');db.prepare('UPDATE room_types SET name=?,description=?,capacity_adults=?,capacity_children=?,amenities=?,version=version+1 WHERE id=?').run(req.body.name??type.name,req.body.description??type.description,adults,children,JSON.stringify(req.body.amenities??JSON.parse(type.amenities)),type.id);const updated=repo.roomType(type.id);res.json({...updated,amenities:JSON.parse(updated.amenities)});});
 // HOTEL-08
 app.get('/api/bookings/:id/messages',(req,res)=>{const user=auth.current(req,['guest','staff']);repo.booking(Number(req.params.id),user);res.json({items:db.prepare('SELECT id,booking_id,sender_id,body,created_at FROM booking_messages WHERE booking_id=? ORDER BY id').all(Number(req.params.id))});});
 app.post('/api/bookings/:id/messages',(req,res)=>{const user=auth.current(req,['guest','staff']),booking=repo.booking(Number(req.params.id),user);requireFields(req.body,['body','idempotency_key']);if(typeof req.body.body!=='string'||req.body.body.length<1||req.body.body.length>1000)throw new ApiError(422,'validation_error','Invalid message body.');const id=duplicate(()=>db.prepare('INSERT INTO booking_messages(booking_id,sender_id,body,created_at,idempotency_key) VALUES(?,?,?,?,?)').run(booking.id,user.id,req.body.body,now(),req.body.idempotency_key).lastInsertRowid);res.status(201).json(repo.need('booking_messages',id));});
 // HOTEL-09
 app.get('/api/room-types/:id/reviews',(req,res)=>{repo.roomType(Number(req.params.id));res.json({items:db.prepare("SELECT id,room_type_id,rating,title,body,created_at FROM reviews WHERE room_type_id=? AND moderation_status='published' ORDER BY id DESC").all(Number(req.params.id))});});
 app.post('/api/bookings/:id/review',(req,res)=>{const user=auth.current(req,['guest']),booking=repo.booking(Number(req.params.id),user);if(booking.status!=='checked_out')throw new ApiError(409,'invalid_state','Review requires a completed stay.');reviewFields(req.body);const id=duplicate(()=>db.prepare('INSERT INTO reviews(booking_id,room_type_id,author_id,rating,title,body,created_at) VALUES(?,?,?,?,?,?,?)').run(booking.id,booking.room_type_id,user.id,req.body.rating,req.body.title,req.body.body,now()).lastInsertRowid);res.status(201).json(repo.need('reviews',id));});
 app.patch('/api/reviews/:id',(req,res)=>{const user=auth.current(req,['guest']),item=repo.need('reviews',Number(req.params.id));if(item.author_id!==user.id)throw new ApiError(403,'forbidden','Only the author may edit this review.');version(req.body,item);const merged={rating:req.body.rating??item.rating,title:req.body.title??item.title,body:req.body.body??item.body};reviewFields(merged);db.prepare('UPDATE reviews SET rating=?,title=?,body=?,version=version+1 WHERE id=?').run(merged.rating,merged.title,merged.body,item.id);res.json(repo.need('reviews',item.id));});
 app.post('/api/admin/reviews/:id/moderate',(req,res)=>{auth.current(req,['admin','moderator']);const item=repo.need('reviews',Number(req.params.id));requireFields(req.body,['status','reason']);if(!['published','hidden'].includes(req.body.status))throw new ApiError(422,'validation_error','Invalid moderation status.');db.prepare('UPDATE reviews SET moderation_status=?,moderation_reason=?,version=version+1 WHERE id=?').run(req.body.status,req.body.reason,item.id);res.json(repo.need('reviews',item.id));});
 // HOTEL-10
 app.get('/api/bookings/:id/invoice',(req,res)=>{const user=auth.current(req,['guest','staff']),booking=repo.booking(Number(req.params.id),user),invoice=db.prepare('SELECT * FROM invoices WHERE booking_id=?').get(booking.id);if(!invoice)throw new ApiError(404,'not_found','Invoice not found.');res.json(invoice);});
 app.get('/api/bookings/:id/receipt.pdf',(req,res)=>{const user=auth.current(req,['guest','staff']),booking=repo.booking(Number(req.params.id),user),invoice=db.prepare('SELECT * FROM invoices WHERE booking_id=?').get(booking.id),payment=db.prepare("SELECT 1 ok FROM payments WHERE booking_id=? AND kind='charge' AND status='succeeded'").get(booking.id);if(!invoice||!payment)throw new ApiError(409,'invalid_state','Receipt requires a recorded payment.');const pdf=Buffer.from(`%PDF-1.4\nHotel receipt ${booking.confirmation_code}\nTotal ${invoice.total_cents}\n%%EOF\n`);res.type('application/pdf').set('Content-Disposition',`attachment; filename=receipt-${booking.id}.pdf`).send(pdf);});
 // HOTEL-11
 app.get('/api/admin/reports/occupancy',(req,res)=>{auth.current(req,['admin']);const[from,to]=range(req.query),booked=db.prepare("SELECT COUNT(*) count FROM bookings WHERE status IN ('confirmed','checked_in','checked_out') AND check_in<? AND check_out>?").get(to,from).count,rooms=db.prepare('SELECT COUNT(*) count FROM rooms').get().count;res.json({from,to,booked_room_stays:booked,total_rooms:rooms,occupancy_percent:rooms?Math.round(booked*100/rooms):0});});
 app.get('/api/admin/reports/revenue',(req,res)=>{auth.current(req,['admin']);const[from,to]=range(req.query),total=db.prepare("SELECT COALESCE(SUM(amount_cents),0) total FROM payments WHERE kind='charge' AND status='succeeded' AND created_at>=? AND created_at<?").get(from,to).total;res.json({from,to,revenue_cents:total});});
 app.get('/api/admin/reports/cancellations',(req,res)=>{auth.current(req,['admin']);const[from,to]=range(req.query),row=db.prepare('SELECT COUNT(*) count,COALESCE(SUM(fee_cents),0) fees FROM cancellations WHERE created_at>=? AND created_at<?').get(from,to);res.json({from,to,cancellations:row.count,fees_cents:row.fees});});
 // HOTEL-12
 app.get('/api/admin/rate-plans',(req,res)=>{auth.current(req,['admin','staff']);res.json({items:db.prepare('SELECT * FROM rate_plans ORDER BY id').all()});});
 app.post('/api/admin/rate-plans',(req,res)=>{auth.current(req,['admin']);requireFields(req.body,['room_type_id','policy_id','name','nightly_rate_cents','valid_from','valid_to','max_adults','max_children']);repo.roomType(Number(req.body.room_type_id));repo.need('cancellation_policies',Number(req.body.policy_id));stay(req.body.valid_from,req.body.valid_to,{future:false});if(!Number.isInteger(req.body.nightly_rate_cents)||req.body.nightly_rate_cents<1000||!Number.isInteger(req.body.max_adults)||!Number.isInteger(req.body.max_children))throw new ApiError(422,'validation_error','Invalid rate plan.');const overlap=db.prepare('SELECT 1 ok FROM rate_plans WHERE room_type_id=? AND valid_from<? AND valid_to>?').get(req.body.room_type_id,req.body.valid_to,req.body.valid_from);if(overlap)throw new ApiError(409,'overlap','Rate period overlaps an existing plan.');const id=duplicate(()=>db.prepare('INSERT INTO rate_plans(room_type_id,policy_id,name,nightly_rate_cents,valid_from,valid_to,max_adults,max_children) VALUES(?,?,?,?,?,?,?,?)').run(req.body.room_type_id,req.body.policy_id,req.body.name,req.body.nightly_rate_cents,req.body.valid_from,req.body.valid_to,req.body.max_adults,req.body.max_children).lastInsertRowid);res.status(201).json(repo.need('rate_plans',id));});
 app.patch('/api/admin/rate-plans/:id',(req,res)=>{auth.current(req,['admin']);const item=repo.need('rate_plans',Number(req.params.id));version(req.body,item);const rate=req.body.nightly_rate_cents??item.nightly_rate_cents;if(!Number.isInteger(rate)||rate<1000)throw new ApiError(422,'validation_error','Invalid nightly rate.');db.prepare('UPDATE rate_plans SET name=?,nightly_rate_cents=?,version=version+1 WHERE id=?').run(req.body.name??item.name,rate,item.id);res.json(repo.need('rate_plans',item.id));});
 app.get('/api/admin/cancellation-policies',(req,res)=>{auth.current(req,['admin','staff']);res.json({items:db.prepare('SELECT * FROM cancellation_policies ORDER BY id').all()});});
 app.post('/api/admin/cancellation-policies',(req,res)=>{auth.current(req,['admin']);requireFields(req.body,['name','free_hours','fee_percent']);if(!Number.isInteger(req.body.free_hours)||req.body.free_hours<0||!Number.isInteger(req.body.fee_percent)||req.body.fee_percent<0||req.body.fee_percent>100)throw new ApiError(422,'validation_error','Invalid cancellation policy.');const id=duplicate(()=>db.prepare('INSERT INTO cancellation_policies(name,free_hours,fee_percent) VALUES(?,?,?)').run(req.body.name,req.body.free_hours,req.body.fee_percent).lastInsertRowid);res.status(201).json(repo.need('cancellation_policies',id));});
 app.patch('/api/admin/cancellation-policies/:id',(req,res)=>{auth.current(req,['admin']);const item=repo.need('cancellation_policies',Number(req.params.id));version(req.body,item);const hours=req.body.free_hours??item.free_hours,fee=req.body.fee_percent??item.fee_percent;if(!Number.isInteger(hours)||hours<0||!Number.isInteger(fee)||fee<0||fee>100)throw new ApiError(422,'validation_error','Invalid cancellation policy.');db.prepare('UPDATE cancellation_policies SET name=?,free_hours=?,fee_percent=?,version=version+1 WHERE id=?').run(req.body.name??item.name,hours,fee,item.id);res.json(repo.need('cancellation_policies',item.id));});
 app.use((req,res)=>res.status(404).json({error:{code:'not_found',message:'Resource not found.',fields:{}}}));
 app.use((error,_req,res,_next)=>{if(error instanceof ApiError)return res.status(error.status).json({error:{code:error.code,message:error.message,fields:error.fields}});return res.status(500).json({error:{code:'internal_error',message:'The request could not be completed.',fields:{}}});});return app;
}
