<?php
declare(strict_types=1);
namespace App;
use PDO;use Slim\App;use Psr\Http\Message\ServerRequestInterface as Request;use Psr\Http\Message\ResponseInterface as Response;
final class AuthRoutes{use Support;public static function register(App $app,PDO $db,Auth $auth,array $cfg):void{
$app->get('/',fn(Request $r,Response $s)=>$s->withHeader('Location','/app.html')->withStatus(302));$app->get('/health',fn(Request $r,Response $s)=>Http::json($s,['status'=>'ok','database'=>(bool)$db->query('SELECT 1')->fetchColumn()]));
$app->post('/api/auth/register',function(Request $r,Response $s)use($db,$auth,$cfg){$d=self::body($r);self::required($d,['email','password','name']);if(!filter_var($d['email'],FILTER_VALIDATE_EMAIL))throw new ApiException(422,'validation_failed','Invalid email.',['email'=>'Enter a valid email.']);if(strlen((string)$d['password'])<10)throw new ApiException(422,'validation_failed','Password is too short.',['password'=>'Use at least 10 characters.']);try{$db->prepare("INSERT INTO users(email,password_hash,name,role,affiliation) VALUES(?,?,?,'author',?)")->execute([strtolower(trim($d['email'])),password_hash($d['password'],PASSWORD_DEFAULT),trim($d['name']),trim((string)($d['affiliation']??''))]);}catch(\PDOException){throw new ApiException(409,'email_exists','An account already uses this email.');}$id=(int)$db->lastInsertId();$token=$auth->create($id);return Http::json($s,['user'=>self::one($db,'SELECT id,email,name,role,affiliation FROM users WHERE id=?',[$id])],201)->withAddedHeader('Set-Cookie',$auth->cookie($token,$cfg['sessionTtl']));});
$app->post('/api/auth/login',function(Request $r,Response $s)use($db,$auth,$cfg){$d=self::body($r);self::required($d,['email','password']);$st=$db->prepare('SELECT * FROM users WHERE email=? COLLATE NOCASE');$st->execute([trim($d['email'])]);$u=$st->fetch();if(!$u||!password_verify((string)$d['password'],$u['password_hash']))throw new ApiException(401,'invalid_credentials','Email or password is incorrect.');$token=$auth->create((int)$u['id']);unset($u['password_hash']);return Http::json($s,['user'=>$u])->withAddedHeader('Set-Cookie',$auth->cookie($token,$cfg['sessionTtl']));});
$app->post('/api/auth/logout',function(Request $r,Response $s)use($auth){$auth->destroy($r);return Http::json($s,['message'=>'Signed out.'])->withAddedHeader('Set-Cookie',$auth->cookie('',0));});
$app->post('/api/auth/password-reset-requests',function(Request $r,Response $s)use($db,$cfg){$d=self::body($r);self::required($d,['email']);$st=$db->prepare('SELECT id FROM users WHERE email=? COLLATE NOCASE');$st->execute([trim($d['email'])]);$id=$st->fetchColumn();$out=['message'=>'If that account exists, reset instructions were created.'];if($id){$plain=bin2hex(random_bytes(24));$db->prepare('DELETE FROM password_reset_tokens WHERE user_id=?')->execute([$id]);$db->prepare("INSERT INTO password_reset_tokens(token_hash,user_id,expires_at) VALUES(?,?,datetime('now',?))")->execute([hash('sha256',$plain),$id,'+'.$cfg['resetTtl'].' seconds']);if(($_ENV['APP_ENV']??'development')==='development')$out['developmentResetToken']=$plain;}return Http::json($s,$out);});
$app->post('/api/auth/password-resets',function(Request $r,Response $s)use($db){$d=self::body($r);self::required($d,['resetToken','newPassword']);if(strlen($d['newPassword'])<10)throw new ApiException(422,'validation_failed','Password is too short.',['newPassword'=>'Use at least 10 characters.']);$x=self::one($db,"SELECT * FROM password_reset_tokens WHERE token_hash=? AND used_at IS NULL AND expires_at>datetime('now')",[hash('sha256',$d['resetToken'])],'reset_token_invalid');$db->beginTransaction();$db->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($d['newPassword'],PASSWORD_DEFAULT),$x['user_id']]);$db->prepare("UPDATE password_reset_tokens SET used_at=datetime('now') WHERE token_hash=?")->execute([$x['token_hash']]);$db->prepare('DELETE FROM sessions WHERE user_id=?')->execute([$x['user_id']]);$db->commit();return Http::json($s,['message'=>'Password reset completed.']);});
$app->get('/api/notifications',function(Request $r,Response $s)use($auth,$db){$u=$auth->requireUser($r,['author','reviewer','chair']);[$limit,$offset,$page]=self::page($r);$unread=filter_var($r->getQueryParams()['unread']??false,FILTER_VALIDATE_BOOLEAN);$sql='SELECT * FROM notifications WHERE user_id=?'.($unread?' AND read_at IS NULL':'').' ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?';return Http::json($s,['items'=>self::all($db,$sql,[$u['id'],$limit,$offset]),'page'=>$page,'limit'=>$limit]);});
$app->post('/api/notifications/{notificationId}/read',function(Request $r,Response $s,array $a)use($auth,$db){$u=$auth->requireUser($r,['author','reviewer','chair']);$n=self::one($db,'SELECT * FROM notifications WHERE id=? AND user_id=?',[(int)$a['notificationId'],$u['id']],'notification_not_found');$db->prepare("UPDATE notifications SET read_at=COALESCE(read_at,datetime('now')) WHERE id=?")->execute([$n['id']]);return Http::json($s,['notification'=>self::one($db,'SELECT * FROM notifications WHERE id=?',[$n['id']])]);});
$app->get('/api/submissions/{submissionId}/activity',function(Request $r,Response $s,array $a)use($auth,$db){$u=$auth->requireUser($r,['author','reviewer','chair']);$access=new Access($db);$sub=$access->submission((int)$a['submissionId']);$access->requireSubmissionAccess($u,$sub);$rows=self::all($db,'SELECT id,event,details,created_at FROM submission_activity WHERE submission_id=? ORDER BY created_at,id',[$sub['id']]);return Http::json($s,['items'=>$rows]);});
}}
