PRAGMA foreign_keys = OFF;
DROP TABLE IF EXISTS ticket_replies; DROP TABLE IF EXISTS support_tickets; DROP TABLE IF EXISTS metric_samples;
DROP TABLE IF EXISTS scheduled_tasks; DROP TABLE IF EXISTS certificates; DROP TABLE IF EXISTS restore_jobs; DROP TABLE IF EXISTS backups;
DROP TABLE IF EXISTS database_users; DROP TABLE IF EXISTS hosted_databases; DROP TABLE IF EXISTS site_files; DROP TABLE IF EXISTS deployments;
DROP TABLE IF EXISTS dns_records; DROP TABLE IF EXISTS audit_events; DROP TABLE IF EXISTS sites; DROP TABLE IF EXISTS domains;
DROP TABLE IF EXISTS sessions; DROP TABLE IF EXISTS reset_tokens; DROP TABLE IF EXISTS accounts; DROP TABLE IF EXISTS plans; DROP TABLE IF EXISTS settings; DROP TABLE IF EXISTS users;
PRAGMA foreign_keys = ON;

CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('customer','operator','admin')), status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE plans (id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL, storage_mb INTEGER NOT NULL, site_limit INTEGER NOT NULL, price_cents INTEGER NOT NULL);
CREATE TABLE accounts (id INTEGER PRIMARY KEY, user_id INTEGER UNIQUE NOT NULL REFERENCES users(id), plan_id INTEGER NOT NULL REFERENCES plans(id), status TEXT NOT NULL, quota_mb INTEGER NOT NULL, version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE sessions (id INTEGER PRIMARY KEY, token_hash TEXT UNIQUE NOT NULL, user_id INTEGER NOT NULL REFERENCES users(id), expires_at TEXT NOT NULL);
CREATE TABLE reset_tokens (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), token_hash TEXT UNIQUE NOT NULL, expires_at TEXT NOT NULL, used_at TEXT);
CREATE TABLE domains (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL REFERENCES accounts(id), name TEXT UNIQUE NOT NULL, status TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE dns_records (id INTEGER PRIMARY KEY, domain_id INTEGER NOT NULL REFERENCES domains(id) ON DELETE CASCADE, type TEXT NOT NULL, name TEXT NOT NULL, value TEXT NOT NULL, ttl INTEGER NOT NULL, UNIQUE(domain_id,type,name,value));
CREATE TABLE sites (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL REFERENCES accounts(id), domain_id INTEGER NOT NULL REFERENCES domains(id), name TEXT NOT NULL, runtime TEXT NOT NULL, status TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, UNIQUE(account_id,name));
CREATE TABLE deployments (id INTEGER PRIMARY KEY, site_id INTEGER NOT NULL REFERENCES sites(id), status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE site_files (id INTEGER PRIMARY KEY, site_id INTEGER NOT NULL REFERENCES sites(id) ON DELETE CASCADE, path TEXT NOT NULL, content TEXT NOT NULL, size INTEGER NOT NULL, updated_at TEXT NOT NULL, UNIQUE(site_id,path));
CREATE TABLE hosted_databases (id INTEGER PRIMARY KEY, site_id INTEGER NOT NULL REFERENCES sites(id) ON DELETE CASCADE, name TEXT NOT NULL, engine TEXT NOT NULL, status TEXT NOT NULL, UNIQUE(site_id,name));
CREATE TABLE database_users (id INTEGER PRIMARY KEY, database_id INTEGER NOT NULL REFERENCES hosted_databases(id) ON DELETE CASCADE, username TEXT NOT NULL, password_hash TEXT NOT NULL, UNIQUE(database_id,username));
CREATE TABLE backups (id INTEGER PRIMARY KEY, site_id INTEGER NOT NULL REFERENCES sites(id), status TEXT NOT NULL, content TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(site_id,created_at));
CREATE TABLE restore_jobs (id INTEGER PRIMARY KEY, backup_id INTEGER NOT NULL REFERENCES backups(id), status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE certificates (id INTEGER PRIMARY KEY, domain_id INTEGER NOT NULL REFERENCES domains(id) ON DELETE CASCADE, status TEXT NOT NULL, expires_at TEXT NOT NULL, UNIQUE(domain_id,status));
CREATE TABLE scheduled_tasks (id INTEGER PRIMARY KEY, site_id INTEGER NOT NULL REFERENCES sites(id) ON DELETE CASCADE, command TEXT NOT NULL, schedule TEXT NOT NULL, enabled INTEGER NOT NULL, version INTEGER NOT NULL DEFAULT 1, UNIQUE(site_id,command));
CREATE TABLE metric_samples (id INTEGER PRIMARY KEY, site_id INTEGER NOT NULL REFERENCES sites(id), sampled_at TEXT NOT NULL, cpu REAL NOT NULL, memory_mb REAL NOT NULL, storage_mb REAL NOT NULL, requests INTEGER NOT NULL);
CREATE TABLE support_tickets (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL REFERENCES accounts(id), subject TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE ticket_replies (id INTEGER PRIMARY KEY, ticket_id INTEGER NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE, user_id INTEGER NOT NULL REFERENCES users(id), body TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE audit_events (id INTEGER PRIMARY KEY, actor_id INTEGER NOT NULL REFERENCES users(id), site_id INTEGER REFERENCES sites(id), action TEXT NOT NULL, details TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
