#ifndef NETD_COMMON_H
#define NETD_COMMON_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#define NETD_VERSION_MAJOR 1
#define NETD_VERSION_MINOR 0
#define NETD_VERSION_PATCH 0
#define NETD_VERSION_STRING "1.0.0"

#define NETD_DEFAULT_PORT 9090
#define NETD_DEFAULT_BIND "127.0.0.1"
#define NETD_DEFAULT_DB_PATH "./var/netd.db"
#define NETD_DEFAULT_LOG_PATH "./var/netd.log"
#define NETD_DEFAULT_AUDIT_PATH "./var/netd.audit.log"
#define NETD_DEFAULT_PID_FILE "./var/netd.pid"
#define NETD_DEFAULT_WORKERS 4
#define NETD_DEFAULT_IDLE_TIMEOUT 60
#define NETD_DEFAULT_MAX_CLIENTS 64
#define NETD_DEFAULT_MAX_COMMAND_BYTES 65536
#define NETD_DEFAULT_EXPIRY_INTERVAL 10
#define NETD_DEFAULT_EXPIRY_BATCH 100
#define NETD_DEFAULT_SHUTDOWN_TIMEOUT 10

#define NETD_LISTENER_BACKLOG 128
#define NETD_OUT_BUFFER_SIZE 8192
#define NETD_SEED_EPOCH 1700000000

#define NETD_ROLE_CLIENT "client"
#define NETD_ROLE_MONITORING "monitoring"
#define NETD_ROLE_ADMINISTRATOR "administrator"

#define NETD_PERM_READ "read"
#define NETD_PERM_WRITE "write"
#define NETD_PERM_ADMIN "admin"

#define NETD_TOKEN_STATUS_ACTIVE "active"
#define NETD_TOKEN_STATUS_REVOKED "revoked"
#define NETD_TOKEN_STATUS_EXPIRED "expired"

#define NETD_HEALTH_OK "OK"
#define NETD_HEALTH_DEGRADED "DEGRADED"
#define NETD_HEALTH_STOPPING "STOPPING"

#define NETD_OK "OK"
#define NETD_ERR "ERR"

#define NETD_OK_AUTH "AUTH"
#define NETD_OK_CREATED "CREATED"
#define NETD_OK_VALUE "VALUE"
#define NETD_OK_NOTFOUND "NOTFOUND"
#define NETD_OK_KEYS "KEYS"
#define NETD_OK_UPDATED "UPDATED"
#define NETD_OK_DELETED "DELETED"
#define NETD_OK_PONG "PONG"
#define NETD_OK_HEALTH "HEALTH"
#define NETD_OK_STATS "STATS"
#define NETD_OK_BYE "BYE"
#define NETD_OK_RELOADED "RELOADED"

#define NETD_ERR_PROTOCOL "PROTOCOL"
#define NETD_ERR_PROTOCOL_INVALID_LINE "PROTOCOL_INVALID_LINE"
#define NETD_ERR_PROTOCOL_BAD_UTF8 "PROTOCOL_BAD_UTF8"
#define NETD_ERR_PROTOCOL_TOO_LONG "PROTOCOL_TOO_LONG"
#define NETD_ERR_PROTOCOL_BAD_COUNT "PROTOCOL_BAD_COUNT"

#define NETD_ERR_AUTH "AUTH"
#define NETD_ERR_AUTH_REQUIRED "AUTH_REQUIRED"
#define NETD_ERR_AUTH_INVALID "AUTH_INVALID"
#define NETD_ERR_AUTH_EXPIRED "AUTH_EXPIRED"
#define NETD_ERR_AUTH_REVOKED "AUTH_REVOKED"
#define NETD_ERR_AUTH_TIMEOUT "AUTH_TIMEOUT"
#define NETD_ERR_AUTH_FORBIDDEN "AUTH_FORBIDDEN"

#define NETD_ERR_ACCESS_DENIED "ACCESS_DENIED"
#define NETD_ERR_NOT_FOUND "NOT_FOUND"
#define NETD_ERR_ALREADY_EXISTS "ALREADY_EXISTS"
#define NETD_ERR_CONFLICT "CONFLICT"
#define NETD_ERR_BAD_REQUEST "BAD_REQUEST"
#define NETD_ERR_TOO_LARGE "TOO_LARGE"
#define NETD_ERR_INVALID_TTL "INVALID_TTL"
#define NETD_ERR_INVALID_BASE64 "INVALID_BASE64"
#define NETD_ERR_INVALID_NAMESPACE "INVALID_NAMESPACE"
#define NETD_ERR_INVALID_KEY "INVALID_KEY"
#define NETD_ERR_LIMIT_EXCEEDED "LIMIT_EXCEEDED"
#define NETD_ERR_BUSY "BUSY"
#define NETD_ERR_SHUTTING_DOWN "SHUTTING_DOWN"
#define NETD_ERR_INTERNAL "INTERNAL"

#define NETD_EVENT_STARTUP "STARTUP"
#define NETD_EVENT_READY "READY"
#define NETD_EVENT_SHUTDOWN "SHUTDOWN"
#define NETD_EVENT_CONFIG_LOAD "CONFIG_LOAD"
#define NETD_EVENT_CONFIG_RELOAD "CONFIG_RELOAD"
#define NETD_EVENT_AUTH_OK "AUTH_OK"
#define NETD_EVENT_AUTH_FAIL "AUTH_FAIL"
#define NETD_EVENT_AUTH_TIMEOUT "AUTH_TIMEOUT"
#define NETD_EVENT_RECORD_CREATE "RECORD_CREATE"
#define NETD_EVENT_RECORD_UPDATE "RECORD_UPDATE"
#define NETD_EVENT_RECORD_DELETE "RECORD_DELETE"
#define NETD_EVENT_RECORD_READ "RECORD_READ"
#define NETD_EVENT_RECORD_LIST "RECORD_LIST"
#define NETD_EVENT_EXPIRY_RUN "EXPIRY_RUN"
#define NETD_EVENT_LIMIT_REJECT "LIMIT_REJECT"
#define NETD_EVENT_LOG_REOPEN "LOG_REOPEN"
#define NETD_EVENT_OUTCOME_OK "OK"
#define NETD_EVENT_OUTCOME_FAIL "FAIL"
#define NETD_EVENT_OUTCOME_DEFER "DEFER"

#define NETD_METRIC_CONNECTIONS_ACCEPTED "connections_accepted_total"
#define NETD_METRIC_CONNECTIONS_CLOSED "connections_closed_total"
#define NETD_METRIC_COMMANDS_TOTAL "commands_total"
#define NETD_METRIC_AUTH_SUCCESS "auth_success_total"
#define NETD_METRIC_AUTH_FAILED "auth_failed_total"
#define NETD_METRIC_RECORDS_PUT "records_put_total"
#define NETD_METRIC_RECORDS_GET "records_get_total"
#define NETD_METRIC_RECORDS_UPDATED "records_updated_total"
#define NETD_METRIC_RECORDS_DELETED "records_deleted_total"
#define NETD_METRIC_RECORDS_EXPIRED "records_expired_total"
#define NETD_METRIC_LIST_OPS "list_operations_total"
#define NETD_METRIC_BYTES_IN "bytes_in_total"
#define NETD_METRIC_BYTES_OUT "bytes_out_total"
#define NETD_METRIC_LOG_ERRORS "log_write_errors_total"
#define NETD_METRIC_DB_BUSY_TIMEOUTS "db_busy_timeouts_total"

#endif