<?php
declare(strict_types=1);
namespace App;

use PDO;
use Slim\App;

final class Routes
{
    public static function register(App $app, PDO $db, Auth $auth, HostingRepository $repo, array $config): void
    {
        $ok=fn($r,$data,$status=200)=>Http::json($r,$data,$status);
        $one=function(string $sql,array $args)use($db):array{$s=$db->prepare($sql);$s->execute($args);$row=$s->fetch();if(!$row)throw new ApiException(404,'not_found','Resource not found.');return $row;};
        $version=function(array $data,array $row):void{if(isset($data['version'])&&(int)$data['version']!==(int)$row['version'])throw new ApiException(409,'stale_version','Resource version is stale.');};
        $path=function(string $value):string{$v='/' . ltrim(trim($value),'/');if(str_contains($v,'..')||strlen($v)>255)throw new ApiException(422,'validation_error','Invalid path.',['path'=>'must remain under site root']);return $v;};
        $duplicate=function(callable $work):void{try{$work();}catch(\PDOException $e){if($e->getCode()==='23000')throw new ApiException(409,'conflict','Resource already exists.');throw $e;}};

        // HOST-01
        $app->post('/api/auth/login',function($q,$r)use($auth,$ok){$d=Http::body($q);Http::requireFields($d,['email','password']);[$u,$token]=$auth->login($d['email'],$d['password']);return $ok($r,['user'=>$u])->withHeader('Set-Cookie',$auth->cookie.'='.rawurlencode($token).'; Path=/; HttpOnly; SameSite=Lax');});
        $app->post('/api/auth/logout',function($q,$r)use($auth,$ok){$auth->user($q);$auth->logout($q);return $ok($r,['logged_out'=>true])->withHeader('Set-Cookie',$auth->cookie.'=; Path=/; HttpOnly; Max-Age=0; SameSite=Lax');});
        $app->post('/api/auth/password-reset-requests',function($q,$r)use($db,$ok,$config){$d=Http::body($q);Http::requireFields($d,['email']);$s=$db->prepare('SELECT id FROM users WHERE email=? AND status="active"');$s->execute([strtolower($d['email'])]);$u=$s->fetch();$token=null;if($u){$token='reset-fixture-'.bin2hex(random_bytes(4));$db->prepare('INSERT INTO reset_tokens(user_id,token_hash,expires_at) VALUES(?,?,?)')->execute([$u['id'],hash('sha256',$token),gmdate(DATE_ATOM,time()+$config['resetTtl'])]);}return $ok($r,['accepted'=>true,'reset_token'=>$config['appEnv']==='test'?$token:null],201);});
        $app->post('/api/auth/password-resets',function($q,$r)use($db,$ok){$d=Http::body($q);Http::requireFields($d,['token','password']);if(strlen($d['password'])<10)throw new ApiException(422,'validation_error','Invalid password.',['password'=>'minimum 10 characters']);$s=$db->prepare('SELECT * FROM reset_tokens WHERE token_hash=?');$s->execute([hash('sha256',$d['token'])]);$t=$s->fetch();if(!$t||$t['used_at']!==null||$t['expires_at']<=gmdate(DATE_ATOM))throw new ApiException(409,'invalid_reset_token','Reset token is invalid or expired.');$db->beginTransaction();$db->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($d['password'],PASSWORD_DEFAULT),$t['user_id']]);$db->prepare('UPDATE reset_tokens SET used_at=? WHERE id=?')->execute([gmdate(DATE_ATOM),$t['id']]);$db->prepare('DELETE FROM sessions WHERE user_id=?')->execute([$t['user_id']]);$db->commit();return $ok($r,['password_reset'=>true]);});

        // HOST-02
        $app->get('/api/domains',function($q,$r)use($auth,$repo,$ok){$u=$auth->user($q,['customer']);$a=$repo->account($u);[$l,$o]=Http::page($q);return $ok($r,['items'=>$repo->rows('SELECT * FROM domains WHERE account_id=? ORDER BY id LIMIT ? OFFSET ?',[$a['id'],$l,$o])]);});
        $app->post('/api/domains',function($q,$r)use($auth,$repo,$db,$duplicate,$ok){$u=$auth->user($q,['customer']);$a=$repo->account($u);$d=Http::body($q);Http::requireFields($d,['name']);$name=strtolower($d['name']);if(!filter_var($name,FILTER_VALIDATE_DOMAIN,FILTER_FLAG_HOSTNAME))throw new ApiException(422,'validation_error','Invalid domain.',['name'=>'valid hostname required']);$duplicate(fn()=>$db->prepare('INSERT INTO domains(account_id,name,status) VALUES(?,? ,"pending")')->execute([$a['id'],$name]));$id=(int)$db->lastInsertId();$repo->audit((int)$u['id'],null,'domain.created',$name);return $ok($r,$repo->owned('domains',$id,$u),201);});
        $app->patch('/api/domains/{id}',function($q,$r,$a)use($auth,$repo,$db,$version,$ok){$u=$auth->user($q,['customer']);$row=$repo->owned('domains',(int)$a['id'],$u);$d=Http::body($q);$version($d,$row);$status=$d['status']??null;if(!in_array($status,['active','disabled'],true))throw new ApiException(422,'validation_error','Invalid status.',['status'=>'active or disabled']);$db->prepare('UPDATE domains SET status=?,version=version+1 WHERE id=?')->execute([$status,$row['id']]);return $ok($r,$repo->owned('domains',(int)$row['id'],$u));});
        $app->get('/api/domains/{id}/dns-records',function($q,$r,$a)use($auth,$repo,$ok){$u=$auth->user($q,['customer']);$d=$repo->owned('domains',(int)$a['id'],$u);return $ok($r,['items'=>$repo->rows('SELECT * FROM dns_records WHERE domain_id=? ORDER BY id',[$d['id']])]);});
        $app->post('/api/domains/{id}/dns-records',function($q,$r,$a)use($auth,$repo,$db,$duplicate,$ok){$u=$auth->user($q,['customer']);$domain=$repo->owned('domains',(int)$a['id'],$u);$d=Http::body($q);Http::requireFields($d,['type','name','value']);$type=strtoupper($d['type']);if(!in_array($type,['A','AAAA','CNAME','TXT','MX'],true))throw new ApiException(422,'validation_error','Invalid DNS type.',['type'=>'not allowed']);$ttl=(int)($d['ttl']??3600);if($ttl<60||$ttl>86400)throw new ApiException(422,'validation_error','Invalid TTL.',['ttl'=>'must be 60..86400']);$duplicate(fn()=>$db->prepare('INSERT INTO dns_records(domain_id,type,name,value,ttl) VALUES(?,?,?,?,?)')->execute([$domain['id'],$type,$d['name'],$d['value'],$ttl]));$id=(int)$db->lastInsertId();return $ok($r,$one=self::fetch($db,'SELECT * FROM dns_records WHERE id=?',[$id]),201);});
        $app->delete('/api/dns-records/{id}',function($q,$r,$a)use($auth,$repo,$db){$u=$auth->user($q,['customer']);$row=$repo->child('dns_records',(int)$a['id'],$u,'domains','domain_id');$db->prepare('DELETE FROM dns_records WHERE id=?')->execute([$row['id']]);return $r->withStatus(204);});

        // HOST-03
        $app->get('/api/sites',function($q,$r)use($auth,$repo,$ok){$u=$auth->user($q,['customer']);$a=$repo->account($u);[$l,$o]=Http::page($q);return $ok($r,['items'=>$repo->rows('SELECT * FROM sites WHERE account_id=? ORDER BY id LIMIT ? OFFSET ?',[$a['id'],$l,$o])]);});
        $app->post('/api/sites',function($q,$r)use($auth,$repo,$db,$duplicate,$ok){$u=$auth->user($q,['customer']);$a=$repo->account($u);$d=Http::body($q);Http::requireFields($d,['domain_id','name','runtime']);$domain=$repo->owned('domains',(int)$d['domain_id'],$u);if($domain['status']!=='active')throw new ApiException(409,'invalid_state','Domain must be active.');if(!in_array($d['runtime'],['php83','static','node20'],true))throw new ApiException(422,'validation_error','Invalid runtime.',['runtime'=>'not supported']);$count=(int)$db->query('SELECT COUNT(*) FROM sites WHERE account_id='.(int)$a['id'])->fetchColumn();$plan=self::fetch($db,'SELECT p.* FROM plans p JOIN accounts a ON a.plan_id=p.id WHERE a.id=?',[$a['id']]);if($count>=(int)$plan['site_limit'])throw new ApiException(409,'quota_exceeded','Site limit reached.');$duplicate(fn()=>$db->prepare('INSERT INTO sites(account_id,domain_id,name,runtime,status) VALUES(?,?,?, ?,"draft")')->execute([$a['id'],$domain['id'],$d['name'],$d['runtime']]));$id=(int)$db->lastInsertId();$repo->audit((int)$u['id'],$id,'site.created',$d['name']);return $ok($r,$repo->site($id,$u),201);});
        $app->patch('/api/sites/{id}',function($q,$r,$a)use($auth,$repo,$db,$version,$ok){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);$d=Http::body($q);$version($d,$s);Http::requireFields($d,['name']);$db->prepare('UPDATE sites SET name=?,version=version+1 WHERE id=?')->execute([$d['name'],$s['id']]);return $ok($r,$repo->site((int)$s['id'],$u));});
        $app->post('/api/sites/{id}/deploy',function($q,$r,$a)use($auth,$repo,$db,$ok){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);if($s['status']==='suspended')throw new ApiException(409,'invalid_state','Suspended site cannot deploy.');$db->beginTransaction();$db->prepare('INSERT INTO deployments(site_id,status,created_at) VALUES(?,"succeeded",?)')->execute([$s['id'],gmdate(DATE_ATOM)]);$id=(int)$db->lastInsertId();$db->prepare('UPDATE sites SET status="active",version=version+1 WHERE id=?')->execute([$s['id']]);$repo->audit((int)$u['id'],(int)$s['id'],'site.deployed','Deployment '.$id);$db->commit();return $ok($r,self::fetch($db,'SELECT * FROM deployments WHERE id=?',[$id]));});
        $app->post('/api/sites/{id}/suspend',function($q,$r,$a)use($auth,$repo,$db,$ok){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);if($s['status']==='suspended')throw new ApiException(409,'invalid_state','Site is already suspended.');$db->prepare('UPDATE sites SET status="suspended",version=version+1 WHERE id=?')->execute([$s['id']]);return $ok($r,$repo->site((int)$s['id'],$u));});

        // HOST-04
        $app->get('/api/sites/{id}/files',function($q,$r,$a)use($auth,$repo,$path,$ok){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);$base=$path((string)($q->getQueryParams()['path']??'/'));return $ok($r,['items'=>$repo->rows('SELECT id,path,size,updated_at FROM site_files WHERE site_id=? AND path LIKE ? ORDER BY path',[$s['id'],rtrim($base,'/').'/%'])]);});
        $app->post('/api/sites/{id}/files',function($q,$r,$a)use($auth,$repo,$db,$path,$duplicate,$ok){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);$d=Http::body($q);Http::requireFields($d,['path','content']);$p=$path($d['path']);if(strlen($d['content'])>1048576)throw new ApiException(422,'validation_error','File too large.',['content'=>'maximum 1 MiB']);$duplicate(fn()=>$db->prepare('INSERT INTO site_files(site_id,path,content,size,updated_at) VALUES(?,?,?,?,?)')->execute([$s['id'],$p,$d['content'],strlen($d['content']),gmdate(DATE_ATOM)]));$id=(int)$db->lastInsertId();return $ok($r,self::fetch($db,'SELECT id,path,size,updated_at FROM site_files WHERE id=?',[$id]),201);});
        $app->get('/api/sites/{id}/files/content',function($q,$r,$a)use($auth,$repo,$path,$ok){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);$p=$path((string)($q->getQueryParams()['path']??''));$row=self::fetch($repo->db,'SELECT path,content,size FROM site_files WHERE site_id=? AND path=?',[$s['id'],$p]);return $ok($r,$row);});
        $app->post('/api/sites/{id}/files/move',function($q,$r,$a)use($auth,$repo,$db,$path,$ok){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);$d=Http::body($q);Http::requireFields($d,['from','to']);$from=$path($d['from']);$to=$path($d['to']);$row=self::fetch($db,'SELECT * FROM site_files WHERE site_id=? AND path=?',[$s['id'],$from]);try{$db->prepare('UPDATE site_files SET path=?,updated_at=? WHERE id=?')->execute([$to,gmdate(DATE_ATOM),$row['id']]);}catch(\PDOException){throw new ApiException(409,'conflict','Destination already exists.');}return $ok($r,self::fetch($db,'SELECT id,path,size,updated_at FROM site_files WHERE id=?',[$row['id']]));});
        $app->delete('/api/sites/{id}/files',function($q,$r,$a)use($auth,$repo,$db,$path){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);$p=$path((string)($q->getQueryParams()['path']??''));$st=$db->prepare('DELETE FROM site_files WHERE site_id=? AND path=?');$st->execute([$s['id'],$p]);if($st->rowCount()===0)throw new ApiException(404,'not_found','Resource not found.');return $r->withStatus(204);});

        // HOST-05
        $app->get('/api/sites/{id}/databases',function($q,$r,$a)use($auth,$repo,$ok){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);return $ok($r,['items'=>$repo->rows('SELECT * FROM hosted_databases WHERE site_id=? ORDER BY id',[$s['id']])]);});
        $app->post('/api/sites/{id}/databases',function($q,$r,$a)use($auth,$repo,$db,$duplicate,$ok){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);$d=Http::body($q);Http::requireFields($d,['name','engine']);if(!in_array($d['engine'],['sqlite','mysql8','postgres16'],true))throw new ApiException(422,'validation_error','Invalid engine.',['engine'=>'not supported']);$duplicate(fn()=>$db->prepare('INSERT INTO hosted_databases(site_id,name,engine,status) VALUES(?,?,?,"ready")')->execute([$s['id'],$d['name'],$d['engine']]));return $ok($r,self::fetch($db,'SELECT * FROM hosted_databases WHERE id=?',[(int)$db->lastInsertId()]),201);});
        $app->post('/api/databases/{id}/users',function($q,$r,$a)use($auth,$repo,$db,$duplicate,$ok){$u=$auth->user($q,['customer']);$database=$repo->child('hosted_databases',(int)$a['id'],$u,'sites','site_id');$d=Http::body($q);Http::requireFields($d,['username','password']);if(strlen($d['password'])<10)throw new ApiException(422,'validation_error','Invalid password.',['password'=>'minimum 10 characters']);$duplicate(fn()=>$db->prepare('INSERT INTO database_users(database_id,username,password_hash) VALUES(?,?,?)')->execute([$database['id'],$d['username'],password_hash($d['password'],PASSWORD_DEFAULT)]));return $ok($r,['id'=>(int)$db->lastInsertId(),'username'=>$d['username'],'password'=>$d['password']],201);});
        $app->delete('/api/databases/{id}',function($q,$r,$a)use($auth,$repo,$db){$u=$auth->user($q,['customer']);$row=$repo->child('hosted_databases',(int)$a['id'],$u,'sites','site_id');$db->prepare('DELETE FROM hosted_databases WHERE id=?')->execute([$row['id']]);return $r->withStatus(204);});

        // HOST-06
        $app->get('/api/sites/{id}/backups',function($q,$r,$a)use($auth,$repo,$ok){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);return $ok($r,['items'=>$repo->rows('SELECT id,site_id,status,created_at FROM backups WHERE site_id=? ORDER BY id DESC',[$s['id']])]);});
        $app->post('/api/sites/{id}/backups',function($q,$r,$a)use($auth,$repo,$db,$ok){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);$content=json_encode(['site'=>$s['name'],'files'=>(int)self::scalar($db,'SELECT COUNT(*) FROM site_files WHERE site_id=?',[$s['id']])],JSON_THROW_ON_ERROR);$created=gmdate('Y-m-d\TH:i:s.u\Z');$db->prepare('INSERT INTO backups(site_id,status,content,created_at) VALUES(?,"ready",?,?)')->execute([$s['id'],$content,$created]);return $ok($r,self::fetch($db,'SELECT id,site_id,status,created_at FROM backups WHERE id=?',[(int)$db->lastInsertId()]),201);});
        $app->get('/api/backups/{id}/content',function($q,$r,$a)use($auth,$repo,$ok){$u=$auth->user($q,['customer']);$b=$repo->child('backups',(int)$a['id'],$u,'sites','site_id');if($b['status']!=='ready')throw new ApiException(409,'invalid_state','Backup is not ready.');return $ok($r,['backup_id'=>(int)$b['id'],'content'=>$b['content']]);});
        $app->post('/api/backups/{id}/restore',function($q,$r,$a)use($auth,$repo,$db,$ok){$u=$auth->user($q,['customer']);$b=$repo->child('backups',(int)$a['id'],$u,'sites','site_id');if($b['status']!=='ready')throw new ApiException(409,'invalid_state','Backup is not ready.');$db->prepare('INSERT INTO restore_jobs(backup_id,status,created_at) VALUES(?,"succeeded",?)')->execute([$b['id'],gmdate(DATE_ATOM)]);return $ok($r,self::fetch($db,'SELECT * FROM restore_jobs WHERE id=?',[(int)$db->lastInsertId()]));});

        // HOST-07
        $app->get('/api/domains/{id}/certificates',function($q,$r,$a)use($auth,$repo,$ok){$u=$auth->user($q,['customer']);$d=$repo->owned('domains',(int)$a['id'],$u);return $ok($r,['items'=>$repo->rows('SELECT * FROM certificates WHERE domain_id=? ORDER BY id',[$d['id']])]);});
        $app->post('/api/domains/{id}/certificates',function($q,$r,$a)use($auth,$repo,$db,$duplicate,$ok){$u=$auth->user($q,['customer']);$d=$repo->owned('domains',(int)$a['id'],$u);if($d['status']!=='active')throw new ApiException(409,'invalid_state','Domain must be active.');$duplicate(fn()=>$db->prepare('INSERT INTO certificates(domain_id,status,expires_at) VALUES(?,"active",?)')->execute([$d['id'],gmdate(DATE_ATOM,strtotime('+90 days'))]));return $ok($r,self::fetch($db,'SELECT * FROM certificates WHERE id=?',[(int)$db->lastInsertId()]),201);});
        $app->post('/api/certificates/{id}/renew',function($q,$r,$a)use($auth,$repo,$db,$ok){$u=$auth->user($q,['customer']);$c=$repo->child('certificates',(int)$a['id'],$u,'domains','domain_id');if($c['status']!=='active')throw new ApiException(409,'invalid_state','Only active certificates can renew.');$db->prepare('UPDATE certificates SET expires_at=? WHERE id=?')->execute([gmdate(DATE_ATOM,strtotime('+90 days')),$c['id']]);return $ok($r,$repo->child('certificates',(int)$c['id'],$u,'domains','domain_id'));});
        $app->delete('/api/certificates/{id}',function($q,$r,$a)use($auth,$repo,$db){$u=$auth->user($q,['customer']);$c=$repo->child('certificates',(int)$a['id'],$u,'domains','domain_id');$db->prepare('UPDATE certificates SET status="revoked" WHERE id=?')->execute([$c['id']]);return $r->withStatus(204);});

        // HOST-08
        $app->get('/api/sites/{id}/scheduled-tasks',function($q,$r,$a)use($auth,$repo,$ok){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);return $ok($r,['items'=>$repo->rows('SELECT * FROM scheduled_tasks WHERE site_id=? ORDER BY id',[$s['id']])]);});
        $app->post('/api/sites/{id}/scheduled-tasks',function($q,$r,$a)use($auth,$repo,$db,$duplicate,$ok){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);$d=Http::body($q);Http::requireFields($d,['command','schedule']);if(!in_array($d['command'],['backup','cache-clear','health-check'],true))throw new ApiException(422,'validation_error','Command is not allowed.',['command'=>'not allow-listed']);if(!preg_match('/^(\S+\s+){4}\S+$/',$d['schedule']))throw new ApiException(422,'validation_error','Invalid schedule.',['schedule'=>'five cron fields required']);$duplicate(fn()=>$db->prepare('INSERT INTO scheduled_tasks(site_id,command,schedule,enabled) VALUES(?,?,?,?)')->execute([$s['id'],$d['command'],$d['schedule'],isset($d['enabled'])?(int)(bool)$d['enabled']:1]));return $ok($r,self::fetch($db,'SELECT * FROM scheduled_tasks WHERE id=?',[(int)$db->lastInsertId()]),201);});
        $app->patch('/api/scheduled-tasks/{id}',function($q,$r,$a)use($auth,$repo,$db,$version,$ok){$u=$auth->user($q,['customer']);$t=$repo->child('scheduled_tasks',(int)$a['id'],$u,'sites','site_id');$d=Http::body($q);$version($d,$t);if(!array_key_exists('enabled',$d))throw new ApiException(422,'validation_error','Invalid request data.',['enabled'=>'required']);$db->prepare('UPDATE scheduled_tasks SET enabled=?,version=version+1 WHERE id=?')->execute([(int)(bool)$d['enabled'],$t['id']]);return $ok($r,$repo->child('scheduled_tasks',(int)$t['id'],$u,'sites','site_id'));});
        $app->delete('/api/scheduled-tasks/{id}',function($q,$r,$a)use($auth,$repo,$db){$u=$auth->user($q,['customer']);$t=$repo->child('scheduled_tasks',(int)$a['id'],$u,'sites','site_id');$db->prepare('DELETE FROM scheduled_tasks WHERE id=?')->execute([$t['id']]);return $r->withStatus(204);});

        // HOST-09
        $app->get('/api/sites/{id}/metrics',function($q,$r,$a)use($auth,$repo,$ok){$u=$auth->user($q,['customer','operator']);$s=$repo->site((int)$a['id'],$u,true);$p=$q->getQueryParams();foreach(['from','to','interval'] as $f)if(!isset($p[$f])||$p[$f]==='')throw new ApiException(422,'validation_error','Metric range required.',[$f=>'required']);if(!in_array($p['interval'],['hour','day'],true))throw new ApiException(422,'validation_error','Invalid interval.',['interval'=>'hour or day']);if(strtotime($p['from'])===false||strtotime($p['to'])===false||$p['from']>$p['to'])throw new ApiException(422,'validation_error','Invalid date range.',['from'=>'must precede to']);return $ok($r,['site_id'=>(int)$s['id'],'interval'=>$p['interval'],'items'=>$repo->rows('SELECT sampled_at,cpu,memory_mb,storage_mb,requests FROM metric_samples WHERE site_id=? AND sampled_at>=? AND sampled_at<=? ORDER BY sampled_at',[$s['id'],$p['from'],$p['to']])]);});

        // HOST-10
        $app->get('/api/support-tickets',function($q,$r)use($auth,$repo,$ok){$u=$auth->user($q,['customer','operator']);[$l,$o]=Http::page($q);$args=[$l,$o];$where='';if($u['role']==='customer'){$a=$repo->account($u);$where=' WHERE account_id=?';$args=[$a['id'],$l,$o];}return $ok($r,['items'=>$repo->rows('SELECT * FROM support_tickets'.$where.' ORDER BY id DESC LIMIT ? OFFSET ?',$args)]);});
        $app->post('/api/support-tickets',function($q,$r)use($auth,$repo,$db,$ok){$u=$auth->user($q,['customer']);$a=$repo->account($u);$d=Http::body($q);Http::requireFields($d,['subject','body']);$db->beginTransaction();$db->prepare('INSERT INTO support_tickets(account_id,subject,status,created_at) VALUES(?,?,"open",?)')->execute([$a['id'],$d['subject'],gmdate(DATE_ATOM)]);$id=(int)$db->lastInsertId();$db->prepare('INSERT INTO ticket_replies(ticket_id,user_id,body,created_at) VALUES(?,?,?,?)')->execute([$id,$u['id'],$d['body'],gmdate(DATE_ATOM)]);$db->commit();return $ok($r,self::fetch($db,'SELECT * FROM support_tickets WHERE id=?',[$id]),201);});
        $app->get('/api/support-tickets/{id}',function($q,$r,$a)use($auth,$repo,$db,$ok){$u=$auth->user($q,['customer','operator']);$t=self::ticket($db,$repo,$u,(int)$a['id']);return $ok($r,['ticket'=>$t,'replies'=>$repo->rows('SELECT r.id,r.body,r.created_at,u.email,u.role FROM ticket_replies r JOIN users u ON u.id=r.user_id WHERE ticket_id=? ORDER BY r.id',[$t['id']])]);});
        $app->post('/api/support-tickets/{id}/replies',function($q,$r,$a)use($auth,$repo,$db,$ok){$u=$auth->user($q,['customer','operator']);$t=self::ticket($db,$repo,$u,(int)$a['id']);if($t['status']==='closed')throw new ApiException(409,'invalid_state','Ticket is closed.');$d=Http::body($q);Http::requireFields($d,['body']);$db->prepare('INSERT INTO ticket_replies(ticket_id,user_id,body,created_at) VALUES(?,?,?,?)')->execute([$t['id'],$u['id'],$d['body'],gmdate(DATE_ATOM)]);return $ok($r,['id'=>(int)$db->lastInsertId(),'ticket_id'=>(int)$t['id'],'body'=>$d['body']],201);});
        $app->post('/api/support-tickets/{id}/close',function($q,$r,$a)use($auth,$repo,$db,$ok){$u=$auth->user($q,['customer','operator']);$t=self::ticket($db,$repo,$u,(int)$a['id']);if($t['status']==='closed')throw new ApiException(409,'invalid_state','Ticket is already closed.');$db->prepare('UPDATE support_tickets SET status="closed" WHERE id=?')->execute([$t['id']]);return $ok($r,self::fetch($db,'SELECT * FROM support_tickets WHERE id=?',[$t['id']]));});

        // HOST-11
        $app->get('/api/sites/{id}/audit-events',function($q,$r,$a)use($auth,$repo,$ok){$u=$auth->user($q,['customer']);$s=$repo->site((int)$a['id'],$u);[$l,$o]=Http::page($q);return $ok($r,['items'=>$repo->rows('SELECT * FROM audit_events WHERE site_id=? ORDER BY id DESC LIMIT ? OFFSET ?',[$s['id'],$l,$o])]);});
        $app->get('/api/admin/audit-events',function($q,$r)use($auth,$repo,$ok){$auth->user($q,['admin']);[$l,$o]=Http::page($q);return $ok($r,['items'=>$repo->rows('SELECT * FROM audit_events ORDER BY id DESC LIMIT ? OFFSET ?',[$l,$o])]);});

        // HOST-12
        $app->get('/api/admin/accounts',function($q,$r)use($auth,$repo,$ok){$auth->user($q,['admin']);[$l,$o]=Http::page($q);return $ok($r,['items'=>$repo->rows('SELECT a.*,u.email,p.name plan_name FROM accounts a JOIN users u ON u.id=a.user_id JOIN plans p ON p.id=a.plan_id ORDER BY a.id LIMIT ? OFFSET ?',[$l,$o])]);});
        $app->patch('/api/admin/accounts/{id}',function($q,$r,$a)use($auth,$db,$one,$version,$ok){$auth->user($q,['admin']);$row=$one('SELECT * FROM accounts WHERE id=?',[(int)$a['id']]);$d=Http::body($q);$version($d,$row);$status=$d['status']??$row['status'];$quota=(int)($d['quota_mb']??$row['quota_mb']);if(!in_array($status,['active','suspended'],true)||$quota<100)throw new ApiException(422,'validation_error','Invalid account update.',['status'=>'active or suspended','quota_mb'=>'minimum 100']);$db->prepare('UPDATE accounts SET status=?,quota_mb=?,version=version+1 WHERE id=?')->execute([$status,$quota,$row['id']]);return $ok($r,$one('SELECT * FROM accounts WHERE id=?',[$row['id']]));});
        $app->get('/api/admin/plans',function($q,$r)use($auth,$repo,$ok){$auth->user($q,['admin']);return $ok($r,['items'=>$repo->rows('SELECT * FROM plans ORDER BY id')]);});
        $app->post('/api/admin/plans',function($q,$r)use($auth,$db,$duplicate,$ok){$auth->user($q,['admin']);$d=Http::body($q);Http::requireFields($d,['name']);foreach(['storage_mb','site_limit','price_cents'] as $f)if(!isset($d[$f])||(int)$d[$f]<0)throw new ApiException(422,'validation_error','Invalid plan.',[$f=>'non-negative integer required']);$duplicate(fn()=>$db->prepare('INSERT INTO plans(name,storage_mb,site_limit,price_cents) VALUES(?,?,?,?)')->execute([$d['name'],(int)$d['storage_mb'],(int)$d['site_limit'],(int)$d['price_cents']]));return $ok($r,self::fetch($db,'SELECT * FROM plans WHERE id=?',[(int)$db->lastInsertId()]),201);});
        $app->patch('/api/admin/maintenance',function($q,$r)use($auth,$db,$ok){$auth->user($q,['admin']);$d=Http::body($q);if(!isset($d['enabled'])||!is_bool($d['enabled']))throw new ApiException(422,'validation_error','Invalid maintenance setting.',['enabled'=>'boolean required']);$value=$d['enabled']?'on':'off';$db->prepare('UPDATE settings SET value=? WHERE key="maintenance"')->execute([$value]);return $ok($r,['maintenance'=>$value]);});
    }

    private static function fetch(PDO $db,string $sql,array $args): array { $s=$db->prepare($sql);$s->execute($args);$r=$s->fetch();if(!$r)throw new ApiException(404,'not_found','Resource not found.');return $r; }
    private static function scalar(PDO $db,string $sql,array $args): mixed { $s=$db->prepare($sql);$s->execute($args);return $s->fetchColumn(); }
    private static function ticket(PDO $db,HostingRepository $repo,array $u,int $id): array { if($u['role']==='operator')return self::fetch($db,'SELECT * FROM support_tickets WHERE id=?',[$id]);$a=$repo->account($u);return self::fetch($db,'SELECT * FROM support_tickets WHERE id=? AND account_id=?',[$id,$a['id']]); }
}
