<?php
declare(strict_types=1);

namespace App;

use PDO;
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\App;

final class AssessmentRoutes
{
    use RouteSupport;

    public static function register(App $app,PDO $db,Auth $auth,array $config):void
    {
        $access=new Access($db);
        $app->post('/api/courses/{courseId}/quizzes',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor']);$cid=(int)$a['courseId'];$access->requireInstructor($u,$cid);$access->writableCourse($cid);$d=self::body($r);self::required($d,['title','timeLimitMinutes','attemptLimit','maxScore','questions']);if(!is_array($d['questions'])||!count($d['questions']))throw new ApiException(422,'validation_failed','At least one question is required.',['questions'=>'Required.']);$db->beginTransaction();$db->prepare('INSERT INTO quizzes(course_id,title,time_limit_minutes,attempt_limit,max_score) VALUES(?,?,?,?,?)')->execute([$cid,trim($d['title']),(int)$d['timeLimitMinutes'],(int)$d['attemptLimit'],(float)$d['maxScore']]);$id=(int)$db->lastInsertId();$stmt=$db->prepare('INSERT INTO questions(quiz_id,prompt,choices_json,correct_answer,points,position) VALUES(?,?,?,?,?,?)');foreach(array_values($d['questions']) as $i=>$q){self::required($q,['prompt','choices','correctAnswer','points']);if(!is_array($q['choices'])||!in_array((string)$q['correctAnswer'],array_map('strval',$q['choices']),true)){$db->rollBack();throw new ApiException(422,'validation_failed','Every answer must match one choice.',['questions'=>'Invalid answer key.']);}$stmt->execute([$id,trim($q['prompt']),json_encode(array_values($q['choices'])),(string)$q['correctAnswer'],(float)$q['points'],$i+1]);}$db->commit();return Http::json($s,['quiz'=>self::quiz($db,$id,true)],201);});
        $app->patch('/api/quizzes/{quizId}',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor']);$q=self::one($db,'SELECT * FROM quizzes WHERE id=?',[(int)$a['quizId']],'quiz_not_found');$access->requireInstructor($u,(int)$q['course_id']);$access->writableCourse((int)$q['course_id']);if($q['status']!=='draft')throw new ApiException(409,'quiz_published','Published quiz settings are immutable.');$d=self::body($r);if(isset($d['version'])&&(int)$d['version']!==(int)$q['version'])throw new ApiException(409,'stale_version','Quiz was changed by another request.');$map=['title'=>'title','timeLimitMinutes'=>'time_limit_minutes','attemptLimit'=>'attempt_limit','maxScore'=>'max_score'];$sets=[];$p=[];foreach($map as $i=>$c)if(array_key_exists($i,$d)){$sets[]="$c=?";$p[]=$d[$i];}if(!$sets)throw new ApiException(422,'validation_failed','No supported fields supplied.');$sets[]='version=version+1';$p[]=$q['id'];$db->prepare('UPDATE quizzes SET '.implode(',',$sets).' WHERE id=?')->execute($p);return Http::json($s,['quiz'=>self::quiz($db,(int)$q['id'],true)]);});
        $app->post('/api/quizzes/{quizId}/publish',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor']);$q=self::one($db,'SELECT * FROM quizzes WHERE id=?',[(int)$a['quizId']],'quiz_not_found');$access->requireInstructor($u,(int)$q['course_id']);$access->writableCourse((int)$q['course_id']);if($q['status']!=='draft')throw new ApiException(409,'invalid_quiz_state','Quiz is already published.');$count=(int)self::one($db,'SELECT COUNT(*) n FROM questions WHERE quiz_id=?',[$q['id']])['n'];if(!$count)throw new ApiException(409,'quiz_has_no_questions','Quiz must contain questions.');$db->prepare("UPDATE quizzes SET status='published',version=version+1 WHERE id=?")->execute([$q['id']]);return Http::json($s,['quiz'=>self::quiz($db,(int)$q['id'],true)]);});
        $app->post('/api/quizzes/{quizId}/attempts',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student']);$q=self::one($db,'SELECT * FROM quizzes WHERE id=?',[(int)$a['quizId']],'quiz_not_found');$access->requireMember($u,(int)$q['course_id']);if($q['status']!=='published')throw new ApiException(404,'quiz_not_found','Quiz not found.');$count=(int)self::one($db,'SELECT COUNT(*) n FROM quiz_attempts WHERE quiz_id=? AND student_id=?',[$q['id'],$u['id']])['n'];if($count>=(int)$q['attempt_limit'])throw new ApiException(409,'attempt_limit_reached','No attempts remain.');$current=self::all($db,"SELECT * FROM quiz_attempts WHERE quiz_id=? AND student_id=? AND status='in_progress' ORDER BY id DESC LIMIT 1",[$q['id'],$u['id']]);if($current)return Http::json($s,['attempt'=>$current[0],'quiz'=>self::quiz($db,(int)$q['id'],false)]);$db->prepare('INSERT INTO quiz_attempts(quiz_id,student_id) VALUES(?,?)')->execute([$q['id'],$u['id']]);$id=(int)$db->lastInsertId();return Http::json($s,['attempt'=>self::one($db,'SELECT * FROM quiz_attempts WHERE id=?',[$id]),'quiz'=>self::quiz($db,(int)$q['id'],false)],201);});
        $app->put('/api/quiz-attempts/{attemptId}/answers',function(Request $r,Response $s,array $a)use($auth,$db){$u=$auth->requireUser($r,['student']);$at=self::attempt($db,(int)$a['attemptId'],$u);self::openAttempt($at);$d=self::body($r);self::required($d,['answers']);if(!is_array($d['answers']))throw new ApiException(422,'validation_failed','Answers must be keyed by question ID.',['answers'=>'Expected an object.']);$valid=self::all($db,'SELECT id FROM questions WHERE quiz_id=?',[$at['quiz_id']]);$ids=array_map(fn($x)=>(int)$x['id'],$valid);$db->beginTransaction();$stmt=$db->prepare('INSERT INTO quiz_answers(attempt_id,question_id,answer) VALUES(?,?,?) ON CONFLICT(attempt_id,question_id) DO UPDATE SET answer=excluded.answer');foreach($d['answers'] as $qid=>$answer){if(!in_array((int)$qid,$ids,true)){$db->rollBack();throw new ApiException(422,'validation_failed','Answer references an unknown question.',['answers'=>'Unknown question ID.']);}$stmt->execute([$at['id'],(int)$qid,(string)$answer]);}$db->commit();return Http::json($s,['answers'=>self::all($db,'SELECT question_id,answer FROM quiz_answers WHERE attempt_id=? ORDER BY question_id',[$at['id']])]);});
        $app->post('/api/quiz-attempts/{attemptId}/submit',function(Request $r,Response $s,array $a)use($auth,$db){$u=$auth->requireUser($r,['student']);$at=self::attempt($db,(int)$a['attemptId'],$u);self::openAttempt($at);$rows=self::all($db,'SELECT q.id,q.correct_answer,q.points,a.answer FROM questions q LEFT JOIN quiz_answers a ON a.question_id=q.id AND a.attempt_id=? WHERE q.quiz_id=?',[$at['id'],$at['quiz_id']]);$score=0.0;foreach($rows as $row)if($row['answer']!==null&&hash_equals((string)$row['correct_answer'],(string)$row['answer']))$score+=(float)$row['points'];$db->prepare("UPDATE quiz_attempts SET status='submitted',submitted_at=datetime('now'),score=?,released=1 WHERE id=?")->execute([$score,$at['id']]);return Http::json($s,['result'=>self::result($db,(int)$at['id'])]);});
        $app->get('/api/quiz-attempts/{attemptId}/result',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student','instructor']);$at=self::one($db,'SELECT qa.*,q.course_id FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id WHERE qa.id=?',[(int)$a['attemptId']],'attempt_not_found');if($u['role']==='student'&&(int)$at['student_id']!==(int)$u['id'])throw new ApiException(403,'attempt_access_denied','This attempt belongs to another student.');if($u['role']==='instructor')$access->requireInstructor($u,(int)$at['course_id']);if($at['status']!=='submitted')throw new ApiException(409,'attempt_in_progress','Submit the attempt before viewing results.');if($u['role']==='student'&&!(int)$at['released'])throw new ApiException(404,'result_not_released','Result is not released.');return Http::json($s,['result'=>self::result($db,(int)$at['id'])]);});

        self::grades($app,$db,$auth,$access); self::reports($app,$db,$auth,$access);
    }

    private static function quiz(PDO $db,int $id,bool $keys):array {$q=self::one($db,'SELECT * FROM quizzes WHERE id=?',[$id],'quiz_not_found');$cols=$keys?'id,prompt,choices_json,correct_answer,points,position':'id,prompt,choices_json,points,position';$q['questions']=self::all($db,"SELECT $cols FROM questions WHERE quiz_id=? ORDER BY position,id",[$id]);foreach($q['questions'] as &$x){$x['choices']=json_decode($x['choices_json'],true);unset($x['choices_json']);}return $q;}
    private static function attempt(PDO $db,int $id,array $u):array {$at=self::one($db,'SELECT qa.*,q.time_limit_minutes,q.course_id FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id WHERE qa.id=?',[$id],'attempt_not_found');if((int)$at['student_id']!==(int)$u['id'])throw new ApiException(403,'attempt_access_denied','This attempt belongs to another student.');return $at;}
    private static function openAttempt(array $at):void {if($at['status']!=='in_progress')throw new ApiException(409,'attempt_submitted','Submitted attempts cannot change.');if(time()>strtotime($at['started_at'])+(int)$at['time_limit_minutes']*60)throw new ApiException(409,'attempt_expired','The attempt time limit has expired.');}
    private static function result(PDO $db,int $id):array {return self::one($db,'SELECT qa.id,qa.quiz_id,qa.student_id,qa.started_at,qa.submitted_at,qa.score,qa.feedback,qa.released,q.max_score FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id WHERE qa.id=?',[$id]);}

    private static function grades(App $app,PDO $db,Auth $auth,Access $access):void {
        $app->get('/api/courses/{courseId}/gradebook/me',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student']);$cid=(int)$a['courseId'];$access->requireMember($u,$cid);return Http::json($s,['assignments'=>self::all($db,'SELECT a.id assignment_id,a.title,a.max_score,s.score,s.feedback,s.submitted_at FROM assignments a LEFT JOIN submissions s ON s.assignment_id=a.id AND s.student_id=? AND s.is_current=1 AND s.released=1 WHERE a.course_id=? ORDER BY a.id',[$u['id'],$cid]),'quizzes'=>self::all($db,"SELECT q.id quiz_id,q.title,q.max_score,qa.score,qa.feedback,qa.submitted_at FROM quizzes q LEFT JOIN quiz_attempts qa ON qa.quiz_id=q.id AND qa.student_id=? AND qa.status='submitted' AND qa.released=1 WHERE q.course_id=? ORDER BY q.id,qa.id",[$u['id'],$cid])]);});
        $app->get('/api/courses/{courseId}/gradebook',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor']);$cid=(int)$a['courseId'];$access->requireInstructor($u,$cid);return Http::json($s,['students'=>self::gradeRows($db,$cid)]);});
        $app->put('/api/submissions/{submissionId}/grade',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor']);$x=self::one($db,'SELECT s.*,a.course_id,a.max_score FROM submissions s JOIN assignments a ON a.id=s.assignment_id WHERE s.id=?',[(int)$a['submissionId']],'submission_not_found');$access->requireInstructor($u,(int)$x['course_id']);$d=self::body($r);self::required($d,['score']);$score=(float)$d['score'];if($score<0||$score>(float)$x['max_score'])throw new ApiException(422,'validation_failed','Score is outside the allowed range.',['score'=>'Use 0 through '.$x['max_score'].'.']);$db->prepare('UPDATE submissions SET score=?,feedback=?,released=? WHERE id=?')->execute([$score,trim((string)($d['feedback']??'')),(int)(bool)($d['released']??false),$x['id']]);return Http::json($s,['submission'=>self::one($db,'SELECT * FROM submissions WHERE id=?',[$x['id']])]);});
        $app->put('/api/quiz-attempts/{attemptId}/grade',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor']);$x=self::one($db,'SELECT qa.*,q.course_id,q.max_score FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id WHERE qa.id=?',[(int)$a['attemptId']],'attempt_not_found');$access->requireInstructor($u,(int)$x['course_id']);if($x['status']!=='submitted')throw new ApiException(409,'attempt_in_progress','Only submitted attempts can be graded.');$d=self::body($r);self::required($d,['score']);$score=(float)$d['score'];if($score<0||$score>(float)$x['max_score'])throw new ApiException(422,'validation_failed','Score is outside the allowed range.',['score'=>'Use 0 through '.$x['max_score'].'.']);$db->prepare('UPDATE quiz_attempts SET score=?,feedback=?,released=? WHERE id=?')->execute([$score,trim((string)($d['feedback']??'')),(int)(bool)($d['released']??false),$x['id']]);return Http::json($s,['attempt'=>self::result($db,(int)$x['id'])]);});
        $app->get('/api/courses/{courseId}/gradebook/export',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor','admin']);$cid=(int)$a['courseId'];$access->requireInstructor($u,$cid);if(($r->getQueryParams()['format']??'csv')!=='csv')throw new ApiException(422,'validation_failed','Only CSV export is supported.',['format'=>'Use csv.']);$rows=self::gradeRows($db,$cid);$stream=fopen('php://temp','r+');fputcsv($stream,['student_id','display_name','email','assignment_average','quiz_average']);foreach($rows as $x)fputcsv($stream,[$x['student_id'],$x['display_name'],$x['email'],$x['assignment_average'],$x['quiz_average']]);rewind($stream);$s->getBody()->write((string)stream_get_contents($stream));return $s->withHeader('Content-Type','text/csv; charset=utf-8')->withHeader('Content-Disposition','attachment; filename="course-'.$cid.'-gradebook.csv"');});
    }
    private static function gradeRows(PDO $db,int $cid):array {return self::all($db,"SELECT u.id student_id,u.display_name,u.email,ROUND(AVG(CASE WHEN s.released=1 THEN s.score END),2) assignment_average,(SELECT ROUND(AVG(qa.score),2) FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id WHERE q.course_id=? AND qa.student_id=u.id AND qa.status='submitted') quiz_average FROM enrollments e JOIN users u ON u.id=e.student_id LEFT JOIN assignments a ON a.course_id=e.course_id LEFT JOIN submissions s ON s.assignment_id=a.id AND s.student_id=u.id AND s.is_current=1 WHERE e.course_id=? AND e.status IN ('active','completed') GROUP BY u.id,u.display_name,u.email ORDER BY u.display_name,u.id",[$cid,$cid]);}

    private static function reports(App $app,PDO $db,Auth $auth,Access $access):void {
        $app->get('/api/courses/{courseId}/reports/overview',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor','admin']);$cid=(int)$a['courseId'];$access->requireInstructor($u,$cid);$c=$access->course($cid);$counts=self::one($db,"SELECT (SELECT COUNT(*) FROM enrollments WHERE course_id=? AND status='active') active_enrollments,(SELECT COUNT(*) FROM enrollments WHERE course_id=? AND status='completed') completed_enrollments,(SELECT COUNT(*) FROM submissions s JOIN assignments a ON a.id=s.assignment_id WHERE a.course_id=? AND s.is_current=1) current_submissions,(SELECT COUNT(*) FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id WHERE q.course_id=? AND qa.status='submitted') submitted_quiz_attempts",[$cid,$cid,$cid,$cid]);return Http::json($s,['course'=>$c,'overview'=>$counts]);});
        $app->get('/api/admin/reports/courses',function(Request $r,Response $s)use($auth,$db){$auth->requireUser($r,['admin']);$q=$r->getQueryParams();[$limit,$offset,$page]=self::page($r);$where=[];$p=[];if(trim($q['status']??'')!==''){$where[]='c.status=?';$p[]=trim($q['status']);}if(trim($q['from']??'')!==''){$where[]='c.created_at>=?';$p[]=trim($q['from']);}if(trim($q['to']??'')!==''){$where[]='c.created_at<=?';$p[]=trim($q['to']);}$sql="SELECT c.id,c.title,c.status,c.created_at,COUNT(DISTINCT CASE WHEN e.status='active' THEN e.id END) active_enrollments,COUNT(DISTINCT a.id) assignments,COUNT(DISTINCT qz.id) quizzes FROM courses c LEFT JOIN enrollments e ON e.course_id=c.id LEFT JOIN assignments a ON a.course_id=c.id LEFT JOIN quizzes qz ON qz.course_id=c.id".($where?' WHERE '.implode(' AND ',$where):'').' GROUP BY c.id,c.title,c.status,c.created_at ORDER BY c.created_at DESC,c.id DESC LIMIT ? OFFSET ?';$p[]=$limit;$p[]=$offset;return Http::json($s,['items'=>self::all($db,$sql,$p),'page'=>$page,'limit'=>$limit]);});
    }
}
