<?php
declare(strict_types=1);

namespace App;

use PDO;
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\App;

final class CourseRoutes
{
    use RouteSupport;

    public static function register(App $app, PDO $db, Auth $auth, array $config): void
    {
        $access=new Access($db);
        $app->get('/api/courses',function(Request $r,Response $s)use($db,$auth){$u=$auth->current($r);$q=$r->getQueryParams();[$limit,$offset,$page]=self::page($r);$where=[];$p=[];if(!$u||$u['role']==='student')$where[]="c.status='published'";elseif($u['role']==='instructor'){$where[]="(c.status='published' OR EXISTS(SELECT 1 FROM course_instructors mine WHERE mine.course_id=c.id AND mine.user_id=?))";$p[]=$u['id'];}if(trim($q['q']??'')!==''){$where[]='(c.title LIKE ? OR c.description LIKE ?)';$term='%'.trim($q['q']).'%';$p[]=$term;$p[]=$term;}if(trim($q['category']??'')!==''){$where[]='cat.slug=?';$p[]=trim($q['category']);}if(isset($q['instructorId'])&&$q['instructorId']!==''){$where[]='EXISTS(SELECT 1 FROM course_instructors ci WHERE ci.course_id=c.id AND ci.user_id=?)';$p[]=(int)$q['instructorId'];}if(isset($q['enrollmentStatus'])&&$q['enrollmentStatus']!==''){if(!$u||$u['role']!=='student')throw new ApiException(422,'validation_failed','Enrollment status filter requires a student session.',['enrollmentStatus'=>'Sign in as a student.']);if($q['enrollmentStatus']==='enrolled')$where[]="EXISTS(SELECT 1 FROM enrollments e WHERE e.course_id=c.id AND e.student_id=? AND e.status='active')";elseif($q['enrollmentStatus']==='available')$where[]="NOT EXISTS(SELECT 1 FROM enrollments e WHERE e.course_id=c.id AND e.student_id=? AND e.status='active')";else throw new ApiException(422,'validation_failed','Unknown enrollment status.',['enrollmentStatus'=>'Use enrolled or available.']);$p[]=$u['id'];}$sql='SELECT c.id,c.title,c.description,c.status,c.capacity,c.version,cat.name category,cat.slug categorySlug,(SELECT COUNT(*) FROM enrollments e WHERE e.course_id=c.id AND e.status=\'active\') enrollmentCount FROM courses c JOIN categories cat ON cat.id=c.category_id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY c.title,c.id LIMIT ? OFFSET ?';$p[]=$limit;$p[]=$offset;return Http::json($s,['items'=>self::all($db,$sql,$p),'page'=>$page,'limit'=>$limit]);});
        $app->get('/api/courses/{courseId}',function(Request $r,Response $s,array $a)use($access,$auth,$db){$c=$access->course((int)$a['courseId']);$u=$auth->current($r);if($c['status']!=='published'&&(!$u||($u['role']!=='admin'&&!$access->isInstructor((int)$c['id'],(int)$u['id']))))throw new ApiException(404,'course_not_found','Course not found.');$c['instructors']=self::all($db,'SELECT u.id,u.display_name FROM course_instructors ci JOIN users u ON u.id=ci.user_id WHERE ci.course_id=? ORDER BY u.display_name',[$c['id']]);$c['enrollmentCount']=(int)self::one($db,"SELECT COUNT(*) count FROM enrollments WHERE course_id=? AND status='active'",[$c['id']])['count'];return Http::json($s,['course'=>$c]);});
        $app->post('/api/courses/{courseId}/enrollments',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student']);$c=$access->course((int)$a['courseId']);if($c['status']!=='published')throw new ApiException(409,'course_not_open','Course is not published.');$d=self::body($r);if($c['enrollment_key_hash']&&!password_verify((string)($d['enrollmentKey']??''),$c['enrollment_key_hash']))throw new ApiException(403,'invalid_enrollment_key','The enrollment key is incorrect.');$now=time();if($c['enrollment_opens_at']&&strtotime($c['enrollment_opens_at'])>$now||$c['enrollment_closes_at']&&strtotime($c['enrollment_closes_at'])<$now)throw new ApiException(409,'enrollment_closed','The enrollment window is closed.');$count=(int)self::one($db,"SELECT COUNT(*) n FROM enrollments WHERE course_id=? AND status='active'",[$c['id']])['n'];if($count>=(int)$c['capacity'])throw new ApiException(409,'course_full','Course capacity has been reached.');$existing=self::all($db,'SELECT * FROM enrollments WHERE course_id=? AND student_id=?',[$c['id'],$u['id']]);if($existing&&$existing[0]['status']==='active')throw new ApiException(409,'already_enrolled','Student is already enrolled.');if($existing){$db->prepare("UPDATE enrollments SET status='active',enrolled_at=datetime('now') WHERE id=?")->execute([$existing[0]['id']]);$id=$existing[0]['id'];}else{$db->prepare('INSERT INTO enrollments(course_id,student_id) VALUES(?,?)')->execute([$c['id'],$u['id']]);$id=(int)$db->lastInsertId();}return Http::json($s,['enrollment'=>self::one($db,'SELECT * FROM enrollments WHERE id=?',[$id])],201);});
        $app->delete('/api/courses/{courseId}/enrollments/me',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student']);$access->course((int)$a['courseId']);$stmt=$db->prepare("UPDATE enrollments SET status='withdrawn' WHERE course_id=? AND student_id=? AND status='active'");$stmt->execute([(int)$a['courseId'],$u['id']]);if(!$stmt->rowCount())throw new ApiException(404,'enrollment_not_found','Active enrollment not found.');return $s->withStatus(204);});
        $app->get('/api/courses/{courseId}/enrollments',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor','admin']);$access->requireInstructor($u,(int)$a['courseId']);[$limit,$offset,$page]=self::page($r);return Http::json($s,['items'=>self::all($db,'SELECT e.id,e.status,e.enrolled_at,u.id student_id,u.email,u.display_name FROM enrollments e JOIN users u ON u.id=e.student_id WHERE e.course_id=? ORDER BY u.display_name,u.id LIMIT ? OFFSET ?',[(int)$a['courseId'],$limit,$offset]),'page'=>$page,'limit'=>$limit]);});

        $app->get('/api/courses/{courseId}/materials',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student','instructor']);$cid=(int)$a['courseId'];$access->requireMember($u,$cid);$show=$u['role']==='instructor'&&$access->isInstructor($cid,(int)$u['id']);$sql='SELECT id,course_id,title,description,visibility,external_url,file_id,created_at FROM materials WHERE course_id=?'.($show?'':" AND visibility='visible'").' ORDER BY created_at,id';return Http::json($s,['items'=>self::all($db,$sql,[$cid])]);});
        $app->post('/api/courses/{courseId}/materials',function(Request $r,Response $s,array $a)use($auth,$db,$access,$config){$u=$auth->requireUser($r,['instructor']);$cid=(int)$a['courseId'];$access->requireInstructor($u,$cid);$access->writableCourse($cid);$d=self::body($r);self::required($d,['title']);$external=trim((string)($d['externalUrl']??''))?:null;$fileId=null;$uploads=$r->getUploadedFiles();if(isset($uploads['file'])&&$uploads['file']->getError()===UPLOAD_ERR_OK){$f=$uploads['file'];if($f->getSize()>$config['maxUpload'])throw new ApiException(422,'validation_failed','File is too large.',['file'=>'Upload is above configured maximum.']);$dir=str_starts_with($config['uploadDir'],'/')?$config['uploadDir']:dirname(__DIR__).'/'.$config['uploadDir'];if(!is_dir($dir))mkdir($dir,0775,true);$name=bin2hex(random_bytes(16));$f->moveTo($dir.'/'.$name);$db->prepare('INSERT INTO stored_files(original_name,stored_name,mime_type,size_bytes) VALUES(?,?,?,?)')->execute([$f->getClientFilename()?:'upload',$name,$f->getClientMediaType()?:'application/octet-stream',$f->getSize()]);$fileId=(int)$db->lastInsertId();}if(!$external&&!$fileId)throw new ApiException(422,'validation_failed','Provide a file or external URL.',['externalUrl'=>'Required when no file is uploaded.']);$visibility=($d['visibility']??'visible')==='hidden'?'hidden':'visible';$db->prepare('INSERT INTO materials(course_id,title,description,visibility,external_url,file_id) VALUES(?,?,?,?,?,?)')->execute([$cid,trim($d['title']),trim((string)($d['description']??'')),$visibility,$external,$fileId]);$id=(int)$db->lastInsertId();return Http::json($s,['material'=>self::one($db,'SELECT * FROM materials WHERE id=?',[$id])],201);});
        $app->patch('/api/materials/{materialId}',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor']);$m=self::one($db,'SELECT * FROM materials WHERE id=?',[(int)$a['materialId']],'material_not_found');$access->requireInstructor($u,(int)$m['course_id']);$access->writableCourse((int)$m['course_id']);$d=self::body($r);$map=['title'=>'title','description'=>'description','visibility'=>'visibility','externalUrl'=>'external_url'];$sets=[];$p=[];foreach($map as $in=>$col)if(array_key_exists($in,$d)){$sets[]="$col=?";$p[]=$d[$in];}if(!$sets)throw new ApiException(422,'validation_failed','No supported fields supplied.');$p[]=$m['id'];$db->prepare('UPDATE materials SET '.implode(',',$sets).' WHERE id=?')->execute($p);return Http::json($s,['material'=>self::one($db,'SELECT * FROM materials WHERE id=?',[$m['id']])]);});
        $app->get('/api/materials/{materialId}/content',function(Request $r,Response $s,array $a)use($auth,$db,$access,$config){$u=$auth->requireUser($r,['student','instructor']);$m=self::one($db,'SELECT * FROM materials WHERE id=?',[(int)$a['materialId']],'material_not_found');$access->requireMember($u,(int)$m['course_id']);if($m['visibility']==='hidden'&&!$access->isInstructor((int)$m['course_id'],(int)$u['id']))throw new ApiException(404,'material_not_found','Material not found.');if($m['external_url'])return $s->withHeader('Location',$m['external_url'])->withStatus(302);$f=self::one($db,'SELECT * FROM stored_files WHERE id=?',[$m['file_id']]);$path=(str_starts_with($config['uploadDir'],'/')?$config['uploadDir']:dirname(__DIR__).'/'.$config['uploadDir']).'/'.$f['stored_name'];if(!is_file($path))throw new ApiException(404,'content_not_found','Material content is unavailable.');$s->getBody()->write((string)file_get_contents($path));return $s->withHeader('Content-Type',$f['mime_type'])->withHeader('Content-Disposition','attachment; filename="'.str_replace('"','',$f['original_name']).'"');});
        $app->delete('/api/materials/{materialId}',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor']);$m=self::one($db,'SELECT * FROM materials WHERE id=?',[(int)$a['materialId']],'material_not_found');$access->requireInstructor($u,(int)$m['course_id']);$access->writableCourse((int)$m['course_id']);$db->prepare('DELETE FROM materials WHERE id=?')->execute([$m['id']]);return $s->withStatus(204);});

        self::announcements($app,$db,$auth,$access); self::discussions($app,$db,$auth,$access); self::assignments($app,$db,$auth,$access,$config); self::administration($app,$db,$auth,$access);
    }

    private static function announcements(App $app,PDO $db,Auth $auth,Access $access):void {
        $app->get('/api/courses/{courseId}/announcements',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student','instructor']);$cid=(int)$a['courseId'];$access->requireMember($u,$cid);$manage=$u['role']==='instructor'&&$access->isInstructor($cid,(int)$u['id']);$sql='SELECT * FROM announcements WHERE course_id=?'.($manage?'':" AND publish_at<=datetime('now')").' ORDER BY publish_at DESC,id DESC';return Http::json($s,['items'=>self::all($db,$sql,[$cid])]);});
        $app->post('/api/courses/{courseId}/announcements',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor']);$cid=(int)$a['courseId'];$access->requireInstructor($u,$cid);$access->writableCourse($cid);$d=self::body($r);self::required($d,['title','body']);$publish=$d['publishAt']??gmdate('Y-m-d H:i:s');$db->beginTransaction();$db->prepare('INSERT INTO announcements(course_id,title,body,publish_at,author_id) VALUES(?,?,?,?,?)')->execute([$cid,trim($d['title']),trim($d['body']),$publish,$u['id']]);$id=(int)$db->lastInsertId();if(strtotime($publish)<=time())$db->prepare("INSERT INTO notifications(user_id,type,message,link) SELECT student_id,'announcement',?,? FROM enrollments WHERE course_id=? AND status='active'")->execute(['New announcement: '.trim($d['title']),'/courses/'.$cid,$cid]);$db->commit();return Http::json($s,['announcement'=>self::one($db,'SELECT * FROM announcements WHERE id=?',[$id])],201);});
        $app->patch('/api/announcements/{announcementId}',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor']);$x=self::one($db,'SELECT * FROM announcements WHERE id=?',[(int)$a['announcementId']]);$access->requireInstructor($u,(int)$x['course_id']);$access->writableCourse((int)$x['course_id']);$d=self::body($r);$map=['title'=>'title','body'=>'body','publishAt'=>'publish_at'];$sets=[];$p=[];foreach($map as $i=>$c)if(array_key_exists($i,$d)){$sets[]="$c=?";$p[]=$d[$i];}if(!$sets)throw new ApiException(422,'validation_failed','No supported fields supplied.');$p[]=$x['id'];$db->prepare('UPDATE announcements SET '.implode(',',$sets).' WHERE id=?')->execute($p);return Http::json($s,['announcement'=>self::one($db,'SELECT * FROM announcements WHERE id=?',[$x['id']])]);});
        $app->delete('/api/announcements/{announcementId}',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor']);$x=self::one($db,'SELECT * FROM announcements WHERE id=?',[(int)$a['announcementId']]);$access->requireInstructor($u,(int)$x['course_id']);$access->writableCourse((int)$x['course_id']);$db->prepare('DELETE FROM announcements WHERE id=?')->execute([$x['id']]);return $s->withStatus(204);});
    }

    private static function discussions(App $app,PDO $db,Auth $auth,Access $access):void {
        $app->get('/api/courses/{courseId}/topics',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student','instructor']);$cid=(int)$a['courseId'];$access->requireMember($u,$cid);return Http::json($s,['items'=>self::all($db,'SELECT t.*,p.body,u.display_name author FROM discussion_topics t JOIN discussion_posts p ON p.topic_id=t.id AND p.is_topic_post=1 JOIN users u ON u.id=p.author_id WHERE t.course_id=? ORDER BY t.created_at DESC,t.id DESC',[$cid])]);});
        $app->post('/api/courses/{courseId}/topics',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student','instructor']);$cid=(int)$a['courseId'];$access->requireMember($u,$cid);$access->writableCourse($cid);$d=self::body($r);self::required($d,['title','body']);$db->beginTransaction();$db->prepare('INSERT INTO discussion_topics(course_id,title) VALUES(?,?)')->execute([$cid,trim($d['title'])]);$id=(int)$db->lastInsertId();$db->prepare('INSERT INTO discussion_posts(topic_id,author_id,body,is_topic_post) VALUES(?,?,?,1)')->execute([$id,$u['id'],trim($d['body'])]);$db->commit();return Http::json($s,['topic'=>self::one($db,'SELECT * FROM discussion_topics WHERE id=?',[$id])],201);});
        $app->get('/api/topics/{topicId}/replies',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student','instructor']);$t=self::one($db,'SELECT * FROM discussion_topics WHERE id=?',[(int)$a['topicId']]);$access->requireMember($u,(int)$t['course_id']);return Http::json($s,['items'=>self::all($db,'SELECT p.*,u.display_name author FROM discussion_posts p JOIN users u ON u.id=p.author_id WHERE p.topic_id=? AND p.is_topic_post=0 ORDER BY p.created_at,p.id',[$t['id']])]);});
        $app->post('/api/topics/{topicId}/replies',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student','instructor']);$t=self::one($db,'SELECT * FROM discussion_topics WHERE id=?',[(int)$a['topicId']]);$access->requireMember($u,(int)$t['course_id']);$access->writableCourse((int)$t['course_id']);$d=self::body($r);self::required($d,['body']);$db->prepare('INSERT INTO discussion_posts(topic_id,author_id,body) VALUES(?,?,?)')->execute([$t['id'],$u['id'],trim($d['body'])]);$id=(int)$db->lastInsertId();return Http::json($s,['post'=>self::one($db,'SELECT * FROM discussion_posts WHERE id=?',[$id])],201);});
        $edit=function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student','instructor']);$p=self::one($db,'SELECT p.*,t.course_id FROM discussion_posts p JOIN discussion_topics t ON t.id=p.topic_id WHERE p.id=?',[(int)$a['postId']]);$moderator=$u['role']==='instructor'&&$access->isInstructor((int)$p['course_id'],(int)$u['id']);if((int)$p['author_id']!==(int)$u['id']&&!$moderator)throw new ApiException(403,'post_access_denied','Only the author or course instructor may change this post.');$access->writableCourse((int)$p['course_id']);$d=self::body($r);self::required($d,['body']);$db->prepare("UPDATE discussion_posts SET body=?,updated_at=datetime('now') WHERE id=?")->execute([trim($d['body']),$p['id']]);return Http::json($s,['post'=>self::one($db,'SELECT * FROM discussion_posts WHERE id=?',[$p['id']])]);};
        $app->patch('/api/posts/{postId}',$edit);$app->delete('/api/posts/{postId}',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student','instructor']);$p=self::one($db,'SELECT p.*,t.course_id FROM discussion_posts p JOIN discussion_topics t ON t.id=p.topic_id WHERE p.id=?',[(int)$a['postId']]);$mod=$u['role']==='instructor'&&$access->isInstructor((int)$p['course_id'],(int)$u['id']);if((int)$p['author_id']!==(int)$u['id']&&!$mod)throw new ApiException(403,'post_access_denied','Only the author or course instructor may delete this post.');$access->writableCourse((int)$p['course_id']);if((int)$p['is_topic_post']===1)$db->prepare('DELETE FROM discussion_topics WHERE id=?')->execute([$p['topic_id']]);else$db->prepare('DELETE FROM discussion_posts WHERE id=?')->execute([$p['id']]);return $s->withStatus(204);});
    }

    private static function assignments(App $app,PDO $db,Auth $auth,Access $access,array $config):void {
        $app->get('/api/courses/{courseId}/assignments',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student','instructor']);$cid=(int)$a['courseId'];$access->requireMember($u,$cid);return Http::json($s,['items'=>self::all($db,'SELECT * FROM assignments WHERE course_id=? ORDER BY due_at,id',[$cid])]);});
        $app->post('/api/courses/{courseId}/assignments',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor']);$cid=(int)$a['courseId'];$access->requireInstructor($u,$cid);$access->writableCourse($cid);$d=self::body($r);self::required($d,['title','instructions','dueAt','maxScore']);if((float)$d['maxScore']<=0||!strtotime($d['dueAt']))throw new ApiException(422,'validation_failed','Invalid assignment settings.',['dueAt'=>'Use a valid date.','maxScore'=>'Must be positive.']);$db->prepare('INSERT INTO assignments(course_id,title,instructions,due_at,max_score) VALUES(?,?,?,?,?)')->execute([$cid,trim($d['title']),trim($d['instructions']),$d['dueAt'],(float)$d['maxScore']]);$id=(int)$db->lastInsertId();$db->prepare("INSERT INTO notifications(user_id,type,message,link) SELECT student_id,'assignment',?,? FROM enrollments WHERE course_id=? AND status='active'")->execute(['New assignment: '.trim($d['title']),'/courses/'.$cid,$cid]);return Http::json($s,['assignment'=>self::one($db,'SELECT * FROM assignments WHERE id=?',[$id])],201);});
        $app->get('/api/assignments/{assignmentId}',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student','instructor']);$x=self::one($db,'SELECT * FROM assignments WHERE id=?',[(int)$a['assignmentId']],'assignment_not_found');$access->requireMember($u,(int)$x['course_id']);return Http::json($s,['assignment'=>$x]);});
        $app->post('/api/assignments/{assignmentId}/submissions',function(Request $r,Response $s,array $a)use($auth,$db,$access,$config){$u=$auth->requireUser($r,['student']);$x=self::one($db,'SELECT * FROM assignments WHERE id=?',[(int)$a['assignmentId']],'assignment_not_found');$access->requireMember($u,(int)$x['course_id']);$access->writableCourse((int)$x['course_id']);$d=self::body($r);$text=trim((string)($d['text']??''));$fileId=null;$uploads=$r->getUploadedFiles();if(isset($uploads['file'])&&$uploads['file']->getError()===UPLOAD_ERR_OK){$f=$uploads['file'];if($f->getSize()>$config['maxUpload'])throw new ApiException(422,'validation_failed','File is too large.',['file'=>'Upload is above configured maximum.']);$dir=str_starts_with($config['uploadDir'],'/')?$config['uploadDir']:dirname(__DIR__).'/'.$config['uploadDir'];if(!is_dir($dir))mkdir($dir,0775,true);$name=bin2hex(random_bytes(16));$f->moveTo($dir.'/'.$name);$db->prepare('INSERT INTO stored_files(original_name,stored_name,mime_type,size_bytes) VALUES(?,?,?,?)')->execute([$f->getClientFilename()?:'submission',$name,$f->getClientMediaType()?:'application/octet-stream',$f->getSize()]);$fileId=(int)$db->lastInsertId();}if($text===''&&!$fileId)throw new ApiException(422,'validation_failed','Provide submission text or a file.',['text'=>'Required when no file is uploaded.']);$row=self::all($db,'SELECT MAX(version) v FROM submissions WHERE assignment_id=? AND student_id=?',[$x['id'],$u['id']]);$version=(int)($row[0]['v']??0)+1;$late=time()>strtotime($x['due_at'])?1:0;$db->beginTransaction();$db->prepare('UPDATE submissions SET is_current=0 WHERE assignment_id=? AND student_id=?')->execute([$x['id'],$u['id']]);$db->prepare('INSERT INTO submissions(assignment_id,student_id,version,text_content,file_id,is_late) VALUES(?,?,?,?,?,?)')->execute([$x['id'],$u['id'],$version,$text?:null,$fileId,$late]);$id=(int)$db->lastInsertId();$db->commit();return Http::json($s,['submission'=>self::one($db,'SELECT * FROM submissions WHERE id=?',[$id])],201);});
        $app->get('/api/assignments/{assignmentId}/submissions',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['student','instructor']);$x=self::one($db,'SELECT * FROM assignments WHERE id=?',[(int)$a['assignmentId']],'assignment_not_found');if($u['role']==='instructor'){$access->requireInstructor($u,(int)$x['course_id']);$rows=self::all($db,'SELECT s.*,u.display_name,u.email FROM submissions s JOIN users u ON u.id=s.student_id WHERE s.assignment_id=? ORDER BY u.display_name,s.version DESC',[$x['id']]);}else{$access->requireMember($u,(int)$x['course_id']);$rows=self::all($db,'SELECT * FROM submissions WHERE assignment_id=? AND student_id=? ORDER BY version DESC',[$x['id'],$u['id']]);foreach($rows as &$row)if(!(int)$row['released']){$row['score']=null;$row['feedback']=null;}}return Http::json($s,['items'=>$rows]);});
    }

    private static function administration(App $app,PDO $db,Auth $auth,Access $access):void {
        $app->post('/api/courses',function(Request $r,Response $s)use($auth,$db){$u=$auth->requireUser($r,['admin']);$d=self::body($r);self::required($d,['title','description','categoryId','capacity']);if((int)$d['capacity']<1)throw new ApiException(422,'validation_failed','Capacity must be positive.',['capacity'=>'Must be positive.']);self::one($db,'SELECT id FROM categories WHERE id=?',[(int)$d['categoryId']],'category_not_found');$db->beginTransaction();$db->prepare('INSERT INTO courses(title,description,category_id,capacity,enrollment_opens_at,enrollment_closes_at) VALUES(?,?,?,?,?,?)')->execute([trim($d['title']),trim($d['description']),(int)$d['categoryId'],(int)$d['capacity'],$d['enrollmentOpensAt']??null,$d['enrollmentClosesAt']??null]);$id=(int)$db->lastInsertId();$db->prepare("INSERT INTO audit_events(actor_id,action,entity_type,entity_id) VALUES(?,'create','course',?)")->execute([$u['id'],$id]);$db->commit();return Http::json($s,['course'=>self::one($db,'SELECT * FROM courses WHERE id=?',[$id])],201);});
        $app->patch('/api/courses/{courseId}',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['instructor','admin']);$cid=(int)$a['courseId'];$access->requireInstructor($u,$cid);$c=$access->writableCourse($cid);$d=self::body($r);if(isset($d['version'])&&(int)$d['version']!==(int)$c['version'])throw new ApiException(409,'stale_version','Course was changed by another request.');$map=['title'=>'title','description'=>'description','categoryId'=>'category_id','capacity'=>'capacity','enrollmentOpensAt'=>'enrollment_opens_at','enrollmentClosesAt'=>'enrollment_closes_at'];$sets=[];$p=[];foreach($map as $i=>$col)if(array_key_exists($i,$d)){$sets[]="$col=?";$p[]=$d[$i];}if(!$sets)throw new ApiException(422,'validation_failed','No supported fields supplied.');$sets[]='version=version+1';$sets[]="updated_at=datetime('now')";$p[]=$cid;$db->prepare('UPDATE courses SET '.implode(',',$sets).' WHERE id=?')->execute($p);return Http::json($s,['course'=>$access->course($cid)]);});
        $app->post('/api/courses/{courseId}/instructors',function(Request $r,Response $s,array $a)use($auth,$db,$access){$u=$auth->requireUser($r,['admin']);$cid=(int)$a['courseId'];$access->writableCourse($cid);$d=self::body($r);self::required($d,['userId']);self::one($db,"SELECT id FROM users WHERE id=? AND role='instructor'",[(int)$d['userId']],'instructor_not_found');$db->prepare('INSERT OR IGNORE INTO course_instructors(course_id,user_id) VALUES(?,?)')->execute([$cid,(int)$d['userId']]);return Http::json($s,['courseId'=>$cid,'userId'=>(int)$d['userId']],201);});
        $app->delete('/api/courses/{courseId}/instructors/{userId}',function(Request $r,Response $s,array $a)use($auth,$db,$access){$auth->requireUser($r,['admin']);$cid=(int)$a['courseId'];$access->writableCourse($cid);$count=(int)self::one($db,'SELECT COUNT(*) n FROM course_instructors WHERE course_id=?',[$cid])['n'];if($count<=1)throw new ApiException(409,'last_instructor','A course must retain at least one instructor.');$db->prepare('DELETE FROM course_instructors WHERE course_id=? AND user_id=?')->execute([$cid,(int)$a['userId']]);return $s->withStatus(204);});
        foreach(['publish'=>'published','archive'=>'archived'] as $action=>$status)$app->post('/api/courses/{courseId}/'.$action,function(Request $r,Response $s,array $a)use($auth,$db,$access,$status,$action){$u=$auth->requireUser($r,['instructor','admin']);$cid=(int)$a['courseId'];$access->requireInstructor($u,$cid);$c=$access->course($cid);if($action==='publish'&&$c['status']!=='draft')throw new ApiException(409,'invalid_course_state','Only draft courses can be published.');if($action==='archive'&&$c['status']!=='published')throw new ApiException(409,'invalid_course_state','Only published courses can be archived.');$db->prepare("UPDATE courses SET status=?,version=version+1,updated_at=datetime('now') WHERE id=?")->execute([$status,$cid]);return Http::json($s,['course'=>$access->course($cid)]);});
        $app->get('/api/admin/categories',function(Request $r,Response $s)use($auth,$db){$auth->requireUser($r,['admin']);return Http::json($s,['items'=>self::all($db,'SELECT * FROM categories ORDER BY name,id')]);});
        $app->post('/api/admin/categories',function(Request $r,Response $s)use($auth,$db){$auth->requireUser($r,['admin']);$d=self::body($r);self::required($d,['name']);$generated=preg_replace('/[^a-z0-9]+/i','-',trim($d['name']));$slug=strtolower(trim((string)($d['slug']??$generated),'-'));try{$db->prepare('INSERT INTO categories(name,slug) VALUES(?,?)')->execute([trim($d['name']),$slug]);}catch(\PDOException){throw new ApiException(409,'category_exists','Category name or slug already exists.');}$id=(int)$db->lastInsertId();return Http::json($s,['category'=>self::one($db,'SELECT * FROM categories WHERE id=?',[$id])],201);});
    }
}
