import express from 'express';import {ApiError,required,integer} from './errors.js';import {authService,publicUser} from './auth.js';import {repository} from './repository.js';
const now=()=>new Date().toISOString(),dateOk=x=>/^\d{4}-\d{2}-\d{2}$/.test(String(x))&&!Number.isNaN(new Date(`${x}T00:00:00Z`).valueOf());
const version=(body,row)=>{integer(body.version,1,Number.MAX_SAFE_INTEGER,'version');if(body.version!==row.version)throw new ApiError(409,'stale_version','The resource has changed.');};
const reportJson=(db,row)=>({...row,items:db.prepare('SELECT * FROM expense_items WHERE report_id=? ORDER BY id').all(row.id)});
const editable=row=>{if(!['draft','returned'].includes(row.status))throw new ApiError(409,'invalid_state','Report is not editable.');};
const employeeOwn=(user,row)=>{if(row.employee_id!==user.id)throw new ApiError(403,'forbidden','Report belongs to another employee.');};
const recalc=(db,id)=>db.prepare('UPDATE expense_reports SET total_cents=COALESCE((SELECT sum(amount_cents) FROM expense_items WHERE report_id=?),0),version=version+1,updated_at=? WHERE id=?').run(id,now(),id);
const access=(db,user,row)=>{if(user.role==='employee')employeeOwn(user,row);else if(user.role==='manager'){const ok=db.prepare('SELECT 1 FROM reporting_lines WHERE employee_id=? AND manager_id=?').get(row.employee_id,user.id);if(!ok)throw new ApiError(403,'forbidden','Employee is outside the reporting line.');}else if(user.role!=='finance'&&user.role!=='admin')throw new ApiError(403,'forbidden','Report access is not permitted.');};
const policyFor=(db,item,currency)=>db.prepare("SELECT * FROM expense_policies WHERE category=? AND currency=? AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) ORDER BY effective_from DESC LIMIT 1").get(item.category,currency,item.expense_date,item.expense_date);
export function createApp({db,env=process.env}){const app=express(),auth=authService(db,env),repo=repository(db);app.disable('x-powered-by');app.use(express.json({limit:'2mb'}));app.use(express.static('public'));
 app.post('/api/auth/login',(req,res)=>res.json({user:auth.login(req,res)}));app.post('/api/auth/logout',(req,res)=>{auth.current(req);auth.logout(req,res);res.json({logged_out:true});});app.post('/api/auth/password-reset-requests',(req,res)=>res.json(auth.requestReset(req)));app.post('/api/auth/password-resets',(req,res)=>res.json(auth.reset(req)));

 app.post('/api/expense-reports',(req,res)=>{const user=auth.current(req,['employee']);required(req.body,['title','currency']);const currency=db.prepare('SELECT * FROM currencies WHERE code=? AND enabled=1').get(req.body.currency);if(!currency)throw new ApiError(422,'unsupported_currency','Currency is not supported.');const t=now();const r=db.prepare("INSERT INTO expense_reports(report_number,employee_id,title,currency,business_purpose,status,created_at,updated_at) VALUES(?,?,?,?,?,'draft',?,?)").run(`EXP-${Date.now()}-${user.id}`,user.id,String(req.body.title),currency.code,String(req.body.business_purpose??''),t,t);res.status(201).json(reportJson(db,repo.report(r.lastInsertRowid)));});
 app.patch('/api/expense-reports/:id',(req,res)=>{const user=auth.current(req,['employee']),row=repo.report(Number(req.params.id));employeeOwn(user,row);editable(row);version(req.body,row);let currency=row.currency;if(req.body.currency!==undefined){const c=db.prepare('SELECT * FROM currencies WHERE code=? AND enabled=1').get(req.body.currency);if(!c)throw new ApiError(422,'unsupported_currency','Currency is not supported.');currency=c.code;}db.prepare('UPDATE expense_reports SET title=?,currency=?,business_purpose=?,version=version+1,updated_at=? WHERE id=?').run(req.body.title??row.title,currency,req.body.business_purpose??row.business_purpose,now(),row.id);res.json(reportJson(db,repo.report(row.id)));});
 app.post('/api/expense-reports/:id/items',(req,res)=>{const user=auth.current(req,['employee']),row=repo.report(Number(req.params.id));employeeOwn(user,row);editable(row);required(req.body,['expense_date','category','description','amount_cents']);if(!dateOk(req.body.expense_date))throw new ApiError(422,'validation_error','Expense date is invalid.');integer(req.body.amount_cents,1,100000000,'amount_cents');const r=db.transaction(()=>{const out=db.prepare('INSERT INTO expense_items(report_id,expense_date,category,description,amount_cents,merchant) VALUES(?,?,?,?,?,?)').run(row.id,req.body.expense_date,req.body.category,req.body.description,req.body.amount_cents,String(req.body.merchant??''));recalc(db,row.id);return out;})();res.status(201).json(repo.item(r.lastInsertRowid));});
 app.patch('/api/expense-items/:id',(req,res)=>{const user=auth.current(req,['employee']),item=repo.item(Number(req.params.id)),row=repo.report(item.report_id);employeeOwn(user,row);editable(row);version(req.body,item);const amount=req.body.amount_cents??item.amount_cents;integer(amount,1,100000000,'amount_cents');const date=req.body.expense_date??item.expense_date;if(!dateOk(date))throw new ApiError(422,'validation_error','Expense date is invalid.');db.transaction(()=>{db.prepare('UPDATE expense_items SET expense_date=?,category=?,description=?,amount_cents=?,merchant=?,version=version+1 WHERE id=?').run(date,req.body.category??item.category,req.body.description??item.description,amount,req.body.merchant??item.merchant,item.id);recalc(db,row.id);})();res.json(repo.item(item.id));});
 app.delete('/api/expense-items/:id',(req,res)=>{const user=auth.current(req,['employee']),item=repo.item(Number(req.params.id)),row=repo.report(item.report_id);employeeOwn(user,row);editable(row);version(req.body,item);db.transaction(()=>{db.prepare('DELETE FROM expense_items WHERE id=?').run(item.id);recalc(db,row.id);})();res.status(204).end();});

 app.post('/api/expense-items/:id/receipts',(req,res)=>{const user=auth.current(req,['employee']),item=repo.item(Number(req.params.id)),row=repo.report(item.report_id);employeeOwn(user,row);editable(row);required(req.body,['filename','mime_type','content_base64']);if(!['image/png','image/jpeg','application/pdf','text/plain'].includes(req.body.mime_type)||!/^[-\w.]{1,100}$/.test(req.body.filename))throw new ApiError(422,'validation_error','Invalid receipt metadata.');const bytes=Buffer.from(req.body.content_base64,'base64');if(!bytes.length||bytes.length>Number(env.MAX_RECEIPT_BYTES||1048576))throw new ApiError(422,'validation_error','Invalid receipt size.');const r=db.prepare('INSERT INTO receipts(item_id,filename,mime_type,bytes,created_at) VALUES(?,?,?,?,?)').run(item.id,req.body.filename,req.body.mime_type,bytes,now());res.status(201).json({id:r.lastInsertRowid,item_id:item.id,filename:req.body.filename,mime_type:req.body.mime_type,size:bytes.length});});
 app.get('/api/receipts/:id/content',(req,res)=>{const user=auth.current(req,['employee']),receipt=repo.receipt(Number(req.params.id)),item=repo.item(receipt.item_id),row=repo.report(item.report_id);employeeOwn(user,row);res.type(receipt.mime_type).send(receipt.bytes);});
 app.delete('/api/receipts/:id',(req,res)=>{const user=auth.current(req,['employee']),receipt=repo.receipt(Number(req.params.id)),item=repo.item(receipt.item_id),row=repo.report(item.report_id);employeeOwn(user,row);editable(row);db.prepare('DELETE FROM receipts WHERE id=?').run(receipt.id);res.status(204).end();});

 app.post('/api/expense-reports/:id/submit',(req,res)=>{const user=auth.current(req,['employee']),row=repo.report(Number(req.params.id));employeeOwn(user,row);editable(row);version(req.body,row);const items=db.prepare('SELECT * FROM expense_items WHERE report_id=? ORDER BY id').all(row.id);if(!items.length)throw new ApiError(409,'incomplete_report','Report must contain an item.');for(const item of items){const policy=policyFor(db,item,row.currency);if(!policy)throw new ApiError(422,'policy_missing','No effective policy covers an item.');if(item.amount_cents>policy.max_amount_cents)throw new ApiError(422,'policy_limit_exceeded','An item exceeds its category limit.');if(item.amount_cents>=policy.receipt_threshold_cents&&!db.prepare('SELECT 1 FROM receipts WHERE item_id=?').get(item.id))throw new ApiError(422,'receipt_required','A required receipt is missing.');}const line=db.prepare('SELECT * FROM reporting_lines WHERE employee_id=?').get(user.id);if(!line)throw new ApiError(409,'manager_missing','No manager is assigned.');db.transaction(()=>{db.prepare("UPDATE expense_reports SET status='submitted',version=version+1,updated_at=? WHERE id=?").run(now(),row.id);db.prepare('INSERT INTO approval_steps(report_id,manager_id) VALUES(?,?)').run(row.id,line.manager_id);db.prepare('INSERT INTO activity_events(report_id,actor_id,event_type,detail,created_at) VALUES(?,?,?,?,?)').run(row.id,user.id,'report.submitted','Submitted for approval',now());db.prepare('INSERT INTO notifications(user_id,type,message,report_id,created_at) VALUES(?,?,?,?,?)').run(line.manager_id,'approval_requested',`${row.report_number} requires approval`,row.id,now());})();res.json(reportJson(db,repo.report(row.id)));});

 app.get('/api/manager/expense-reports',(req,res)=>{const user=auth.current(req,['manager']),wanted=String(req.query.status||'pending');if(!['pending','approved','rejected','returned'].includes(wanted))throw new ApiError(422,'validation_error','Invalid approval status.');const rows=db.prepare('SELECT r.* FROM expense_reports r JOIN approval_steps a ON a.report_id=r.id WHERE a.manager_id=? AND a.decision=? ORDER BY r.id').all(user.id,wanted);res.json({items:rows.map(x=>reportJson(db,x))});});
 const managerDecision=(req,user,decision,status,needsComment)=>{const row=repo.report(Number(req.params.id)),step=db.prepare("SELECT * FROM approval_steps WHERE report_id=? AND manager_id=? AND decision='pending'").get(row.id,user.id);if(!step)throw new ApiError(403,'not_assigned','Report is not pending for this manager.');if(row.status!=='submitted')throw new ApiError(409,'invalid_state','Report is not awaiting manager review.');if(needsComment)required(req.body,['comment']);version(req.body,row);db.transaction(()=>{db.prepare('UPDATE approval_steps SET decision=?,comment=?,decided_at=? WHERE id=?').run(decision,String(req.body.comment??''),now(),step.id);db.prepare('UPDATE expense_reports SET status=?,version=version+1,updated_at=? WHERE id=?').run(status,now(),row.id);db.prepare('INSERT INTO activity_events(report_id,actor_id,event_type,detail,created_at) VALUES(?,?,?,?,?)').run(row.id,user.id,`manager.${decision}`,String(req.body.comment??''),now());const type=status==='approved'?'finance_review':'report_update';const target=status==='approved'?5:row.employee_id;db.prepare('INSERT INTO notifications(user_id,type,message,report_id,created_at) VALUES(?,?,?,?,?)').run(target,type,`${row.report_number}: ${decision}`,row.id,now());})();return reportJson(db,repo.report(row.id));};
 app.post('/api/manager/expense-reports/:id/approve',(req,res)=>res.json(managerDecision(req,auth.current(req,['manager']),'approved','approved',false)));app.post('/api/manager/expense-reports/:id/reject',(req,res)=>res.json(managerDecision(req,auth.current(req,['manager']),'rejected','rejected',true)));app.post('/api/manager/expense-reports/:id/return',(req,res)=>res.json(managerDecision(req,auth.current(req,['manager']),'returned','returned',true)));

 app.get('/api/finance/expense-reports',(req,res)=>{auth.current(req,['finance']);const status=String(req.query.status||'approved');if(!['approved','verified','returned'].includes(status))throw new ApiError(422,'validation_error','Invalid finance status.');res.json({items:db.prepare('SELECT * FROM expense_reports WHERE status=? ORDER BY id').all(status).map(x=>reportJson(db,x))});});
 const financeDecision=(req,user,decision,status)=>{const row=repo.report(Number(req.params.id));if(row.status!=='approved')throw new ApiError(409,'invalid_state','Report is not approved for finance review.');if(decision==='returned')required(req.body,['comment']);version(req.body,row);db.transaction(()=>{db.prepare('INSERT INTO finance_reviews(report_id,finance_id,decision,comment,created_at) VALUES(?,?,?,?,?)').run(row.id,user.id,decision,String(req.body.comment??''),now());db.prepare('UPDATE expense_reports SET status=?,version=version+1,updated_at=? WHERE id=?').run(status,now(),row.id);db.prepare('INSERT INTO activity_events(report_id,actor_id,event_type,detail,created_at) VALUES(?,?,?,?,?)').run(row.id,user.id,`finance.${decision}`,String(req.body.comment??''),now());db.prepare('INSERT INTO notifications(user_id,type,message,report_id,created_at) VALUES(?,?,?,?,?)').run(row.employee_id,'finance_update',`${row.report_number}: ${decision}`,row.id,now());})();return reportJson(db,repo.report(row.id));};
 app.post('/api/finance/expense-reports/:id/verify',(req,res)=>res.json(financeDecision(req,auth.current(req,['finance']),'verified','verified')));app.post('/api/finance/expense-reports/:id/return',(req,res)=>res.json(financeDecision(req,auth.current(req,['finance']),'returned','returned')));

 app.get('/api/admin/expense-policies',(req,res)=>{auth.current(req,['finance','admin']);res.json({items:db.prepare('SELECT * FROM expense_policies ORDER BY id').all()});});
 app.post('/api/admin/expense-policies',(req,res)=>{auth.current(req,['finance','admin']);required(req.body,['category','currency','max_amount_cents','receipt_threshold_cents','effective_from']);integer(req.body.max_amount_cents,1,100000000,'max_amount_cents');integer(req.body.receipt_threshold_cents,0,100000000,'receipt_threshold_cents');if(!dateOk(req.body.effective_from)||req.body.effective_to&&!dateOk(req.body.effective_to)||req.body.effective_to&&req.body.effective_to<req.body.effective_from)throw new ApiError(422,'validation_error','Invalid effective dates.');if(!db.prepare('SELECT 1 FROM currencies WHERE code=? AND enabled=1').get(req.body.currency))throw new ApiError(422,'unsupported_currency','Currency is not supported.');try{const r=db.prepare('INSERT INTO expense_policies(category,currency,max_amount_cents,receipt_threshold_cents,effective_from,effective_to) VALUES(?,?,?,?,?,?)').run(req.body.category,req.body.currency,req.body.max_amount_cents,req.body.receipt_threshold_cents,req.body.effective_from,req.body.effective_to??null);res.status(201).json(repo.policy(r.lastInsertRowid));}catch(e){if(e.code==='SQLITE_CONSTRAINT_UNIQUE')throw new ApiError(409,'policy_exists','Policy already exists for that effective date.');throw e;}});
 app.patch('/api/admin/expense-policies/:id',(req,res)=>{auth.current(req,['finance','admin']);const row=repo.policy(Number(req.params.id));version(req.body,row);const max=req.body.max_amount_cents??row.max_amount_cents,threshold=req.body.receipt_threshold_cents??row.receipt_threshold_cents;integer(max,1,100000000,'max_amount_cents');integer(threshold,0,100000000,'receipt_threshold_cents');db.prepare('UPDATE expense_policies SET max_amount_cents=?,receipt_threshold_cents=?,effective_to=?,version=version+1 WHERE id=?').run(max,threshold,req.body.effective_to??row.effective_to,row.id);res.json(repo.policy(row.id));});

 app.get('/api/expense-reports/:id/activity',(req,res)=>{const user=auth.current(req,['employee','manager','finance']),row=repo.report(Number(req.params.id));access(db,user,row);res.json({items:db.prepare('SELECT * FROM activity_events WHERE report_id=? ORDER BY id').all(row.id)});});
 app.post('/api/expense-reports/:id/comments',(req,res)=>{const user=auth.current(req,['employee','manager','finance']),row=repo.report(Number(req.params.id));access(db,user,row);required(req.body,['body','idempotency_key']);if(String(req.body.body).length>2000)throw new ApiError(422,'validation_error','Comment is too long.');try{const r=db.prepare('INSERT INTO report_comments(report_id,author_id,body,created_at,idempotency_key) VALUES(?,?,?,?,?)').run(row.id,user.id,String(req.body.body),now(),req.body.idempotency_key);db.prepare('INSERT INTO activity_events(report_id,actor_id,event_type,detail,created_at) VALUES(?,?,?,?,?)').run(row.id,user.id,'comment.added',String(req.body.body),now());res.status(201).json(db.prepare('SELECT * FROM report_comments WHERE id=?').get(r.lastInsertRowid));}catch(e){if(e.code==='SQLITE_CONSTRAINT_UNIQUE')throw new ApiError(409,'duplicate_comment','Comment action already exists.');throw e;}});

 app.get('/api/expense-reports',(req,res)=>{const user=auth.current(req,['employee','manager','finance']);const page=Number(req.query.page||1);integer(page,1,10000,'page');let rows=user.role==='employee'?db.prepare('SELECT * FROM expense_reports WHERE employee_id=? ORDER BY id DESC').all(user.id):user.role==='manager'?db.prepare('SELECT r.* FROM expense_reports r JOIN reporting_lines l ON l.employee_id=r.employee_id WHERE l.manager_id=? ORDER BY r.id DESC').all(user.id):db.prepare('SELECT * FROM expense_reports ORDER BY id DESC').all();res.json({items:rows.slice((page-1)*20,page*20).map(x=>reportJson(db,x)),page});});
 app.get('/api/expense-reports/:id',(req,res)=>{const user=auth.current(req,['employee','manager','finance']),row=repo.report(Number(req.params.id));access(db,user,row);res.json(reportJson(db,row));});
 app.get('/api/manager/employees/:employeeId/expense-reports',(req,res)=>{const user=auth.current(req,['manager']),employee=repo.user(Number(req.params.employeeId));const line=db.prepare('SELECT 1 FROM reporting_lines WHERE employee_id=? AND manager_id=?').get(employee.id,user.id);if(!line)throw new ApiError(403,'forbidden','Employee is outside the reporting line.');res.json({employee:publicUser(employee),items:db.prepare('SELECT * FROM expense_reports WHERE employee_id=? ORDER BY id DESC').all(employee.id).map(x=>reportJson(db,x))});});

 app.post('/api/finance/reimbursement-batches',(req,res)=>{const user=auth.current(req,['finance']);required(req.body,['idempotency_key']);const reports=db.prepare("SELECT * FROM expense_reports r WHERE status='verified' AND NOT EXISTS(SELECT 1 FROM batch_items b WHERE b.report_id=r.id) ORDER BY id").all();if(!reports.length)throw new ApiError(409,'no_reports','No verified reports are available.');try{const result=db.transaction(()=>{const batch=db.prepare("INSERT INTO reimbursement_batches(batch_number,created_by,created_at,idempotency_key) VALUES(?,?,?,?)").run(`PAY-${Date.now()}`,user.id,now(),req.body.idempotency_key),stmt=db.prepare('INSERT INTO batch_items VALUES(?,?,?)');for(const report of reports)stmt.run(batch.lastInsertRowid,report.id,report.total_cents);return db.prepare('SELECT * FROM reimbursement_batches WHERE id=?').get(batch.lastInsertRowid);})();res.status(201).json({...result,report_count:reports.length,total_cents:reports.reduce((n,x)=>n+x.total_cents,0)});}catch(e){if(e.code==='SQLITE_CONSTRAINT_UNIQUE')throw new ApiError(409,'duplicate_batch','Batch action already exists.');throw e;}});
 app.get('/api/finance/reimbursement-batches/:id.csv',(req,res)=>{auth.current(req,['finance']);const batch=repo.batch(Number(req.params.id));const rows=db.prepare('SELECT r.report_number,u.email,b.amount_cents,r.currency FROM batch_items b JOIN expense_reports r ON r.id=b.report_id JOIN users u ON u.id=r.employee_id WHERE b.batch_id=? ORDER BY r.id').all(batch.id);const csv=['report_number,employee_email,amount_cents,currency',...rows.map(x=>`${x.report_number},${x.email},${x.amount_cents},${x.currency}`)].join('\n');res.type('text/csv').send(csv);});
 app.post('/api/finance/reimbursement-batches/:id/processed',(req,res)=>{const user=auth.current(req,['finance']),batch=repo.batch(Number(req.params.id));if(batch.status!=='created')throw new ApiError(409,'invalid_state','Batch is already processed.');db.transaction(()=>{db.prepare("UPDATE reimbursement_batches SET status='processed',processed_at=? WHERE id=?").run(now(),batch.id);db.prepare("UPDATE expense_reports SET status='reimbursed',version=version+1,updated_at=? WHERE id IN(SELECT report_id FROM batch_items WHERE batch_id=?)").run(now(),batch.id);for(const row of db.prepare('SELECT report_id FROM batch_items WHERE batch_id=?').all(batch.id))db.prepare('INSERT INTO activity_events(report_id,actor_id,event_type,detail,created_at) VALUES(?,?,?,?,?)').run(row.report_id,user.id,'reimbursement.processed',batch.batch_number,now());})();res.json(repo.batch(batch.id));});

 app.get('/api/admin/departments',(req,res)=>{auth.current(req,['admin']);res.json({items:db.prepare('SELECT * FROM departments ORDER BY id').all()});});app.post('/api/admin/departments',(req,res)=>{auth.current(req,['admin']);required(req.body,['name','code']);if(!/^[A-Z]{2,8}$/.test(req.body.code))throw new ApiError(422,'validation_error','Department code is invalid.');try{const r=db.prepare('INSERT INTO departments(name,code) VALUES(?,?)').run(req.body.name,req.body.code);res.status(201).json(repo.department(r.lastInsertRowid));}catch(e){if(e.code==='SQLITE_CONSTRAINT_UNIQUE')throw new ApiError(409,'department_exists','Department already exists.');throw e;}});
 app.patch('/api/admin/users/:id/manager',(req,res)=>{auth.current(req,['admin']);const employee=repo.user(Number(req.params.id)),manager=repo.user(req.body.manager_id);if(employee.role!=='employee'||manager.role!=='manager'||employee.id===manager.id)throw new ApiError(422,'validation_error','Invalid reporting line.');db.prepare('INSERT INTO reporting_lines(employee_id,manager_id) VALUES(?,?) ON CONFLICT(employee_id) DO UPDATE SET manager_id=excluded.manager_id,version=reporting_lines.version+1').run(employee.id,manager.id);res.json({employee_id:employee.id,manager_id:manager.id});});
 app.patch('/api/admin/users/:id/roles',(req,res)=>{const actor=auth.current(req,['admin']),row=repo.user(Number(req.params.id));required(req.body,['role']);version(req.body,row);if(!['employee','manager','finance','admin'].includes(req.body.role))throw new ApiError(422,'validation_error','Invalid role.');if(row.id===actor.id&&req.body.role!=='admin')throw new ApiError(409,'admin_guard','Administrator cannot remove their own role.');db.prepare('UPDATE users SET role=?,version=version+1 WHERE id=?').run(req.body.role,row.id);res.json(publicUser(repo.user(row.id)));});
 app.patch('/api/admin/currencies',(req,res)=>{auth.current(req,['admin']);required(req.body,['currencies']);if(!Array.isArray(req.body.currencies)||!req.body.currencies.length)throw new ApiError(422,'validation_error','Currencies must be a non-empty array.');for(const c of req.body.currencies)if(!c||!(/^[A-Z]{3}$/).test(c.code)||typeof c.enabled!=='boolean')throw new ApiError(422,'validation_error','Invalid currency entry.');db.transaction(()=>{for(const c of req.body.currencies){const found=db.prepare('SELECT 1 FROM currencies WHERE code=?').get(c.code);if(!found)throw new ApiError(404,'not_found',`Currency ${c.code} was not found.`);db.prepare('UPDATE currencies SET enabled=?,version=version+1 WHERE code=?').run(Number(c.enabled),c.code);}})();res.json({items:db.prepare('SELECT * FROM currencies ORDER BY code').all().map(x=>({...x,enabled:Boolean(x.enabled)}))});});

 app.get('/api/dashboard',(req,res)=>{const user=auth.current(req,['employee','manager','finance']);const counts=user.role==='employee'?db.prepare('SELECT status,count(*) count FROM expense_reports WHERE employee_id=? GROUP BY status').all(user.id):user.role==='manager'?db.prepare('SELECT r.status,count(*) count FROM expense_reports r JOIN reporting_lines l ON l.employee_id=r.employee_id WHERE l.manager_id=? GROUP BY r.status').all(user.id):db.prepare('SELECT status,count(*) count FROM expense_reports GROUP BY status').all();res.json({role:user.role,counts:Object.fromEntries(counts.map(x=>[x.status,x.count])),unread_notifications:db.prepare('SELECT count(*) count FROM notifications WHERE user_id=? AND read_at IS NULL').get(user.id).count});});
 app.get('/api/notifications',(req,res)=>{const user=auth.current(req,['employee','manager','finance']);const page=Number(req.query.page||1);integer(page,1,10000,'page');res.json({items:db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 20 OFFSET ?').all(user.id,(page-1)*20),page});});
 app.post('/api/notifications/:id/read',(req,res)=>{const user=auth.current(req,['employee','manager','finance']),note=repo.notification(Number(req.params.id));if(note.user_id!==user.id)throw new ApiError(403,'forbidden','Notification belongs to another user.');if(!note.read_at)db.prepare('UPDATE notifications SET read_at=? WHERE id=?').run(now(),note.id);res.json(repo.notification(note.id));});

 app.use('/api',(req,res,next)=>next(new ApiError(404,'not_found','API route was not found.')));app.use((err,req,res,next)=>{if(res.headersSent)return next(err);if(err instanceof SyntaxError&&err.status===400)return res.status(422).json({error:{code:'invalid_json',message:'Request JSON is invalid.',fields:{}}});const status=err.status||500;if(status===500)console.error('Unexpected server error');res.status(status).json({error:{code:err.code||'internal_error',message:status===500?'An unexpected error occurred.':err.message,fields:err.fields||{}}});});return app;}
