<?php
declare(strict_types=1);
namespace App;
use PDO;use Slim\App;use Psr\Http\Message\ServerRequestInterface as Request;use Psr\Http\Message\ResponseInterface as Response;
final class AuthProfileRoutes
{
    use Support;
    public static function register(App $app,PDO $db,Auth $auth,array $cfg):void
    {
        $app->get('/',fn(Request $r,Response $s)=>$s->withHeader('Location','/app.html')->withStatus(302));
        $app->get('/health',fn(Request $r,Response $s)=>Http::json($s,['status'=>'ok','database'=>(bool)$db->query('SELECT 1')->fetchColumn()]));
        $app->post('/api/auth/register',function(Request $r,Response $s)use($db,$auth,$cfg){$d=self::body($r);self::required($d,['email','password','name']);if(!filter_var($d['email'],FILTER_VALIDATE_EMAIL))throw new ApiException(422,'validation_failed','Invalid email.',['email'=>'Enter a valid email.']);if(strlen((string)$d['password'])<10)throw new ApiException(422,'validation_failed','Password is too short.',['password'=>'Use at least 10 characters.']);try{$db->beginTransaction();$db->prepare("INSERT INTO users(email,password_hash,name,role,phone) VALUES(?,?,?,'customer',?)")->execute([strtolower(trim($d['email'])),password_hash($d['password'],PASSWORD_DEFAULT),trim($d['name']),trim((string)($d['phone']??''))]);$id=(int)$db->lastInsertId();$db->prepare('INSERT INTO customer_profiles(user_id) VALUES(?)')->execute([$id]);$db->prepare('INSERT INTO carts(customer_id) VALUES(?)')->execute([$id]);$db->commit();}catch(\PDOException){if($db->inTransaction())$db->rollBack();throw new ApiException(409,'email_exists','An account already uses this email.');}$token=$auth->create($id);return Http::json($s,['user'=>self::one($db,'SELECT id,email,name,role,phone FROM users WHERE id=?',[$id])],201)->withAddedHeader('Set-Cookie',$auth->cookie($token,$cfg['sessionTtl']));});
        $app->post('/api/auth/login',function(Request $r,Response $s)use($db,$auth,$cfg){$d=self::body($r);self::required($d,['email','password']);$st=$db->prepare('SELECT * FROM users WHERE email=? COLLATE NOCASE');$st->execute([trim($d['email'])]);$u=$st->fetch();if(!$u||!password_verify((string)$d['password'],$u['password_hash']))throw new ApiException(401,'invalid_credentials','Email or password is incorrect.');$token=$auth->create((int)$u['id']);unset($u['password_hash']);return Http::json($s,['user'=>$u])->withAddedHeader('Set-Cookie',$auth->cookie($token,$cfg['sessionTtl']));});
        $app->post('/api/auth/logout',function(Request $r,Response $s)use($auth){$auth->destroy($r);return Http::json($s,['message'=>'Signed out.'])->withAddedHeader('Set-Cookie',$auth->cookie('',0));});
        $app->get('/api/profile',function(Request $r,Response $s)use($auth,$db){$u=$auth->requireUser($r);$out=['user'=>$u];if($u['role']==='customer')$out['customerProfile']=self::one($db,'SELECT marketing_opt_in FROM customer_profiles WHERE user_id=?',[$u['id']]);if($u['role']==='seller')$out['sellerProfile']=self::one($db,'SELECT storefront_name,description,support_email,approval_status,approved_at FROM seller_profiles WHERE user_id=?',[$u['id']]);return Http::json($s,$out);});
        $app->patch('/api/profile',function(Request $r,Response $s)use($auth,$db){$u=$auth->requireUser($r);$d=self::body($r);$sets=[];$p=[];foreach(['name','phone']as$f)if(array_key_exists($f,$d)){$value=trim((string)$d[$f]);if($f==='name'&&$value==='')throw new ApiException(422,'validation_failed','Name is required.',['name'=>'Required.']);$sets[]="$f=?";$p[]=$value;}if(!$sets&&!array_key_exists('marketingOptIn',$d))throw new ApiException(422,'validation_failed','No supported profile fields supplied.');if($sets){$p[]=$u['id'];$db->prepare('UPDATE users SET '.implode(',',$sets).' WHERE id=?')->execute($p);}if($u['role']==='customer'&&array_key_exists('marketingOptIn',$d))$db->prepare('UPDATE customer_profiles SET marketing_opt_in=? WHERE user_id=?')->execute([(int)(bool)$d['marketingOptIn'],$u['id']]);return Http::json($s,['user'=>self::one($db,'SELECT id,email,name,role,phone FROM users WHERE id=?',[$u['id']])]);});

        $app->get('/api/addresses',function(Request $r,Response $s)use($auth,$db){$u=$auth->requireUser($r,['customer']);return Http::json($s,['items'=>self::all($db,'SELECT * FROM addresses WHERE user_id=? ORDER BY id',[$u['id']])]);});
        $app->post('/api/addresses',function(Request $r,Response $s)use($auth,$db){$u=$auth->requireUser($r,['customer']);$d=self::body($r);self::required($d,['recipient','street','city','region','postalCode','country']);$db->prepare('INSERT INTO addresses(user_id,recipient,street,city,region,postal_code,country) VALUES(?,?,?,?,?,?,?)')->execute([$u['id'],trim($d['recipient']),trim($d['street']),trim($d['city']),trim($d['region']),trim($d['postalCode']),strtoupper(trim($d['country']))]);$id=(int)$db->lastInsertId();return Http::json($s,['address'=>self::one($db,'SELECT * FROM addresses WHERE id=?',[$id])],201);});
        $app->patch('/api/addresses/{addressId}',function(Request $r,Response $s,array $a)use($auth,$db){$u=$auth->requireUser($r,['customer']);$x=self::one($db,'SELECT * FROM addresses WHERE id=? AND user_id=?',[(int)$a['addressId'],$u['id']],'address_not_found');$d=self::body($r);$map=['recipient'=>'recipient','street'=>'street','city'=>'city','region'=>'region','postalCode'=>'postal_code','country'=>'country'];$sets=[];$p=[];foreach($map as$in=>$col)if(array_key_exists($in,$d)){$v=trim((string)$d[$in]);if($v==='')throw new ApiException(422,'validation_failed','Address fields cannot be empty.',[$in=>'Required.']);$sets[]="$col=?";$p[]=$in==='country'?strtoupper($v):$v;}if(!$sets)throw new ApiException(422,'validation_failed','No supported address fields supplied.');$p[]=$x['id'];$db->prepare('UPDATE addresses SET '.implode(',',$sets).' WHERE id=?')->execute($p);return Http::json($s,['address'=>self::one($db,'SELECT * FROM addresses WHERE id=?',[$x['id']])]);});
        $app->delete('/api/addresses/{addressId}',function(Request $r,Response $s,array $a)use($auth,$db){$u=$auth->requireUser($r,['customer']);$x=self::one($db,'SELECT * FROM addresses WHERE id=? AND user_id=?',[(int)$a['addressId'],$u['id']],'address_not_found');$st=$db->prepare("SELECT 1 FROM orders WHERE address_id=? AND status IN ('paid','shipped','refund_requested')");$st->execute([$x['id']]);if($st->fetchColumn())throw new ApiException(409,'address_in_use','This address is referenced by an active order.');$db->prepare('DELETE FROM addresses WHERE id=?')->execute([$x['id']]);return$s->withStatus(204);});
        $app->get('/api/profile/export',function(Request $r,Response $s)use($auth,$db){$u=$auth->requireUser($r,['customer']);$data=['profile'=>$u,'addresses'=>self::all($db,'SELECT recipient,street,city,region,postal_code,country FROM addresses WHERE user_id=? ORDER BY id',[$u['id']]),'orders'=>self::all($db,'SELECT id,status,total_cents/100.0 total,created_at FROM orders WHERE customer_id=? ORDER BY id',[$u['id']]),'wishlist'=>self::all($db,'SELECT p.id,p.name FROM wishlist_items w JOIN products p ON p.id=w.product_id WHERE w.customer_id=? ORDER BY p.id',[$u['id']])];return Http::json($s,$data)->withHeader('Content-Disposition','attachment; filename="profile-export-'.$u['id'].'.json"');});
        $app->post('/api/profile/deletion-requests',function(Request $r,Response $s)use($auth,$db){$u=$auth->requireUser($r,['customer']);$existing=self::all($db,"SELECT * FROM deletion_requests WHERE user_id=? AND status='pending'",[$u['id']]);if($existing)return Http::json($s,['deletionRequest'=>$existing[0]]);$db->prepare('INSERT INTO deletion_requests(user_id) VALUES(?)')->execute([$u['id']]);return Http::json($s,['deletionRequest'=>self::one($db,'SELECT * FROM deletion_requests WHERE id=?',[(int)$db->lastInsertId()])],201);});
    }
}
