<?php
declare(strict_types=1);
namespace App;
use PDO;use Slim\App;use Psr\Http\Message\ServerRequestInterface as Request;use Psr\Http\Message\ResponseInterface as Response;
final class CartCheckoutRoutes
{
    use Support;
    public static function register(App $app,PDO $db,Auth $auth,ShopRepository $repo):void
    {
        $app->get('/api/cart',function(Request $r,Response $s)use($auth,$repo){$u=$auth->requireUser($r,['customer']);return Http::json($s,['cart'=>$repo->cart((int)$u['id'])]);});
        $app->post('/api/cart/items',function(Request $r,Response $s)use($db,$auth,$repo){$u=$auth->requireUser($r,['customer']);$d=self::body($r);self::required($d,['productVariantId','quantity']);$qty=(int)$d['quantity'];if($qty<1)throw new ApiException(422,'validation_failed','Quantity must be positive.',['quantity'=>'Use 1 or more.']);$v=self::one($db,"SELECT pv.*,p.status FROM product_variants pv JOIN products p ON p.id=pv.product_id WHERE pv.id=? AND p.status='active'",[(int)$d['productVariantId']],'variant_not_found');$cart=$repo->cart((int)$u['id']);$existing=self::all($db,'SELECT * FROM cart_items WHERE cart_id=? AND variant_id=?',[$cart['id'],$v['id']]);$next=$qty+(int)($existing[0]['quantity']??0);if($next>(int)$v['stock'])throw new ApiException(409,'insufficient_stock','Requested quantity exceeds available stock.');if($existing)$db->prepare('UPDATE cart_items SET quantity=? WHERE id=?')->execute([$next,$existing[0]['id']]);else$db->prepare('INSERT INTO cart_items(cart_id,variant_id,quantity) VALUES(?,?,?)')->execute([$cart['id'],$v['id'],$qty]);return Http::json($s,['cart'=>$repo->cart((int)$u['id'])],201);});
        $app->patch('/api/cart/items/{cartItemId}',function(Request $r,Response $s,array $a)use($db,$auth,$repo){$u=$auth->requireUser($r,['customer']);$d=self::body($r);self::required($d,['quantity']);$qty=(int)$d['quantity'];if($qty<1)throw new ApiException(422,'validation_failed','Quantity must be positive.',['quantity'=>'Use 1 or more.']);$x=self::one($db,'SELECT ci.*,pv.stock FROM cart_items ci JOIN carts c ON c.id=ci.cart_id JOIN product_variants pv ON pv.id=ci.variant_id WHERE ci.id=? AND c.customer_id=?',[(int)$a['cartItemId'],$u['id']],'cart_item_not_found');if($qty>(int)$x['stock'])throw new ApiException(409,'insufficient_stock','Requested quantity exceeds available stock.');$db->prepare('UPDATE cart_items SET quantity=? WHERE id=?')->execute([$qty,$x['id']]);return Http::json($s,['cart'=>$repo->cart((int)$u['id'])]);});
        $app->delete('/api/cart/items/{cartItemId}',function(Request $r,Response $s,array $a)use($db,$auth){$u=$auth->requireUser($r,['customer']);$x=self::one($db,'SELECT ci.id FROM cart_items ci JOIN carts c ON c.id=ci.cart_id WHERE ci.id=? AND c.customer_id=?',[(int)$a['cartItemId'],$u['id']],'cart_item_not_found');$db->prepare('DELETE FROM cart_items WHERE id=?')->execute([$x['id']]);return$s->withStatus(204);});

        $preview=function(array $u,array $d)use($db,$repo):array{self::required($d,['shippingAddressId','paymentMethodId']);if(!in_array($d['paymentMethodId'],['mock-card','mock-wallet'],true))throw new ApiException(422,'validation_failed','Unknown mock payment method.',['paymentMethodId'=>'Use mock-card or mock-wallet.']);$address=self::one($db,'SELECT * FROM addresses WHERE id=? AND user_id=?',[(int)$d['shippingAddressId'],$u['id']],'address_not_found');$cart=$repo->cart((int)$u['id']);if(!$cart['items'])throw new ApiException(409,'cart_empty','Cart is empty.');foreach($cart['items']as$item){if($item['product_status']!=='active')throw new ApiException(409,'product_unavailable','A cart product is not active.');if((int)$item['quantity']>(int)$item['stock'])throw new ApiException(409,'insufficient_stock','A cart item exceeds available stock.');}return['cart'=>$cart,'shippingAddress'=>$address,'paymentMethod'=>['id'=>$d['paymentMethodId'],'label'=>$d['paymentMethodId']==='mock-card'?'Offline test card':'Offline test wallet']];};
        $app->post('/api/checkout/preview',function(Request $r,Response $s)use($auth,$preview){$u=$auth->requireUser($r,['customer']);return Http::json($s,['preview'=>$preview($u,self::body($r))]);});
        $app->post('/api/orders',function(Request $r,Response $s)use($db,$auth,$repo,$preview){$u=$auth->requireUser($r,['customer']);$d=self::body($r);self::required($d,['shippingAddressId','paymentMethodId','idempotencyKey']);$key=trim((string)$d['idempotencyKey']);if($key==='')throw new ApiException(422,'validation_failed','Idempotency key is required.',['idempotencyKey'=>'Required.']);$existing=self::all($db,'SELECT id FROM orders WHERE customer_id=? AND idempotency_key=?',[$u['id'],$key]);if($existing)return Http::json($s,['order'=>$repo->order((int)$existing[0]['id'],$u)]);$checked=$preview($u,$d);$cart=$checked['cart'];$subtotal=(int)round($cart['subtotal']*100);$discount=(int)round($cart['discount']*100);$total=$subtotal-$discount;$db->beginTransaction();try{foreach($cart['items']as$item){$st=$db->prepare('UPDATE product_variants SET stock=stock-? WHERE id=? AND stock>=?');$st->execute([$item['quantity'],$item['variant_id'],$item['quantity']]);if($st->rowCount()!==1)throw new ApiException(409,'insufficient_stock','Stock changed during checkout.');}$db->prepare("INSERT INTO orders(customer_id,address_id,status,subtotal_cents,discount_cents,total_cents,promotion_id,idempotency_key) VALUES(?,?,'paid',?,?,?,?,?)")->execute([$u['id'],(int)$d['shippingAddressId'],$subtotal,$discount,$total,$cart['promotion']['id']??null,$key]);$orderId=(int)$db->lastInsertId();$itemSt=$db->prepare('INSERT INTO order_items(order_id,variant_id,seller_id,product_name,variant_name,quantity,unit_price_cents) SELECT ?,pv.id,p.seller_id,p.name,pv.name,?,pv.price_cents FROM product_variants pv JOIN products p ON p.id=pv.product_id WHERE pv.id=?');foreach($cart['items']as$item)$itemSt->execute([$orderId,$item['quantity'],$item['variant_id']]);$db->prepare("INSERT INTO payment_records(order_id,method_id,provider_reference,status,amount_cents) VALUES(?,?,?,'captured',?)")->execute([$orderId,$d['paymentMethodId'],'PAY-'.str_pad((string)$orderId,8,'0',STR_PAD_LEFT),$total]);$db->prepare('DELETE FROM cart_items WHERE cart_id=?')->execute([$cart['id']]);$db->prepare('UPDATE carts SET promotion_id=NULL,updated_at=datetime(\'now\') WHERE id=?')->execute([$cart['id']]);$db->commit();}catch(\Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}return Http::json($s,['order'=>$repo->order($orderId,$u)],201);});

        $app->get('/api/wishlist',function(Request $r,Response $s)use($db,$auth,$repo){$u=$auth->requireUser($r,['customer']);$rows=self::all($db,"SELECT p.*,c.name category,c.slug category_slug,sp.storefront_name seller_name FROM wishlist_items w JOIN products p ON p.id=w.product_id JOIN categories c ON c.id=p.category_id JOIN seller_profiles sp ON sp.user_id=p.seller_id WHERE w.customer_id=? AND p.status='active' ORDER BY w.created_at DESC,p.id DESC",[$u['id']]);foreach($rows as&$row)$row=$repo->productProjection($row);return Http::json($s,['items'=>$rows]);});
        $app->post('/api/wishlist/items',function(Request $r,Response $s)use($db,$auth,$repo){$u=$auth->requireUser($r,['customer']);$d=self::body($r);self::required($d,['productId']);$p=$repo->product((int)$d['productId'],true);$db->prepare('INSERT OR IGNORE INTO wishlist_items(customer_id,product_id) VALUES(?,?)')->execute([$u['id'],$p['id']]);return Http::json($s,['wishlistItem'=>['customer_id'=>$u['id'],'product_id'=>$p['id']]],201);});
        $app->delete('/api/wishlist/items/{productId}',function(Request $r,Response $s,array $a)use($db,$auth){$u=$auth->requireUser($r,['customer']);$st=$db->prepare('DELETE FROM wishlist_items WHERE customer_id=? AND product_id=?');$st->execute([$u['id'],(int)$a['productId']]);if($st->rowCount()===0)throw new ApiException(404,'wishlist_item_not_found','Wishlist item not found.');return$s->withStatus(204);});
        $app->get('/api/admin/promotions',function(Request $r,Response $s)use($db,$auth){$auth->requireUser($r,['admin']);return Http::json($s,['items'=>self::all($db,'SELECT * FROM promotions ORDER BY created_at DESC,id DESC')]);});
        $app->post('/api/admin/promotions',function(Request $r,Response $s)use($db,$auth){$u=$auth->requireUser($r,['admin']);$d=self::body($r);self::required($d,['code','discountType','discountValue','startsAt','endsAt']);if(!in_array($d['discountType'],['percent','fixed'],true))throw new ApiException(422,'validation_failed','Discount type is invalid.',['discountType'=>'Use percent or fixed.']);$value=$d['discountType']==='fixed'?self::cents($d['discountValue'],'discountValue'):(int)$d['discountValue'];if($value<=0||($d['discountType']==='percent'&&$value>100))throw new ApiException(422,'validation_failed','Discount value is invalid.',['discountValue'=>'Out of range.']);if(!strtotime($d['startsAt'])||!strtotime($d['endsAt'])||strtotime($d['startsAt'])>=strtotime($d['endsAt']))throw new ApiException(422,'validation_failed','Promotion window is invalid.',['startsAt'=>'Check the validity window.']);try{$db->prepare('INSERT INTO promotions(code,discount_type,discount_value,minimum_cents,starts_at,ends_at,active,created_by) VALUES(?,?,?,?,?,?,?,?)')->execute([strtoupper(trim($d['code'])),$d['discountType'],$value,isset($d['minimum'])?self::cents($d['minimum'],'minimum'):0,$d['startsAt'],$d['endsAt'],(int)($d['active']??1),$u['id']]);}catch(\PDOException){throw new ApiException(409,'promotion_exists','Promotion code already exists.');}$id=(int)$db->lastInsertId();return Http::json($s,['promotion'=>self::one($db,'SELECT * FROM promotions WHERE id=?',[$id])],201);});
        $app->post('/api/checkout/promotion',function(Request $r,Response $s)use($db,$auth,$repo){$u=$auth->requireUser($r,['customer']);$d=self::body($r);self::required($d,['code']);$p=self::one($db,"SELECT * FROM promotions WHERE code=? COLLATE NOCASE AND active=1 AND starts_at<=datetime('now') AND ends_at>=datetime('now')",[trim($d['code'])],'promotion_not_available');$cart=$repo->cart((int)$u['id']);$subtotal=(int)round($cart['subtotal']*100);if($subtotal<(int)$p['minimum_cents'])throw new ApiException(409,'promotion_ineligible','Cart does not meet the promotion minimum.');$db->prepare('UPDATE carts SET promotion_id=?,updated_at=datetime(\'now\') WHERE id=?')->execute([$p['id'],$cart['id']]);return Http::json($s,['cart'=>$repo->cart((int)$u['id'])]);});
    }
}
