<?php
declare(strict_types=1);
namespace App;
use PDO;use Slim\App;use Psr\Http\Message\ServerRequestInterface as Request;use Psr\Http\Message\ResponseInterface as Response;
final class CatalogRoutes
{
    use Support;
    public static function register(App $app,PDO $db,Auth $auth,ShopRepository $repo,array $cfg):void
    {
        $app->get('/api/products',function(Request $r,Response $s)use($db,$repo){$q=$r->getQueryParams();[$limit,$offset,$page]=self::page($r);$where=["p.status='active'"];$p=[];if(trim((string)($q['q']??''))!==''){$where[]='(p.name LIKE ? OR p.description LIKE ?)';$term='%'.trim($q['q']).'%';$p[]=$term;$p[]=$term;}if(trim((string)($q['category']??''))!==''){$where[]='(c.slug=? OR c.name=? COLLATE NOCASE)';$p[]=trim($q['category']);$p[]=trim($q['category']);}foreach(['minPrice'=>'>=','maxPrice'=>'<=']as$key=>$op)if(isset($q[$key])&&$q[$key]!==''){$where[]="p.price_cents $op ?";$p[]=self::cents($q[$key],$key);}if(filter_var($q['inStock']??false,FILTER_VALIDATE_BOOLEAN))$where[]='EXISTS(SELECT 1 FROM product_variants pv WHERE pv.product_id=p.id AND pv.stock>0)';$sql='SELECT p.*,c.name category,c.slug category_slug,sp.storefront_name seller_name FROM products p JOIN categories c ON c.id=p.category_id JOIN seller_profiles sp ON sp.user_id=p.seller_id WHERE '.implode(' AND ',$where).' ORDER BY p.name,p.id LIMIT ? OFFSET ?';$p[]=$limit;$p[]=$offset;$rows=self::all($db,$sql,$p);foreach($rows as&$row)$row=$repo->productProjection($row);return Http::json($s,['items'=>$rows,'page'=>$page,'limit'=>$limit]);});
        $app->get('/api/products/{productId}',function(Request $r,Response $s,array $a)use($repo){return Http::json($s,['product'=>$repo->product((int)$a['productId'],true)]);});
        $app->get('/api/product-images/{imageId}',function(Request $r,Response $s,array $a)use($db,$cfg){$image=self::one($db,"SELECT pi.* FROM product_images pi JOIN products p ON p.id=pi.product_id WHERE pi.id=? AND p.status='active'",[(int)$a['imageId']],'image_not_found');$dir=str_starts_with($cfg['uploadDir'],'/')?$cfg['uploadDir']:dirname(__DIR__).'/'.$cfg['uploadDir'];$path=$dir.'/'.$image['stored_name'];if(!is_file($path))throw new ApiException(404,'image_not_found','Product image is unavailable.');$s->getBody()->write((string)file_get_contents($path));return$s->withHeader('Content-Type',$image['mime_type'])->withHeader('Cache-Control','public, max-age=3600');});
        $app->get('/api/products/{productId}/reviews',function(Request $r,Response $s,array $a)use($db,$repo){$repo->product((int)$a['productId'],true);[$limit,$offset,$page]=self::page($r);$rows=self::all($db,"SELECT rv.id,rv.rating,rv.title,rv.body,rv.created_at,rv.updated_at,u.name author_name FROM reviews rv JOIN users u ON u.id=rv.customer_id WHERE rv.product_id=? AND rv.hidden=0 ORDER BY rv.created_at DESC,rv.id DESC LIMIT ? OFFSET ?",[(int)$a['productId'],$limit,$offset]);return Http::json($s,['items'=>$rows,'page'=>$page,'limit'=>$limit]);});
        $app->post('/api/products/{productId}/reviews',function(Request $r,Response $s,array $a)use($db,$auth,$repo){$u=$auth->requireUser($r,['customer']);$product=$repo->product((int)$a['productId'],true);$d=self::body($r);self::required($d,['rating','title','body']);$rating=(int)$d['rating'];if($rating<1||$rating>5)throw new ApiException(422,'validation_failed','Rating must be between 1 and 5.',['rating'=>'Out of range.']);$bought=$db->prepare("SELECT 1 FROM order_items oi JOIN orders o ON o.id=oi.order_id JOIN product_variants pv ON pv.id=oi.variant_id WHERE o.customer_id=? AND pv.product_id=? AND o.status IN ('paid','shipped','refund_requested','refunded')");$bought->execute([$u['id'],$product['id']]);if(!$bought->fetchColumn())throw new ApiException(403,'purchase_required','Only customers who purchased this product may review it.');try{$db->prepare('INSERT INTO reviews(product_id,customer_id,rating,title,body) VALUES(?,?,?,?,?)')->execute([$product['id'],$u['id'],$rating,trim($d['title']),trim($d['body'])]);}catch(\PDOException){throw new ApiException(409,'review_exists','You already reviewed this product.');}$id=(int)$db->lastInsertId();return Http::json($s,['review'=>self::one($db,'SELECT * FROM reviews WHERE id=?',[$id])],201);});
        $app->patch('/api/reviews/{reviewId}',function(Request $r,Response $s,array $a)use($db,$auth){$u=$auth->requireUser($r,['customer','moderator']);$review=self::one($db,'SELECT * FROM reviews WHERE id=?',[(int)$a['reviewId']],'review_not_found');$d=self::body($r);$sets=[];$p=[];if($u['role']==='moderator'){if(!array_key_exists('hidden',$d))throw new ApiException(422,'validation_failed','Moderators may only set moderation state.',['hidden'=>'Required.']);$sets=['hidden=?','moderation_reason=?'];$p=[(int)(bool)$d['hidden'],trim((string)($d['moderationReason']??''))];}else{if((int)$review['customer_id']!==(int)$u['id'])throw new ApiException(403,'review_access_denied','You may edit only your review.');foreach(['title','body']as$f)if(array_key_exists($f,$d)){$sets[]="$f=?";$p[]=trim((string)$d[$f]);}if(array_key_exists('rating',$d)){$rating=(int)$d['rating'];if($rating<1||$rating>5)throw new ApiException(422,'validation_failed','Rating must be between 1 and 5.',['rating'=>'Out of range.']);$sets[]='rating=?';$p[]=$rating;}}if(!$sets)throw new ApiException(422,'validation_failed','No supported review fields supplied.');$sets[]="updated_at=datetime('now')";$p[]=$review['id'];$db->prepare('UPDATE reviews SET '.implode(',',$sets).' WHERE id=?')->execute($p);return Http::json($s,['review'=>self::one($db,'SELECT * FROM reviews WHERE id=?',[$review['id']])]);});
        $app->delete('/api/reviews/{reviewId}',function(Request $r,Response $s,array $a)use($db,$auth){$u=$auth->requireUser($r,['customer','moderator']);$review=self::one($db,'SELECT * FROM reviews WHERE id=?',[(int)$a['reviewId']],'review_not_found');if($u['role']==='moderator')$db->prepare("UPDATE reviews SET hidden=1,moderation_reason='Removed by moderator',updated_at=datetime('now') WHERE id=?")->execute([$review['id']]);else{if((int)$review['customer_id']!==(int)$u['id'])throw new ApiException(403,'review_access_denied','You may delete only your review.');$db->prepare('DELETE FROM reviews WHERE id=?')->execute([$review['id']]);}return$s->withStatus(204);});
    }
}
