<?php
declare(strict_types=1);
namespace App;
use PDO;use Slim\App;use Psr\Http\Message\ServerRequestInterface as Request;use Psr\Http\Message\ResponseInterface as Response;
final class OrderRoutes
{
    use Support;
    public static function register(App $app,PDO $db,Auth $auth,ShopRepository $repo):void
    {
        $app->get('/api/orders',function(Request $r,Response $s)use($db,$auth,$repo){$u=$auth->requireUser($r,['customer','seller','admin']);[$limit,$offset,$page]=self::page($r);$sql='SELECT DISTINCT o.id FROM orders o';$p=[];if($u['role']==='seller'){$sql.=' JOIN order_items oi ON oi.order_id=o.id WHERE oi.seller_id=?';$p[]=$u['id'];}elseif($u['role']==='customer'){$sql.=' WHERE o.customer_id=?';$p[]=$u['id'];}$sql.=' ORDER BY o.created_at DESC,o.id DESC LIMIT ? OFFSET ?';$p[]=$limit;$p[]=$offset;$ids=self::all($db,$sql,$p);$items=[];foreach($ids as$id)$items[]=$repo->order((int)$id['id'],$u);return Http::json($s,['items'=>$items,'page'=>$page,'limit'=>$limit]);});
        $app->get('/api/orders/{orderId}',function(Request $r,Response $s,array $a)use($auth,$repo){$u=$auth->requireUser($r,['customer','seller','admin']);$base=$repo->order((int)$a['orderId']);$repo->requireOrderAccess($u,$base);return Http::json($s,['order'=>$repo->order((int)$a['orderId'],$u)]);});
        $app->get('/api/seller/orders',function(Request $r,Response $s)use($db,$auth,$repo){$u=$auth->requireUser($r,['seller','admin']);$q=$r->getQueryParams();[$limit,$offset,$page]=self::page($r);$sql='SELECT DISTINCT o.id FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE 1=1';$p=[];if($u['role']==='seller'){$sql.=' AND oi.seller_id=?';$p[]=$u['id'];}if(trim((string)($q['status']??''))!==''){$sql.=' AND o.status=?';$p[]=trim($q['status']);}$sql.=' ORDER BY o.created_at DESC,o.id DESC LIMIT ? OFFSET ?';$p[]=$limit;$p[]=$offset;$rows=self::all($db,$sql,$p);$items=[];foreach($rows as$x)$items[]=$repo->order((int)$x['id'],$u);return Http::json($s,['items'=>$items,'page'=>$page,'limit'=>$limit]);});

        $app->post('/api/orders/{orderId}/cancel',function(Request $r,Response $s,array $a)use($db,$auth,$repo){$u=$auth->requireUser($r,['customer','admin']);$o=$repo->order((int)$a['orderId']);if($u['role']==='customer'&&(int)$o['customer_id']!==(int)$u['id'])throw new ApiException(403,'order_access_denied','You cannot cancel this order.');if($o['status']==='cancelled')return Http::json($s,['order'=>$repo->order((int)$o['id'],$u)]);if($o['status']!=='paid')throw new ApiException(409,'invalid_order_state','Only a paid, unshipped order can be cancelled.');$d=self::body($r);self::required($d,['reason']);$db->beginTransaction();self::restoreStock($db,(int)$o['id']);$db->prepare("UPDATE orders SET status='cancelled',updated_at=datetime('now') WHERE id=?")->execute([$o['id']]);$db->prepare("INSERT INTO audit_events(actor_id,action,entity_type,entity_id,details) VALUES(?,'cancel','order',?,?)")->execute([$u['id'],$o['id'],trim($d['reason'])]);$db->commit();return Http::json($s,['order'=>$repo->order((int)$o['id'],$u)]);});
        $app->post('/api/orders/{orderId}/refund-requests',function(Request $r,Response $s,array $a)use($db,$auth,$repo){$u=$auth->requireUser($r,['customer']);$o=$repo->order((int)$a['orderId']);if((int)$o['customer_id']!==(int)$u['id'])throw new ApiException(403,'order_access_denied','You cannot request a refund for this order.');if(!in_array($o['status'],['paid','shipped','refund_requested'],true))throw new ApiException(409,'invalid_order_state','This order cannot enter refund review.');$d=self::body($r);self::required($d,['reason']);$existing=self::all($db,'SELECT * FROM refund_requests WHERE order_id=?',[$o['id']]);if($existing)return Http::json($s,['refundRequest'=>$existing[0]]);$db->beginTransaction();$db->prepare('INSERT INTO refund_requests(order_id,customer_id,reason) VALUES(?,?,?)')->execute([$o['id'],$u['id'],trim($d['reason'])]);$id=(int)$db->lastInsertId();$db->prepare("UPDATE orders SET status='refund_requested',updated_at=datetime('now') WHERE id=?")->execute([$o['id']]);$db->commit();return Http::json($s,['refundRequest'=>self::one($db,'SELECT * FROM refund_requests WHERE id=?',[$id])],201);});
        $app->post('/api/seller/orders/{orderId}/ship',function(Request $r,Response $s,array $a)use($db,$auth,$repo){$u=$auth->requireUser($r,['seller']);$o=$repo->order((int)$a['orderId']);$repo->requireOrderAccess($u,$o);if($o['status']!=='paid'&&$o['status']!=='shipped')throw new ApiException(409,'invalid_order_state','Only paid orders can be shipped.');$d=self::body($r);self::required($d,['carrier','trackingNumber']);$existing=self::all($db,'SELECT * FROM shipments WHERE order_id=? AND seller_id=?',[$o['id'],$u['id']]);if(!$existing){$db->beginTransaction();$db->prepare('INSERT INTO shipments(order_id,seller_id,carrier,tracking_number) VALUES(?,?,?,?)')->execute([$o['id'],$u['id'],trim($d['carrier']),trim($d['trackingNumber'])]);$sellerCount=(int)self::one($db,'SELECT COUNT(DISTINCT seller_id) n FROM order_items WHERE order_id=?',[$o['id']])['n'];$shipmentCount=(int)self::one($db,'SELECT COUNT(*) n FROM shipments WHERE order_id=?',[$o['id']])['n'];if($shipmentCount>=$sellerCount)$db->prepare("UPDATE orders SET status='shipped',updated_at=datetime('now') WHERE id=?")->execute([$o['id']]);$db->prepare("INSERT INTO audit_events(actor_id,action,entity_type,entity_id,details) VALUES(?,'ship','order',?,?)")->execute([$u['id'],$o['id'],trim($d['trackingNumber'])]);$db->commit();}return Http::json($s,['order'=>$repo->order((int)$o['id'],$u)]);});
        $app->post('/api/admin/orders/{orderId}/refund',function(Request $r,Response $s,array $a)use($db,$auth,$repo){$u=$auth->requireUser($r,['admin']);$o=$repo->order((int)$a['orderId']);if($o['status']==='refunded')return Http::json($s,['order'=>$repo->order((int)$o['id'],$u)]);if(!in_array($o['status'],['paid','shipped','refund_requested'],true))throw new ApiException(409,'invalid_order_state','This order cannot be refunded.');$d=self::body($r);self::required($d,['reason']);$db->beginTransaction();self::restoreStock($db,(int)$o['id']);$db->prepare("UPDATE orders SET status='refunded',updated_at=datetime('now') WHERE id=?")->execute([$o['id']]);$db->prepare("UPDATE payment_records SET status='refunded',updated_at=datetime('now') WHERE order_id=?")->execute([$o['id']]);$db->prepare("UPDATE refund_requests SET status='approved' WHERE order_id=?")->execute([$o['id']]);$db->prepare("INSERT INTO audit_events(actor_id,action,entity_type,entity_id,details) VALUES(?,'refund','order',?,?)")->execute([$u['id'],$o['id'],trim($d['reason'])]);$db->commit();return Http::json($s,['order'=>$repo->order((int)$o['id'],$u)]);});
    }
    private static function restoreStock(PDO $db,int $orderId):void{$rows=self::all($db,'SELECT variant_id,quantity FROM order_items WHERE order_id=?',[$orderId]);$st=$db->prepare('UPDATE product_variants SET stock=stock+? WHERE id=?');foreach($rows as$row)$st->execute([$row['quantity'],$row['variant_id']]);}
}
