<?php
declare(strict_types=1);
namespace App;
use PDO;use Slim\App;use Psr\Http\Message\ServerRequestInterface as Request;use Psr\Http\Message\ResponseInterface as Response;
final class SellerAdminRoutes
{
    use Support;
    public static function register(App $app,PDO $db,Auth $auth,ShopRepository $repo,array $cfg):void
    {
        $app->post('/api/seller/products',function(Request $r,Response $s)use($db,$auth,$repo){$u=$auth->requireUser($r,['seller','admin']);$d=self::body($r);self::required($d,['name','description','categoryId','price','variants']);$sellerId=$u['role']==='admin'?(int)($d['sellerId']??0):(int)$u['id'];if(!$sellerId)throw new ApiException(422,'validation_failed','Admin must select a seller.',['sellerId'=>'Required.']);$seller=self::one($db,"SELECT * FROM seller_profiles WHERE user_id=? AND approval_status='approved'",[$sellerId],'seller_not_approved');self::one($db,'SELECT id FROM categories WHERE id=?',[(int)$d['categoryId']],'category_not_found');if(!is_array($d['variants'])||!count($d['variants']))throw new ApiException(422,'validation_failed','At least one variant is required.',['variants'=>'Required.']);$price=self::cents($d['price']);$status=($d['status']??'draft');if(!in_array($status,['draft','active'],true))throw new ApiException(422,'validation_failed','Invalid product status.',['status'=>'Use draft or active.']);$db->beginTransaction();try{$db->prepare('INSERT INTO products(seller_id,category_id,name,description,price_cents,status) VALUES(?,?,?,?,?,?)')->execute([$sellerId,(int)$d['categoryId'],trim($d['name']),trim($d['description']),$price,$status]);$id=(int)$db->lastInsertId();$st=$db->prepare('INSERT INTO product_variants(product_id,sku,name,price_cents,stock) VALUES(?,?,?,?,?)');foreach($d['variants']as$v){self::required($v,['sku','name','price','stock']);$stock=(int)$v['stock'];if($stock<0)throw new ApiException(422,'validation_failed','Stock cannot be negative.',['stock'=>'Invalid.']);$st->execute([$id,trim($v['sku']),trim($v['name']),self::cents($v['price']),$stock]);}$db->commit();}catch(\Throwable$e){if($db->inTransaction())$db->rollBack();if($e instanceof ApiException)throw$e;throw new ApiException(409,'product_conflict','A SKU or product value conflicts with existing data.');}return Http::json($s,['product'=>$repo->product($id)],201);});
        $app->patch('/api/seller/products/{productId}',function(Request $r,Response $s,array $a)use($db,$auth,$repo){$u=$auth->requireUser($r,['seller','admin']);$p=$repo->product((int)$a['productId']);$repo->requireProductManager($u,$p);$d=self::body($r);if(isset($d['version'])&&(int)$d['version']!==(int)$p['version'])throw new ApiException(409,'stale_version','Product changed in another request.');$map=['name'=>'name','description'=>'description','categoryId'=>'category_id','status'=>'status'];$sets=[];$params=[];foreach($map as$in=>$col)if(array_key_exists($in,$d)){if($in==='status'&&!in_array($d[$in],['draft','active','hidden'],true))throw new ApiException(422,'validation_failed','Invalid product status.',['status'=>'Invalid.']);$sets[]="$col=?";$params[]=$in==='categoryId'?(int)$d[$in]:trim((string)$d[$in]);}if(array_key_exists('price',$d)){$sets[]='price_cents=?';$params[]=self::cents($d['price']);}if(!$sets)throw new ApiException(422,'validation_failed','No supported product fields supplied.');$sets[]='version=version+1';$sets[]="updated_at=datetime('now')";$params[]=$p['id'];$db->prepare('UPDATE products SET '.implode(',',$sets).' WHERE id=?')->execute($params);return Http::json($s,['product'=>$repo->product((int)$p['id'])]);});
        $app->post('/api/seller/products/{productId}/images',function(Request $r,Response $s,array $a)use($db,$auth,$repo,$cfg){$u=$auth->requireUser($r,['seller','admin']);$p=$repo->product((int)$a['productId']);$repo->requireProductManager($u,$p);$files=$r->getUploadedFiles();if(!isset($files['image'])||$files['image']->getError()!==UPLOAD_ERR_OK)throw new ApiException(422,'validation_failed','An image is required.',['image'=>'Required.']);$f=$files['image'];$mime=(string)$f->getClientMediaType();$extensions=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($extensions[$mime]))throw new ApiException(422,'validation_failed','Image must be JPEG, PNG, or WebP.',['image'=>'Unsupported type.']);if((int)$f->getSize()>$cfg['maxUpload'])throw new ApiException(422,'validation_failed','Image is too large.',['image'=>'Above configured maximum.']);$dir=str_starts_with($cfg['uploadDir'],'/')?$cfg['uploadDir']:dirname(__DIR__).'/'.$cfg['uploadDir'];if(!is_dir($dir))mkdir($dir,0775,true);$stored=bin2hex(random_bytes(16)).'.'.$extensions[$mime];$f->moveTo($dir.'/'.$stored);$db->prepare('INSERT INTO product_images(product_id,original_name,stored_name,mime_type,size_bytes) VALUES(?,?,?,?,?)')->execute([$p['id'],(string)$f->getClientFilename(),$stored,$mime,$f->getSize()]);$id=(int)$db->lastInsertId();return Http::json($s,['image'=>self::one($db,'SELECT id,product_id,original_name,mime_type,size_bytes,created_at FROM product_images WHERE id=?',[$id])],201);});
        $app->delete('/api/seller/products/{productId}/images/{imageId}',function(Request $r,Response $s,array $a)use($db,$auth,$repo,$cfg){$u=$auth->requireUser($r,['seller','admin']);$p=$repo->product((int)$a['productId']);$repo->requireProductManager($u,$p);$image=self::one($db,'SELECT * FROM product_images WHERE id=? AND product_id=?',[(int)$a['imageId'],$p['id']],'image_not_found');$db->prepare('DELETE FROM product_images WHERE id=?')->execute([$image['id']]);$dir=str_starts_with($cfg['uploadDir'],'/')?$cfg['uploadDir']:dirname(__DIR__).'/'.$cfg['uploadDir'];$path=$dir.'/'.$image['stored_name'];if(is_file($path))unlink($path);return$s->withStatus(204);});
        $app->post('/api/admin/categories',function(Request $r,Response $s)use($db,$auth){$auth->requireUser($r,['admin']);$d=self::body($r);self::required($d,['name','slug']);if(!preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/',$d['slug']))throw new ApiException(422,'validation_failed','Slug is invalid.',['slug'=>'Use lowercase letters, numbers, and hyphens.']);try{$db->prepare('INSERT INTO categories(name,slug) VALUES(?,?)')->execute([trim($d['name']),$d['slug']]);}catch(\PDOException){throw new ApiException(409,'category_exists','Category name or slug already exists.');}$id=(int)$db->lastInsertId();return Http::json($s,['category'=>self::one($db,'SELECT * FROM categories WHERE id=?',[$id])],201);});

        $app->get('/api/seller/inventory',function(Request $r,Response $s)use($db,$auth){$u=$auth->requireUser($r,['seller','admin']);$sql='SELECT pv.id variant_id,pv.sku,pv.name variant_name,pv.stock,p.id product_id,p.name product_name,p.seller_id FROM product_variants pv JOIN products p ON p.id=pv.product_id';$params=[];if($u['role']==='seller'){$sql.=' WHERE p.seller_id=?';$params[]=$u['id'];}return Http::json($s,['items'=>self::all($db,$sql.' ORDER BY p.id,pv.id',$params)]);});
        $app->post('/api/seller/inventory/{variantId}/adjustments',function(Request $r,Response $s,array $a)use($db,$auth){$u=$auth->requireUser($r,['seller','admin']);$v=self::one($db,'SELECT pv.*,p.seller_id FROM product_variants pv JOIN products p ON p.id=pv.product_id WHERE pv.id=?',[(int)$a['variantId']],'variant_not_found');if($u['role']==='seller'&&(int)$v['seller_id']!==(int)$u['id'])throw new ApiException(403,'inventory_access_denied','You cannot adjust this inventory.');$d=self::body($r);self::required($d,['delta','reason','reference']);$delta=(int)$d['delta'];if($delta===0)throw new ApiException(422,'validation_failed','Adjustment delta cannot be zero.',['delta'=>'Non-zero required.']);if((int)$v['stock']+$delta<0)throw new ApiException(409,'insufficient_stock','Adjustment would make stock negative.');$db->beginTransaction();try{$db->prepare('INSERT INTO inventory_adjustments(variant_id,actor_id,delta,reason,reference) VALUES(?,?,?,?,?)')->execute([$v['id'],$u['id'],$delta,trim($d['reason']),trim($d['reference'])]);$id=(int)$db->lastInsertId();$db->prepare('UPDATE product_variants SET stock=stock+? WHERE id=?')->execute([$delta,$v['id']]);$db->commit();}catch(\PDOException){if($db->inTransaction())$db->rollBack();throw new ApiException(409,'adjustment_exists','This inventory reference was already applied.');}return Http::json($s,['adjustment'=>self::one($db,'SELECT * FROM inventory_adjustments WHERE id=?',[$id]),'stock'=>(int)$v['stock']+$delta],201);});

        $app->get('/api/seller/storefront',function(Request $r,Response $s)use($db,$auth){$u=$auth->requireUser($r,['seller','admin']);$id=$u['role']==='admin'?(int)($r->getQueryParams()['sellerId']??0):(int)$u['id'];if(!$id)throw new ApiException(422,'validation_failed','Admin must select a seller.',['sellerId'=>'Required.']);return Http::json($s,['storefront'=>self::one($db,'SELECT * FROM seller_profiles WHERE user_id=?',[$id],'seller_not_found')]);});
        $app->patch('/api/seller/storefront',function(Request $r,Response $s)use($db,$auth){$u=$auth->requireUser($r,['seller','admin']);$d=self::body($r);$id=$u['role']==='admin'?(int)($d['sellerId']??0):(int)$u['id'];$x=self::one($db,'SELECT * FROM seller_profiles WHERE user_id=?',[$id],'seller_not_found');$map=['storefrontName'=>'storefront_name','description'=>'description','supportEmail'=>'support_email'];$sets=[];$p=[];foreach($map as$in=>$col)if(array_key_exists($in,$d)){$sets[]="$col=?";$p[]=trim((string)$d[$in]);}if(!$sets)throw new ApiException(422,'validation_failed','No supported storefront fields supplied.');$p[]=$x['user_id'];$db->prepare('UPDATE seller_profiles SET '.implode(',',$sets).' WHERE user_id=?')->execute($p);return Http::json($s,['storefront'=>self::one($db,'SELECT * FROM seller_profiles WHERE user_id=?',[$x['user_id']])]);});
        $app->get('/api/admin/sellers',function(Request $r,Response $s)use($db,$auth){$auth->requireUser($r,['admin']);[$limit,$offset,$page]=self::page($r);$rows=self::all($db,'SELECT u.id,u.email,u.name,sp.storefront_name,sp.description,sp.support_email,sp.approval_status,sp.approved_at FROM seller_profiles sp JOIN users u ON u.id=sp.user_id ORDER BY u.id LIMIT ? OFFSET ?',[$limit,$offset]);return Http::json($s,['items'=>$rows,'page'=>$page,'limit'=>$limit]);});
        $app->post('/api/admin/sellers/{sellerId}/approve',function(Request $r,Response $s,array $a)use($db,$auth){$u=$auth->requireUser($r,['admin']);$seller=self::one($db,'SELECT * FROM seller_profiles WHERE user_id=?',[(int)$a['sellerId']],'seller_not_found');if($seller['approval_status']!=='approved'){$db->prepare("UPDATE seller_profiles SET approval_status='approved',approved_at=datetime('now') WHERE user_id=?")->execute([$seller['user_id']]);$db->prepare("INSERT INTO audit_events(actor_id,action,entity_type,entity_id) VALUES(?,'approve','seller',?)")->execute([$u['id'],$seller['user_id']]);}return Http::json($s,['seller'=>self::one($db,'SELECT * FROM seller_profiles WHERE user_id=?',[$seller['user_id']])]);});
        $app->post('/api/admin/products/{productId}/moderate',function(Request $r,Response $s,array $a)use($db,$auth,$repo){$u=$auth->requireUser($r,['admin']);$p=$repo->product((int)$a['productId']);$d=self::body($r);self::required($d,['status','reason']);if(!in_array($d['status'],['active','hidden'],true))throw new ApiException(422,'validation_failed','Moderation status is invalid.',['status'=>'Use active or hidden.']);$db->beginTransaction();$db->prepare("UPDATE products SET status=?,moderation_reason=?,version=version+1,updated_at=datetime('now') WHERE id=?")->execute([$d['status'],trim($d['reason']),$p['id']]);$db->prepare("INSERT INTO audit_events(actor_id,action,entity_type,entity_id,details) VALUES(?,'moderate','product',?,?)")->execute([$u['id'],$p['id'],trim($d['reason'])]);$db->commit();return Http::json($s,['product'=>$repo->product((int)$p['id'])]);});

        $report=function(Request $r,Response $s,bool $admin)use($db,$auth){$u=$auth->requireUser($r,[$admin?'admin':'seller']);$q=$r->getQueryParams();$group=$q['groupBy']??'day';if(!in_array($group,['day','month','product'],true))throw new ApiException(422,'validation_failed','Unsupported report grouping.',['groupBy'=>'Use day, month, or product.']);$from=trim((string)($q['from']??'2020-01-01'));$to=trim((string)($q['to']??'2035-12-31'));if(!strtotime($from)||!strtotime($to)||strtotime($from)>strtotime($to))throw new ApiException(422,'validation_failed','Invalid report range.',['from'=>'Check date range.']);$expr=$group==='day'?"date(o.created_at)":($group==='month'?"strftime('%Y-%m',o.created_at)":'oi.product_name');$sql="SELECT $expr label,SUM(oi.quantity) units,SUM(oi.quantity*oi.unit_price_cents)/100.0 gross FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.status NOT IN ('cancelled','refunded') AND date(o.created_at) BETWEEN date(?) AND date(?)";$p=[$from,$to];if(!$admin){$sql.=' AND oi.seller_id=?';$p[]=$u['id'];}$sql.=" GROUP BY $expr ORDER BY label";return Http::json($s,['from'=>$from,'to'=>$to,'groupBy'=>$group,'items'=>self::all($db,$sql,$p)]);};
        $app->get('/api/seller/reports/sales',fn(Request $r,Response $s)=>$report($r,$s,false));
        $app->get('/api/admin/reports/sales',fn(Request $r,Response $s)=>$report($r,$s,true));
    }
}
