<?php
declare(strict_types=1);namespace App;use PDO;use Slim\App;final class Routes{public static function register(App$app,PDO$db,Auth$auth,SystemRepository$repo,array$c):void{$ok=fn($r,$d,$s=200)=>Http::json($r,$d,$s);$duplicate=function(callable$f):void{try{$f();}catch(\PDOException$e){if($e->getCode()==='23000')throw new ApiException(409,'conflict','Resource already exists.');throw$e;}};$version=function(array$d,array$x):void{if(isset($d['version'])&&(int)$d['version']!==(int)$x['version'])throw new ApiException(409,'stale_version','Resource version is stale.');};$range=function(array$p):array{if(!isset($p['from'],$p['to'])||strtotime($p['from'])===false||strtotime($p['to'])===false||$p['from']>$p['to'])throw new ApiException(422,'validation_error','Invalid time range.',['from'=>'must precede to']);return[$p['from'],$p['to']];};
// SYS-01
$app->post('/api/auth/login',function($q,$r)use($auth,$ok){$d=Http::body($q);Http::required($d,['email','password']);[$u,$t]=$auth->login($d['email'],$d['password']);return$ok($r,['user'=>$u])->withHeader('Set-Cookie',$auth->cookie.'='.rawurlencode($t).'; Path=/; HttpOnly; SameSite=Lax');});
$app->post('/api/auth/logout',function($q,$r)use($auth,$ok){$auth->user($q);$auth->logout($q);return$ok($r,['logged_out'=>true])->withHeader('Set-Cookie',$auth->cookie.'=; Path=/; HttpOnly; Max-Age=0; SameSite=Lax');});
$app->post('/api/auth/password-reset-requests',function($q,$r)use($db,$c,$ok){$d=Http::body($q);Http::required($d,['email']);$s=$db->prepare('SELECT id FROM users WHERE email=? AND status="active"');$s->execute([strtolower($d['email'])]);$u=$s->fetch();$token=null;if($u){$token='reset-'.bin2hex(random_bytes(5));$db->prepare('INSERT INTO reset_tokens(user_id,token_hash,expires_at) VALUES(?,?,?)')->execute([$u['id'],hash('sha256',$token),gmdate(DATE_ATOM,time()+$c['resetTtl'])]);}return$ok($r,['accepted'=>true,'reset_token'=>$c['appEnv']==='test'?$token:null],201);});
$app->post('/api/auth/password-resets',function($q,$r)use($db,$ok){$d=Http::body($q);Http::required($d,['token','password']);if(strlen($d['password'])<10)throw new ApiException(422,'validation_error','Invalid password.',['password'=>'minimum 10 characters']);$s=$db->prepare('SELECT * FROM reset_tokens WHERE token_hash=?');$s->execute([hash('sha256',$d['token'])]);$t=$s->fetch();if(!$t||$t['used_at']!==null||$t['expires_at']<=gmdate(DATE_ATOM))throw new ApiException(409,'invalid_reset_token','Reset token is invalid or expired.');$db->beginTransaction();$db->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($d['password'],PASSWORD_DEFAULT),$t['user_id']]);$db->prepare('UPDATE reset_tokens SET used_at=? WHERE id=?')->execute([gmdate(DATE_ATOM),$t['id']]);$db->prepare('DELETE FROM sessions WHERE user_id=?')->execute([$t['user_id']]);$db->commit();return$ok($r,['password_reset'=>true]);});
// SYS-02
$app->get('/api/servers',function($q,$r)use($auth,$repo,$ok){$auth->user($q,['operator']);return$ok($r,['items'=>$repo->rows('SELECT * FROM servers ORDER BY id')]);});
$app->get('/api/servers/{id}',function($q,$r,$a)use($auth,$repo,$ok){$auth->user($q,['operator']);$s=$repo->server((int)$a['id']);$services=$repo->rows('SELECT status,COUNT(*) count FROM services WHERE server_id=? GROUP BY status',[$s['id']]);return$ok($r,['server'=>$s,'service_summary'=>$services]);});
$app->get('/api/servers/{id}/metrics',function($q,$r,$a)use($auth,$repo,$range,$ok){$auth->user($q,['operator']);$s=$repo->server((int)$a['id']);$p=$q->getQueryParams();[$from,$to]=$range($p);if(!in_array($p['interval']??null,['hour','day'],true))throw new ApiException(422,'validation_error','Invalid interval.',['interval'=>'hour or day']);return$ok($r,['server_id'=>(int)$s['id'],'interval'=>$p['interval'],'items'=>$repo->rows('SELECT sampled_at,cpu,memory,disk,load_average FROM metric_samples WHERE server_id=? AND sampled_at>=? AND sampled_at<=? ORDER BY sampled_at',[$s['id'],$from,$to])]);});
// SYS-03
$app->get('/api/servers/{id}/log-sources',function($q,$r,$a)use($auth,$repo,$ok){$auth->user($q,['operator']);$s=$repo->server((int)$a['id']);return$ok($r,['items'=>$repo->rows('SELECT * FROM log_sources WHERE server_id=? ORDER BY id',[$s['id']])]);});
$app->get('/api/servers/{id}/logs',function($q,$r,$a)use($auth,$repo,$ok){$auth->user($q,['operator']);$s=$repo->server((int)$a['id']);$p=$q->getQueryParams();if(!isset($p['sourceId']))throw new ApiException(422,'validation_error','Log source required.',['sourceId'=>'required']);$source=$repo->one('SELECT * FROM log_sources WHERE id=? AND server_id=?',[(int)$p['sourceId'],$s['id']]);$level=(string)($p['level']??'');if($level!==''&&!in_array($level,['debug','info','warning','error'],true))throw new ApiException(422,'validation_error','Invalid level.',['level'=>'unsupported']);$limit=(int)($p['limit']??50);if($limit<1||$limit>100)throw new ApiException(422,'validation_error','Invalid limit.',['limit'=>'must be 1..100']);$before=(string)($p['before']??'9999-12-31T23:59:59Z');if(strtotime($before)===false)throw new ApiException(422,'validation_error','Invalid cursor.',['before'=>'date-time required']);$term='%'.trim((string)($p['q']??'')).'%';$args=[$source['id'],$before,$term];$sql='SELECT * FROM log_entries WHERE source_id=? AND created_at<? AND message LIKE ?';if($level!==''){$sql.=' AND level=?';$args[]=$level;}$sql.=' ORDER BY created_at DESC,id DESC LIMIT ?';$args[]=$limit;return$ok($r,['items'=>$repo->rows($sql,$args)]);});
// SYS-04
$app->get('/api/servers/{id}/services',function($q,$r,$a)use($auth,$repo,$ok){$auth->user($q,['operator','admin']);$s=$repo->server((int)$a['id']);return$ok($r,['items'=>$repo->rows('SELECT * FROM services WHERE server_id=? ORDER BY id',[$s['id']])]);});
$app->get('/api/services/{id}',function($q,$r,$a)use($auth,$repo,$ok){$auth->user($q,['operator','admin']);return$ok($r,$repo->one('SELECT * FROM services WHERE id=?',[(int)$a['id']]));});
$app->post('/api/services/{id}/actions',function($q,$r,$a)use($auth,$repo,$db,$duplicate,$ok){$u=$auth->user($q,['operator','admin']);$s=$repo->one('SELECT * FROM services WHERE id=?',[(int)$a['id']]);$d=Http::body($q);Http::required($d,['action','idempotency_key']);if(!in_array($d['action'],['start','stop','restart'],true))throw new ApiException(422,'validation_error','Invalid service action.',['action'=>'start, stop, or restart']);if(($d['action']==='start'&&$s['status']==='running')||($d['action']==='stop'&&$s['status']==='stopped'))throw new ApiException(409,'invalid_state','Service is already in the requested state.');$status=$d['action']==='stop'?'stopped':'running';$db->beginTransaction();try{$duplicate(fn()=>$db->prepare('INSERT INTO service_actions(service_id,actor_id,action,status,idempotency_key,created_at) VALUES(?,?,?,"succeeded",?,?)')->execute([$s['id'],$u['id'],$d['action'],$d['idempotency_key'],gmdate(DATE_ATOM)]));$id=(int)$db->lastInsertId();$db->prepare('UPDATE services SET status=?,version=version+1 WHERE id=?')->execute([$status,$s['id']]);$repo->audit((int)$u['id'],(int)$s['server_id'],'service.'.$d['action'],$s['name']);$db->commit();}catch(\Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}return$ok($r,$repo->one('SELECT * FROM service_actions WHERE id=?',[$id]));});
// SYS-05
$app->get('/api/servers/{id}/jobs',function($q,$r,$a)use($auth,$repo,$ok){$auth->user($q,['operator','admin']);$s=$repo->server((int)$a['id']);return$ok($r,['items'=>$repo->rows('SELECT * FROM scheduled_jobs WHERE server_id=? ORDER BY id',[$s['id']])]);});
$app->post('/api/servers/{id}/jobs',function($q,$r,$a)use($auth,$repo,$db,$duplicate,$ok){$auth->user($q,['operator','admin']);$s=$repo->server((int)$a['id']);$d=Http::body($q);Http::required($d,['name','command','schedule']);if(!in_array($d['command'],['cleanup','backup','health-check'],true))throw new ApiException(422,'validation_error','Command is not allow-listed.',['command'=>'unsupported']);if(!preg_match('/^(\S+\s+){4}\S+$/',$d['schedule']))throw new ApiException(422,'validation_error','Invalid schedule.',['schedule'=>'five cron fields required']);$duplicate(fn()=>$db->prepare('INSERT INTO scheduled_jobs(server_id,name,command,schedule,status) VALUES(?,?,?,?,"active")')->execute([$s['id'],$d['name'],$d['command'],$d['schedule']]));return$ok($r,$repo->one('SELECT * FROM scheduled_jobs WHERE id=?',[(int)$db->lastInsertId()]),201);});
$app->patch('/api/jobs/{id}',function($q,$r,$a)use($auth,$repo,$db,$version,$ok){$auth->user($q,['operator','admin']);$x=$repo->one('SELECT * FROM scheduled_jobs WHERE id=?',[(int)$a['id']]);$d=Http::body($q);$version($d,$x);if(isset($d['command'])&&!in_array($d['command'],['cleanup','backup','health-check'],true))throw new ApiException(422,'validation_error','Command is not allow-listed.',['command'=>'unsupported']);$schedule=(string)($d['schedule']??$x['schedule']);if(!preg_match('/^(\S+\s+){4}\S+$/',$schedule))throw new ApiException(422,'validation_error','Invalid schedule.',['schedule'=>'five cron fields required']);$db->prepare('UPDATE scheduled_jobs SET name=?,command=?,schedule=?,version=version+1 WHERE id=?')->execute([(string)($d['name']??$x['name']),(string)($d['command']??$x['command']),$schedule,$x['id']]);return$ok($r,$repo->one('SELECT * FROM scheduled_jobs WHERE id=?',[$x['id']]));});
$state=function($q,$r,$a,string$from,string$to)use($auth,$repo,$db,$ok){$auth->user($q,['operator','admin']);$x=$repo->one('SELECT * FROM scheduled_jobs WHERE id=?',[(int)$a['id']]);if($x['status']!==$from)throw new ApiException(409,'invalid_state','Job cannot make this transition.');$db->prepare('UPDATE scheduled_jobs SET status=?,version=version+1 WHERE id=?')->execute([$to,$x['id']]);return$ok($r,$repo->one('SELECT * FROM scheduled_jobs WHERE id=?',[$x['id']]));};
$app->post('/api/jobs/{id}/pause',fn($q,$r,$a)=>$state($q,$r,$a,'active','paused'));
$app->post('/api/jobs/{id}/resume',fn($q,$r,$a)=>$state($q,$r,$a,'paused','active'));
$app->delete('/api/jobs/{id}',function($q,$r,$a)use($auth,$repo,$db){$auth->user($q,['operator','admin']);$x=$repo->one('SELECT * FROM scheduled_jobs WHERE id=?',[(int)$a['id']]);if($x['status']==='active')throw new ApiException(409,'invalid_state','Pause the job before deletion.');$db->prepare('DELETE FROM scheduled_jobs WHERE id=?')->execute([$x['id']]);return$r->withStatus(204);});
// SYS-06
$app->get('/api/jobs/{id}/runs',function($q,$r,$a)use($auth,$repo,$ok){$auth->user($q,['operator']);$j=$repo->one('SELECT * FROM scheduled_jobs WHERE id=?',[(int)$a['id']]);return$ok($r,['items'=>$repo->rows('SELECT * FROM job_runs WHERE job_id=? ORDER BY id DESC',[$j['id']])]);});
$app->get('/api/job-runs/{id}',function($q,$r,$a)use($auth,$repo,$ok){$auth->user($q,['operator']);return$ok($r,$repo->one('SELECT * FROM job_runs WHERE id=?',[(int)$a['id']]));});
$app->post('/api/jobs/{id}/runs',function($q,$r,$a)use($auth,$repo,$db,$duplicate,$ok){$auth->user($q,['operator']);$j=$repo->one('SELECT * FROM scheduled_jobs WHERE id=?',[(int)$a['id']]);if($j['status']!=='active')throw new ApiException(409,'invalid_state','Paused job cannot run.');$d=Http::body($q);Http::required($d,['idempotency_key']);$now=gmdate(DATE_ATOM);$duplicate(fn()=>$db->prepare('INSERT INTO job_runs(job_id,status,output,started_at,finished_at,idempotency_key) VALUES(?,"succeeded",?,?,?,?)')->execute([$j['id'],'Command '.$j['command'].' completed; secrets=[REDACTED]',$now,$now,$d['idempotency_key']]));return$ok($r,$repo->one('SELECT * FROM job_runs WHERE id=?',[(int)$db->lastInsertId()]),201);});
// SYS-07
$app->get('/api/servers/{id}/backups',function($q,$r,$a)use($auth,$repo,$ok){$auth->user($q,['operator','admin']);$s=$repo->server((int)$a['id']);return$ok($r,['items'=>$repo->rows('SELECT id,server_id,kind,status,created_at FROM backups WHERE server_id=? ORDER BY id DESC',[$s['id']])]);});
$app->post('/api/servers/{id}/backups',function($q,$r,$a)use($auth,$repo,$db,$duplicate,$ok){$auth->user($q,['operator','admin']);$s=$repo->server((int)$a['id']);$d=Http::body($q);Http::required($d,['kind','idempotency_key']);if(!in_array($d['kind'],['configuration','data'],true))throw new ApiException(422,'validation_error','Invalid backup kind.',['kind'=>'configuration or data']);$content=json_encode(['server'=>$s['name'],'kind'=>$d['kind'],'captured'=>true],JSON_THROW_ON_ERROR);$duplicate(fn()=>$db->prepare('INSERT INTO backups(server_id,kind,status,content,created_at,idempotency_key) VALUES(?,?,"ready",?,?,?)')->execute([$s['id'],$d['kind'],$content,gmdate(DATE_ATOM),$d['idempotency_key']]));return$ok($r,$repo->one('SELECT id,server_id,kind,status,created_at FROM backups WHERE id=?',[(int)$db->lastInsertId()]),201);});
$app->get('/api/backups/{id}/content',function($q,$r,$a)use($auth,$repo,$ok){$auth->user($q,['operator','admin']);$x=$repo->one('SELECT * FROM backups WHERE id=?',[(int)$a['id']]);if($x['status']!=='ready')throw new ApiException(409,'invalid_state','Backup is not ready.');return$ok($r,['backup_id'=>(int)$x['id'],'content'=>$x['content']]);});
$app->post('/api/backups/{id}/restore',function($q,$r,$a)use($auth,$repo,$db,$ok){$u=$auth->user($q,['operator','admin']);$x=$repo->one('SELECT * FROM backups WHERE id=?',[(int)$a['id']]);if($x['status']!=='ready')throw new ApiException(409,'invalid_state','Backup is not ready.');$db->prepare('INSERT INTO restore_jobs(backup_id,status,created_at) VALUES(?,"succeeded",?)')->execute([$x['id'],gmdate(DATE_ATOM)]);$restoreId=(int)$db->lastInsertId();$repo->audit((int)$u['id'],(int)$x['server_id'],'backup.restored','Backup '.$x['id']);return$ok($r,$repo->one('SELECT * FROM restore_jobs WHERE id=?',[$restoreId]));});
// SYS-08
$app->get('/api/servers/{id}/configuration',function($q,$r,$a)use($auth,$repo,$ok){$auth->user($q,['admin']);$s=$repo->server((int)$a['id']);$x=$repo->one('SELECT * FROM configuration_versions WHERE server_id=? ORDER BY version DESC LIMIT 1',[$s['id']]);$x['settings']=json_decode($x['settings'],true);return$ok($r,$x);});
$app->patch('/api/servers/{id}/configuration',function($q,$r,$a)use($auth,$repo,$db,$ok){$u=$auth->user($q,['admin']);$s=$repo->server((int)$a['id']);$current=$repo->one('SELECT * FROM configuration_versions WHERE server_id=? ORDER BY version DESC LIMIT 1',[$s['id']]);$d=Http::body($q);if(!isset($d['version'])||(int)$d['version']!==(int)$current['version'])throw new ApiException(409,'stale_version','Configuration version is stale.');$settings=$d['settings']??null;if(!is_array($settings)||array_diff(array_keys($settings),['max_workers','maintenance_mode','log_level']))throw new ApiException(422,'validation_error','Invalid settings.',['settings'=>'allow-listed object required']);$old=json_decode($current['settings'],true);$merged=array_merge($old,$settings);if(!is_int($merged['max_workers'])||$merged['max_workers']<1||$merged['max_workers']>64||!is_bool($merged['maintenance_mode'])||!in_array($merged['log_level'],['debug','info','warning','error'],true))throw new ApiException(422,'validation_error','Invalid setting types or values.',['settings'=>'typed values out of range']);$next=(int)$current['version']+1;$db->prepare('INSERT INTO configuration_versions(server_id,settings,version,created_at) VALUES(?,?,?,?)')->execute([$s['id'],json_encode($merged,JSON_THROW_ON_ERROR),$next,gmdate(DATE_ATOM)]);$repo->audit((int)$u['id'],(int)$s['id'],'configuration.updated','Version '.$next);return$ok($r,['server_id'=>(int)$s['id'],'settings'=>$merged,'version'=>$next]);});
// SYS-09
$app->get('/api/alerts',function($q,$r)use($auth,$repo,$ok){$auth->user($q,['operator']);$p=$q->getQueryParams();[$l,$o]=Http::page($q);$severity=(string)($p['severity']??'');$status=(string)($p['status']??'');if($severity!==''&&!in_array($severity,['info','warning','critical'],true))throw new ApiException(422,'validation_error','Invalid severity.',['severity'=>'unsupported']);if($status!==''&&!in_array($status,['open','acknowledged','resolved'],true))throw new ApiException(422,'validation_error','Invalid status.',['status'=>'unsupported']);$sql='SELECT * FROM alerts WHERE 1=1';$args=[];if(isset($p['serverId'])){$repo->server((int)$p['serverId']);$sql.=' AND server_id=?';$args[]=(int)$p['serverId'];}if($severity!==''){$sql.=' AND severity=?';$args[]=$severity;}if($status!==''){$sql.=' AND status=?';$args[]=$status;}$sql.=' ORDER BY id DESC LIMIT ? OFFSET ?';$args[]=$l;$args[]=$o;return$ok($r,['items'=>$repo->rows($sql,$args)]);});
$app->post('/api/alerts/{id}/acknowledge',function($q,$r,$a)use($auth,$repo,$db,$ok){$u=$auth->user($q,['operator']);$x=$repo->one('SELECT * FROM alerts WHERE id=?',[(int)$a['id']]);if($x['status']!=='open')throw new ApiException(409,'invalid_state','Only open alerts can be acknowledged.');$db->beginTransaction();$db->prepare('UPDATE alerts SET status="acknowledged",version=version+1 WHERE id=?')->execute([$x['id']]);$db->prepare('INSERT INTO alert_events(alert_id,actor_id,action,created_at) VALUES(?,?,"acknowledged",?)')->execute([$x['id'],$u['id'],gmdate(DATE_ATOM)]);$db->commit();return$ok($r,$repo->one('SELECT * FROM alerts WHERE id=?',[$x['id']]));});
$app->post('/api/alerts/{id}/resolve',function($q,$r,$a)use($auth,$repo,$db,$ok){$u=$auth->user($q,['operator']);$x=$repo->one('SELECT * FROM alerts WHERE id=?',[(int)$a['id']]);if($x['status']!=='acknowledged')throw new ApiException(409,'invalid_state','Acknowledge the alert before resolving.');$d=Http::body($q);Http::required($d,['note']);$db->beginTransaction();$db->prepare('UPDATE alerts SET status="resolved",resolution_note=?,version=version+1 WHERE id=?')->execute([$d['note'],$x['id']]);$db->prepare('INSERT INTO alert_events(alert_id,actor_id,action,created_at) VALUES(?,?,"resolved",?)')->execute([$x['id'],$u['id'],gmdate(DATE_ATOM)]);$db->commit();return$ok($r,$repo->one('SELECT * FROM alerts WHERE id=?',[$x['id']]));});
// SYS-10
$app->get('/api/health-check-targets',function($q,$r)use($auth,$repo,$ok){$auth->user($q,['operator','admin']);return$ok($r,['items'=>$repo->rows('SELECT * FROM health_check_targets ORDER BY id')]);});
$app->post('/api/health-check-targets',function($q,$r)use($auth,$repo,$db,$duplicate,$ok){$auth->user($q,['operator','admin']);$d=Http::body($q);Http::required($d,['name','type','endpoint']);self::validateTarget($d['type'],$d['endpoint']);$interval=(int)($d['interval_seconds']??60);if($interval<10||$interval>3600)throw new ApiException(422,'validation_error','Invalid interval.',['interval_seconds'=>'must be 10..3600']);$duplicate(fn()=>$db->prepare('INSERT INTO health_check_targets(name,type,endpoint,interval_seconds,enabled) VALUES(?,?,?,?,1)')->execute([$d['name'],$d['type'],$d['endpoint'],$interval]));$id=(int)$db->lastInsertId();$db->prepare('INSERT INTO health_check_results(target_id,status,latency_ms,checked_at) VALUES(?,"up",15,?)')->execute([$id,gmdate(DATE_ATOM)]);return$ok($r,$repo->one('SELECT * FROM health_check_targets WHERE id=?',[$id]),201);});
$app->patch('/api/health-check-targets/{id}',function($q,$r,$a)use($auth,$repo,$db,$version,$ok){$auth->user($q,['operator','admin']);$x=$repo->one('SELECT * FROM health_check_targets WHERE id=?',[(int)$a['id']]);$d=Http::body($q);$version($d,$x);$type=(string)($d['type']??$x['type']);$endpoint=(string)($d['endpoint']??$x['endpoint']);self::validateTarget($type,$endpoint);$interval=(int)($d['interval_seconds']??$x['interval_seconds']);if($interval<10||$interval>3600)throw new ApiException(422,'validation_error','Invalid interval.',['interval_seconds'=>'must be 10..3600']);$db->prepare('UPDATE health_check_targets SET name=?,type=?,endpoint=?,interval_seconds=?,enabled=?,version=version+1 WHERE id=?')->execute([(string)($d['name']??$x['name']),$type,$endpoint,$interval,(int)(bool)($d['enabled']??$x['enabled']),$x['id']]);return$ok($r,$repo->one('SELECT * FROM health_check_targets WHERE id=?',[$x['id']]));});
$app->delete('/api/health-check-targets/{id}',function($q,$r,$a)use($auth,$repo,$db){$auth->user($q,['operator','admin']);$x=$repo->one('SELECT * FROM health_check_targets WHERE id=?',[(int)$a['id']]);$db->prepare('DELETE FROM health_check_targets WHERE id=?')->execute([$x['id']]);return$r->withStatus(204);});
$app->get('/api/health-check-targets/{id}/results',function($q,$r,$a)use($auth,$repo,$ok){$auth->user($q,['operator','admin']);$x=$repo->one('SELECT * FROM health_check_targets WHERE id=?',[(int)$a['id']]);return$ok($r,['items'=>$repo->rows('SELECT * FROM health_check_results WHERE target_id=? ORDER BY id DESC LIMIT 100',[$x['id']])]);});
// SYS-11
$app->get('/api/admin/api-tokens',function($q,$r)use($auth,$repo,$ok){$auth->user($q,['admin']);return$ok($r,['items'=>$repo->rows('SELECT id,name,scopes,token_prefix,status,rotated_at,created_at FROM api_tokens ORDER BY id')]);});
$app->post('/api/admin/api-tokens',function($q,$r)use($auth,$repo,$db,$duplicate,$ok){$auth->user($q,['admin']);$d=Http::body($q);Http::required($d,['name']);$scopes=self::scopes($d['scopes']??null);$token='sys_'.bin2hex(random_bytes(16));$duplicate(fn()=>$db->prepare('INSERT INTO api_tokens(name,scopes,token_hash,token_prefix,status,created_at) VALUES(?,?,?,?,"active",?)')->execute([$d['name'],json_encode($scopes,JSON_THROW_ON_ERROR),hash('sha256',$token),substr($token,0,10),gmdate(DATE_ATOM)]));return$ok($r,['id'=>(int)$db->lastInsertId(),'name'=>$d['name'],'scopes'=>$scopes,'token'=>$token],201);});
$app->post('/api/admin/api-tokens/{id}/rotate',function($q,$r,$a)use($auth,$repo,$db,$ok){$auth->user($q,['admin']);$x=$repo->one('SELECT * FROM api_tokens WHERE id=?',[(int)$a['id']]);if($x['status']!=='active')throw new ApiException(409,'invalid_state','Revoked token cannot rotate.');$token='sys_'.bin2hex(random_bytes(16));$db->prepare('UPDATE api_tokens SET token_hash=?,token_prefix=?,rotated_at=? WHERE id=?')->execute([hash('sha256',$token),substr($token,0,10),gmdate(DATE_ATOM),$x['id']]);return$ok($r,['id'=>(int)$x['id'],'token'=>$token]);});
$app->delete('/api/admin/api-tokens/{id}',function($q,$r,$a)use($auth,$repo,$db){$auth->user($q,['admin']);$x=$repo->one('SELECT * FROM api_tokens WHERE id=?',[(int)$a['id']]);if($x['status']==='revoked')throw new ApiException(409,'invalid_state','Token is already revoked.');$db->prepare('UPDATE api_tokens SET status="revoked" WHERE id=?')->execute([$x['id']]);return$r->withStatus(204);});
// SYS-12
$app->get('/api/admin/audit-events',function($q,$r)use($auth,$repo,$ok){$auth->user($q,['admin']);[$l,$o]=Http::page($q);return$ok($r,['items'=>$repo->rows('SELECT * FROM audit_events ORDER BY id DESC LIMIT ? OFFSET ?',[$l,$o])]);});
$app->get('/api/admin/users',function($q,$r)use($auth,$repo,$ok){$auth->user($q,['admin']);return$ok($r,['items'=>$repo->rows('SELECT id,email,role,status,version FROM users ORDER BY id')]);});
$app->patch('/api/admin/users/{id}/roles',function($q,$r,$a)use($auth,$repo,$db,$version,$ok){$admin=$auth->user($q,['admin']);$x=$repo->one('SELECT * FROM users WHERE id=?',[(int)$a['id']]);$d=Http::body($q);$version($d,$x);$role=$d['role']??null;if(!in_array($role,['operator','admin'],true))throw new ApiException(422,'validation_error','Invalid role.',['role'=>'operator or admin']);if((int)$x['id']===(int)$admin['id']&&$role!=='admin')throw new ApiException(409,'invalid_state','Admin cannot remove own admin role.');$db->prepare('UPDATE users SET role=?,version=version+1 WHERE id=?')->execute([$role,$x['id']]);return$ok($r,$repo->one('SELECT id,email,role,status,version FROM users WHERE id=?',[$x['id']]));});
$app->post('/api/admin/servers',function($q,$r)use($auth,$repo,$db,$duplicate,$ok){$u=$auth->user($q,['admin']);$d=Http::body($q);Http::required($d,['name','hostname','environment']);if(!in_array($d['environment'],['production','staging','development'],true))throw new ApiException(422,'validation_error','Invalid environment.',['environment'=>'unsupported']);if(!preg_match('/^[a-z0-9.-]+$/',$d['hostname']))throw new ApiException(422,'validation_error','Invalid hostname.',['hostname'=>'lowercase host label required']);$duplicate(fn()=>$db->prepare('INSERT INTO servers(name,hostname,environment,status) VALUES(?,?,?,"unknown")')->execute([$d['name'],$d['hostname'],$d['environment']]));$id=(int)$db->lastInsertId();$db->prepare('INSERT INTO configuration_versions(server_id,settings,version,created_at) VALUES(?, ?,1,?)')->execute([$id,'{"max_workers":4,"maintenance_mode":false,"log_level":"info"}',gmdate(DATE_ATOM)]);$repo->audit((int)$u['id'],$id,'server.created',$d['name']);return$ok($r,$repo->server($id),201);});
$app->patch('/api/admin/servers/{id}',function($q,$r,$a)use($auth,$repo,$db,$version,$ok){$auth->user($q,['admin']);$x=$repo->server((int)$a['id']);$d=Http::body($q);$version($d,$x);$status=$d['status']??$x['status'];if(!in_array($status,['healthy','degraded','offline','maintenance','unknown'],true))throw new ApiException(422,'validation_error','Invalid server status.',['status'=>'unsupported']);$db->prepare('UPDATE servers SET name=?,environment=?,status=?,version=version+1 WHERE id=?')->execute([(string)($d['name']??$x['name']),(string)($d['environment']??$x['environment']),$status,$x['id']]);return$ok($r,$repo->server((int)$x['id']));});
}private static function validateTarget(string$type,string$endpoint):void{if(!in_array($type,['http','tcp'],true))throw new ApiException(422,'validation_error','Invalid target type.',['type'=>'http or tcp']);$valid=$type==='http'?preg_match('#^http://127\.0\.0\.1:(8080|8081)/(health|status)$#',$endpoint):preg_match('/^127\.0\.0\.1:(9000|9001)$/',$endpoint);if(!$valid)throw new ApiException(422,'validation_error','Target is outside the local allow-list.',['endpoint'=>'approved local target required']);}private static function scopes(mixed$x):array{if(!is_array($x)||!$x)throw new ApiException(422,'validation_error','Scopes required.',['scopes'=>'non-empty array']);$allowed=['servers:read','metrics:read','jobs:run'];foreach($x as$s)if(!in_array($s,$allowed,true))throw new ApiException(422,'validation_error','Invalid token scope.',['scopes'=>'unsupported']);return array_values(array_unique($x));}}
